### ISSUE TITLE
Setting "ssr: false" causing NX + Vercel deployment to break

### ISSUE THREAD

**Issue by MitchSmoot** [analogjs/analog#1002]
### Please provide the environment you discovered this bug in.

New Analog app (latest package versions as of April 4 2024) as a NX Standalone Project on a Vercel deployment.
Repo: https://github.com/MitchSmoot/deployment-test
Build Command: NX Build
Output Directory: .vercel
Install Command: Default
Development Command: Default

### Which area/package is the issue in?

create-analog

### Description

Originally discovered this issue when attempting to deploy my analog project to Vercel. I managed to pinpoint and replicate the cause. With the standard configuration, everything works like in the docs. But when "ssr: false" is added to Analog's settings in the Vite config, it seems to break the deployment, causing Vercel to return a 404. Despite the error, deployment logs show pages as being successfully built. The issue was replicated in my test repo. My second to last commit in the test repo will deploy properly, but the newest commit, which adds "ssr: false" leads to a 404 error page.

Steps to reproduce:
1: Create standalone NX, Analog application, as shown in docs:
npx create-nx-workspace@latest --preset=@analogjs/platform
2: Set NX default Project, as shown in docs. At this stage, the app would display correctly if deployed before step 3.
3: Add "ssr: false," to the Analog configuration in the project's vite.config.ts
4: Deploy to Vercel with build command: "NX build" and output directory: ".vercel"
5: Visit deployed page to see 404 error.

### Please provide the exception or error you saw

```true
404 Cannot find any route matching /.
```

### Other information

I'm not sure I have a deep enough understanding of all that goes into deployment in order to handle the PR for this fix. But I will gladly help in whatever way is most needed.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
This is not a bug, but an obscure setting. Yes, it fails because setting `ssr` disables the server and prerendering altogether. If you don't want to deploy the server, and just want the client-side app along with some pre-rendered pages, use `static: true` and leave SSR enabled.

We could look at change `ssr: boolean` to `server: boolean` in the future
