### ISSUE TITLE
Docs: add example of using a resolver for metatags for markdown component

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#1014]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

We have an example resolver for getting metatags for the route when using the custom markdown component.

https://github.com/analogjs/analog/blob/beta/apps%2Fblog-app%2Fsrc%2Fapp%2Fpages%2Fblog%2F%5Bslug%5D.page.ts#L16

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by AmGarera** [comment]
@brandonroberts I've submitted a PR for this issue. When you have the time let me know if anything needs to be tweaked/modified. Just glad I can give back in anyway to the analog project and angular community as a whole!
