### ISSUE TITLE
Data binding does't work when deploying to CloudFlare (NX)

### ISSUE THREAD

**Issue by dalenguyen** [analogjs/analog#1015]
### Please provide the environment you discovered this bug in.

Repo: https://github.com/dalenguyen/cloudflare-challenge/pull/6
Link: https://add-whisper.cloudflare-challange.pages.dev/ (try to click on the the recording, the log shows the result, but the form field is not updated)
Host: Cloudflare Pages

### Which area/package is the issue in?

Don't know / other

### Description

I'm trying to adding a simple form and use data binding for updating the value. However, the form field is not updated properly even though the data is present. Here what I tried:

- Use simple ngModel
- Use Reactive Forms
- Add extra `detectChanges`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by dalenguyen** [comment]
Updated: the binding works when using [viewChild](https://angular.io/api/core/viewChild) to manually set the value of the input.

**Comment by dalenguyen** [comment]
Hi @brandonroberts, I don't think this is fixed yet. The data binding (ngModel) or change detection doesn't really work when deploying to Cloudflare.

**Comment by dalenguyen** [comment]
I think the vite.config.ts for NX has an issue. I was trying to mimic the vite.config from non NX app. It does work, so I think these two are the cause: reportCompressedSize & commonjsOptions.

```
   build: {
      reportCompressedSize: true,
      commonjsOptions: { transformMixedEsModules: true },
      target: ["es2020"],
    },
```

**Comment by dalenguyen** [comment]
Probably, it's not present in the normal create command. I can create a PR for this after some testings if you want :D

**Comment by brandonroberts** [comment]
Sounds good 👍

**Comment by brandonroberts** [comment]
Closed by https://github.com/analogjs/analog/pull/1052
