### ISSUE TITLE
Catch-all Routes can't be passed as input

### ISSUE THREAD

**Issue by alexcibotari** [analogjs/analog#1016]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/github-wjglg2?file=src%2Fapp%2Fpages%2F%5B...product%5D.page.ts

### Which area/package is the issue in?

router

### Description

I consume a Headless CMS Localess: https://github.com/Lessify/localess
For that, I created one route that would capture all routes and fetch data via API using the feature: **Using Route Component Input Bindings**
For the moment the feature works only for dynamic routes, which limits me only to a one-page level, where I actually would like to be able to capture all possible routes.

Dynamic Rout will work with the next
````
/coffee
/milk
/sugar
````

But it will not be able to handle next 
````
/coffee/sugar/line
/milk/cow/grass
/en/free/products
/en/company/contact
````

### Other information

Same time ActivatedRouteSnapshot.params is empty

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
You don't be able to use the router input bindings here because a catch-all route isn't captured as a route parameter. You can use the `router.url` to get the full URL path that was used.

https://stackblitz.com/edit/github-wjglg2-5fczvg?file=src%2Fapp%2Fpages%2F[...product].page.ts

**Comment by alexcibotari** [comment]
@brandonroberts , thank you for the explanation. I think the documentation needs to be updated to make sure others are not making the same mistakes.

**Comment by alexcibotari** [comment]
I found another issue when I had only one page with catch-all pages and Server-Side Data Fetching for that page. I'm receiving a next error. I have updated the example also 

````
ERROR HttpErrorResponse {
  headers: HttpHeaders {
    normalizedNames: Map(4) {
      'connection' => 'connection',
      'content-length' => 'content-length',
      'content-type' => 'content-type',
      'date' => 'date'
    },
    lazyUpdate: null,
    headers: Map(4) {
      'connection' => [Array],
      'content-length' => [Array],
      'content-type' => [Array],
      'date' => [Array]
    }
  },
  status: 404,
  statusText: 'Cannot find any route matching /_analog/pages/.',
  url: 'http://localhost:5173/api/_analog/pages/',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for http://localhost:5173/api/_analog/pages/: 404 Cannot find any route matching /_analog/pages/.',
  error: {
    url: '/_analog/pages/',
    statusCode: 404,
    statusMessage: 'Cannot find any route matching /_analog/pages/.',
    message: 'Cannot find any route matching /_analog/pages/.'
  }
}
````
