### ISSUE TITLE
Easier Resolvers

### ISSUE THREAD

**Issue by jdgamble555** [analogjs/analog#1018]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Currently in order to create a resolver, you must declare something like:
```
export const routeMeta: RouteMeta = {
  resolve: { data: myResolver }
};
```
And when you call it you need to do:
```ts
route = inject(ActivatedRoute);
data = route.data.pipe(map(r => r.data));
```
In order to get the observable.

### Describe any alternatives/workarounds you're currently using

It would be nice if this were automatic and we could just do:
```ts
data = injectResolver(myResolver);
```
This would be a first step to better async usability better markdown imports etc.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Interesting

- Are you saying just to make injecting it easier? Or using `injectResolver(myResolver)` somehow automatically registers a resolver? 
- Why wouldn't this be something like `injectResolver<typeof myResolver>('data')`?

**Comment by jdgamble555** [comment]
I thought more about this and don't see how this could work. Closing. Thanks for looking at it.
