### ISSUE TITLE
How to read server load from RouteMeta resolver

### ISSUE THREAD

**Issue by alexcibotari** [analogjs/analog#1022]
### Which scope/s are relevant/related to the feature request?

router

### Information

As a developer, I would like to have access to server data in the Route Metadata Resolve Function

### Describe any alternatives/workarounds you're currently using

At the moment I see examples of how to access content data, but not load data from the server

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
See https://analogjs.org/docs/features/data-fetching/server-side-data-fetching#injecting-the-data

**Comment by alexcibotari** [comment]
The object is always undefined in the header resolver , even it is ok in the component input

**Comment by brandonroberts** [comment]
The `title` key is a resolved string/resolver and is on the route itself.

```ts
title = inject(ActivatedRoute).title; // Observable<string>
```

**Comment by alexcibotari** [comment]
Here I will get the Router Title, and in my case, I would like to define it, as I use Localess Headless CMS, all content and page titles are remote. I load content on the server side, and I will need to fill it in the component and RouteMeta 


````ts
// [...slug].server.ts
export const load = async ({ params, fetch }: PageServerLoad) => {
  console.log('server load');
  const slug = params!['slug'] || 'home';
  const document = await fetch<Content>(`remote URL`);
  return {
    document: document
  } satisfies SlugPageServerLoad;
};

// [...slug].page.ts
const documentNameResolver: ResolveFn<string> = (route, state) => {
  return injectLoad<typeof load>() 
    .pipe(
      tap((it) => console.log(it)), // here the result is always undefined
      map(it => it?.document?.name || 'Unknown')
    )
};

export const routeMeta: RouteMeta = {
  title: documentNameResolver,
};

@Component({...})
export default class SlugComponent implements OnInit {
  load = input.required<SlugPageServerLoad>();
}
````
