### ISSUE TITLE
Can't build empty project

### ISSUE THREAD

**Issue by Smip** [analogjs/analog#1023]
### Please provide the environment you discovered this bug in.

Windows 11
Node v18.20.2
Angular 17

### Which area/package is the issue in?

vite-plugin-nitro

### Description

I created a new project via `npm create analog@latest` and tried to build with prerender, always getting unknown files instead of prerendered HTMLS.

The path `\dist\analog\public\` has the `index` file (without extension) with the next content:

`[false,{"name":"@analogjs/vite-plugin-nitro"}]`

Also, when I tried to run ssr with the command `node \dist\analog\server\index.mjs` in the browser, I got the same content.

I tried different versions of analog and vite, and the result is the same.
I have no idea what to try.

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [X] No

**Comment by brandonroberts** [comment]
Try the `beta` for the next release as this may have been resolved.

```sh
npm create analog@beta my-analog-app
```

**Comment by Smip** [comment]
I tried and the result is the same ;(

Here are all the commands that I executed:

https://gist.github.com/Smip/b5bb71d47619d99ed4b003a038a4d553

the result is:

```cmd
C:\Users\asok1\Projects\my-analog-app>dir dist\analog\public

 Directory of C:\Users\asok1\Projects\my-analog-app\dist\analog\public

11.04.2024  09:02 AM    <DIR>          .
11.04.2024  09:01 AM    <DIR>          ..
11.04.2024  08:58 AM                 0 .gitkeep
11.04.2024  08:58 AM            12,121 analog.svg
11.04.2024  09:01 AM    <DIR>          assets
11.04.2024  09:02 AM                46 index
11.04.2024  08:58 AM             1,497 vite.svg
               4 File(s)         13,664 bytes
               3 Dir(s)  41,263,927,296 bytes free

C:\Users\asok1\Projects\my-analog-app>more dist\analog\public\index
[false,{"name":"@analogjs/vite-plugin-nitro"}]
```

**Comment by mnsdali** [comment]
Hello, I am facing the same issue here, @brandonroberts could you guys please check it. 
I tried with hello world app with a custom route and on prerender only no extension files get generated ,along side the javascripts, with this same content:
`[false,{"name":"@analogjs/vite-plugin-nitro"}]`
![image](https://github.com/analogjs/analog/assets/91077017/1e1108d7-c010-4839-b990-36645b026f57)

**Comment by brandonroberts** [comment]
If you set the prerender routes in the vite config to an empty array does it work?

```ts
analog({
  prerender: {
    routes: []
  }
})
```

**Comment by mnsdali** [comment]
@brandonroberts   pretty much not prerendered
![image](https://github.com/analogjs/analog/assets/91077017/0942a7e9-b7bf-4162-b9a6-da17a65602f6)

**Comment by Smip** [comment]
> @brandonroberts pretty much not prerendered ![image](https://private-user-images.githubusercontent.com/91077017/322023391-0942a7e9-b7bf-4162-b9a6-da17a65602f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzM4NDMsIm5iZiI6MTcxMjkzMzU0MywicGF0aCI6Ii85MTA3NzAxNy8zMjIwMjMzOTEtMDk0MmE3ZTktYjdiZi00MTYyLWI5YTYtZGExN2E2NTYwMmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE0NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZjU1MzhlY2ZkNGRlZDA5ZmNkZGI2OTZiZTZmYTRkNWZiN2Y4MTk1ZjU2ZTU2ZWFlNmI4NWViNWYwMDc1N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tzUwMYEXb11_mkIKHZAMSe6-q3idMei1LXx96LNJigQ)

I have the same

**Comment by Smip** [comment]
After some investigation, I tried to add to the renderer.mjs file some printing:

```js
import render from '#analog/ssr';
import template from '#analog/index';

export default eventHandler(async (event) => {
  const html = await render(event.node.req.url, template, {
    req: event.node.req,
    res: event.node.res,
  });
  console.log(html);
  console.log(template);
  console.log(render);
  return html;
});
```
and got the next result:

```
[
  false,
  {
    name: '@analogjs/vite-plugin-nitro',
    config: [AsyncFunction: config],
    configureServer: [AsyncFunction: configureServer],
    closeBundle: [AsyncFunction: closeBundle]
  }
]
[Function: nitro]
[Function: nitro]
```
so html is the same as what we have as prerendered files, I think the problem is somewhere here.

If I understood correctly, `#analog/ssr` should be a function from ssr but I got a nitro function. I also tried to make a manual config for Nitro and run it, I tried different formats of alias, but nothing helped.

**Comment by brandonroberts** [comment]
@Smip thanks, that helps. Will take a look

**Comment by mnsdali** [comment]
updates ?
