### ISSUE TITLE
How to read server load from RouteMeta resolver

### ISSUE THREAD

**Issue by alexcibotari** [analogjs/analog#1039]
### Which scope/s are relevant/related to the feature request?

router

### Information

I will reopen #1022 , as the ticket has not received an answer and is closed.

As a developer, I would like to have access to server data in the Route Metadata Resolve Function.
Here I will get the Router Title, and in my case, I would like to define it, as I use Localess Headless CMS, all content and page titles are remote. I load content on the server side, and I will need to fill it in the component and RouteMeta.

````ts
// [...slug].server.ts
export const load = async ({ params, fetch }: PageServerLoad) => {
  console.log('server load');
  const slug = params!['slug'] || 'home';
  const document = await fetch<Content>(`remote URL`);
  return {
    document: document
  } satisfies SlugPageServerLoad;
};

// [...slug].page.ts
const documentNameResolver: ResolveFn<string> = (route, state) => {
  return injectLoad<typeof load>() 
    .pipe(
      tap((it) => console.log(it)), // here the result is always undefined
      map(it => it?.document?.name || 'Unknown')
    )
};

export const routeMeta: RouteMeta = {
  title: documentNameResolver,
};

@Component({...})
export default class SlugComponent implements OnInit {
  load = input.required<SlugPageServerLoad>();
}
````

### Describe any alternatives/workarounds you're currently using

No Work arounds.Workarounds

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by jdgamble555** [comment]
The `injectLoad` function is injecting a resolver as you can see on [this line](https://github.com/analogjs/analog/blob/e89cd18b69fcfbc30fcf1fe514058ee00099de3e/packages/router/src/lib/inject-load.ts#L13). So you're trying to inject a resolver inside a resolver. Resolvers are defined in an object at the same time, so you can't  get something from the `ActivatedRoute` that hasn't finished defining yet. 

It is defined as `load` on [this line](https://github.com/analogjs/analog/blob/e89cd18b69fcfbc30fcf1fe514058ee00099de3e/packages/router/src/lib/route-config.ts#L32).

If you want to do something in the resolver that is dependent on your `load` function, just fetch the api route that is created by your `load` function. It will be located at:
```
http://localhost:5173/api/_analog/pages/__YOUR_PAGE_NAME__
```
That being said, it would be useful to be able to import this in a resolver, but it would have to be a different function.

J

**Comment by 01Vladimir10** [comment]
Why don't you simply inject Angular's Meta service to your component and add the metadata in the component's constructor?

```ts
class FooComponent {

private readonly meta = inject(Meta)
private readonly titleService = inject(Title)
load = input.required<SlugPageServerLoad>()

constructor() {
    this.titleService.setTitle(this.load().title)
    this.meta.updateTag({ name: 'og:title', content: this.load().title })
}

}
```

Afaik, the metadata will be added server side so you should be able to achieve the same result.

**Comment by brandonroberts** [comment]
The `load` resolver can be called from within another resolver by accessing it through the route config.

```ts
export const routeMeta: RouteMeta = {
  resolve: {
    data: async(route) => {
      // call server load resolver for this route from another resolver
      const data = await route.routeConfig?.resolve?.['load']?.(route);

      return { ...data };
    }
  }
}
```

We can add a utility function for this named `getLoadResolver` and use it as `getLoadResolver(route)`.

```ts
import { getLoadResolver } from '@analogjs/router';

export const routeMeta: RouteMeta = {
  resolve: {
    data: async(route) => {
      // call server load resolver for this route from another resolver
      const data = await getLoadResolver(route);

      return { ...data };
    }
  }
}
```
