### ISSUE TITLE
[REPO]: Yarn2 or PNPM as package manager 

### ISSUE THREAD

**Issue by TicTak21** [analogjs/analog#104]
### Which scope/s are relevant/related to the feature request?

Don't known / other

### Information

It would be nice to use [Yarn2](https://dev.to/arcanis/introducing-yarn-2-4eh1) or [PNPM](https://pnpm.io/) as package manager.

Pros:
1) Faster `install`
2) [Plugins](https://yarnpkg.com/features/plugins)(Yarn2)
3) Faster CI(Should be tested)
4) Cache

Cons:
1) Yarn2(with Plug-n-Play) requires configuration

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Seems reasonable to be to offer support for this. What extra configuration is needed?

**Comment by TicTak21** [comment]
For PNPM:
1) Replace `yarn.lock` with `pnpm-lock` via `pnpm install`
2) Replace yarn commands with pnpm commands inside CI

For Yarn2:
Follow [migration guide](https://yarnpkg.com/getting-started/migration#step-by-step)
1. Migrate `yarn.lock` to the v2
2. Remove `node_modules`
3. [Configure PnP](https://yarnpkg.com/getting-started/migration#enabling-it) via `.yarnrc`
4. [Editor support](https://yarnpkg.com/getting-started/migration#editor-support)

PNPM is the simpler option, but I thought I should describe all available options.
  
The idea of PnP is to remove `node_modules` and store all dependencies in a zipped format.
This allows you to put the dependencies along with the repo on github and when someone clones/pulls/changes a branch, there is no need to do `yarn install` because all dependencies are already installed([zero-installs](https://yarnpkg.com/features/zero-installs)).

**Comment by brandonroberts** [comment]
Are you referring to using pnpm for this repo, or for new projects? I don't have any plans to move to pnpm at the moment. I'll revisit a later version of yarn at some point
