### ISSUE TITLE
Angular configuration file Replacements doesn't work

### ISSUE THREAD

**Issue by alexcibotari** [analogjs/analog#1040]
### Please provide the environment you discovered this bug in.

N/A

### Which area/package is the issue in?

create-analog

### Description

I need different configurations based on the type of environment. I use the standard Angular way with ``environment.ts`` file.
I configure ``angular.json`` with fileReplacements parameters.
````json
// angular.json
...
         "development": {
              "mode": "development",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.development.ts"
                }
              ]
            },
...
````

I expect that at build and serve time the replacement will happen.
The result is that nothing is replaced.

### Please provide the exception or error you saw

No error

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
If you're wanting to stick with an environment.ts file, I would suggest having a single `environment.ts` and using a `.env` file for your variables.

```sh
VITE_MY_KEY=foo
```

https://vitejs.dev/guide/env-and-mode.html

```ts
export const environment {
  myKey: import.meta.env['VITE_MY_KEY']
}
```

There's also the `@nx/vite/plugins/rollup-replace-files.plugin.js` you can use.

Source: https://github.com/nrwl/nx/blob/master/packages/vite/plugins/rollup-replace-files.plugin.ts
