### ISSUE TITLE
Bug: yarn fails to install peer dependencies, causing app to fail when serving

### ISSUE THREAD

**Issue by sonukapoor** [analogjs/analog#1045]
### Please provide the environment you discovered this bug in.

Not reproducible via stackblitz. Follow the below steps using `yarn` instead. 

1. yarn create analog
2. Follow the wizard to create an Angular 17 application
3. CD into the project
4. yarn
5. yarn dev

### Which area/package is the issue in?

create-analog

### Description

When using `yarn` or `bun` an exception occurs.

### Please provide the exception or error you saw

```true
❯ yarn dev
yarn run v1.22.22
warning ../../package.json: No license field
$ ng serve
failed to load config from /Users/xxxxx/projects/analog-project/vite.config.ts
An unhandled exception occurred: Cannot find package '@ngtools/webpack' imported from /Users/xxxxx/projects/analog-project/node_modules/@analogjs/vite-plugin-angular/src/lib/host.js
See "/private/var/folders/g2/5zjtwbxn4870l3qh6mxyl_vr0000gn/T/ng-9sXu9m/angular-errors.log" for further details.
error Command failed with exit code 127.
```

### Other information

To fix this, install `@angular-devkit/build-angular` manually in your project.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by ajitzero** [comment]
This is a [known issue](https://github.com/yarnpkg/yarn/issues/1503) with yarn, with no real workaround as a library author.

At best, we can update the README & Docs page for Installation to explicitly mention the peer deps in yarn's case. I've done the same for one of my libraries.

I will can make a PR for this.

**Comment by brandonroberts** [comment]
Thanks @ajitzero. @sonukapoor is taking this one. My recommendation would be to add the necessary dependencies (@ngtools/webpack, @angular-devkit/build-angular) to the `package.json` when using `yarn create analog@latest`

**Comment by ajitzero** [comment]
Cool! I was wondering if there is some actual fix instead. This works for me. Also, apparently Bun has the same issue?

**Comment by brandonroberts** [comment]
Bun installs peer dependencies by default. I think we just need to add `@ngtools/webpack` to the peer dependencies for `@analogjs/vite-plugin-angular` to fix that, but that can be done separately

**Comment by brandonroberts** [comment]
Confirmed the app serves correctly on a fresh project with `bun` and `yarn` with `1.3.0-beta.3`
