### ISSUE TITLE
Feature : Draft Mode

### ISSUE THREAD

**Issue by alexcibotari** [analogjs/analog#1054]
### Which scope/s are relevant/related to the feature request?

router

### Information

As a Developer I would like to have a Draft Mode feature like in NextJS : https://nextjs.org/docs/app/building-your-application/configuring/draft-modea 

### Describe any alternatives/workarounds you're currently using

I have implemented the feature in my project, but I need help to create a PR into Analog JS

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Will revisit this at some point. I think using markdown front-matter for indicating draft mode is a decent solution for now
