### ISSUE TITLE
Missing nx path plugin in vite plugin angular

### ISSUE THREAD

**Issue by ezzabuzaid** [analogjs/analog#1056]
### Please provide the environment you discovered this bug in.

The example is not prepared for NX, sorry 😥

### Which area/package is the issue in?

create-analog

### Description

Following this blog [Faster testing with Angular and Vitest ⚡️](https://dev.to/brandontroberts/faster-testing-with-angular-and-vitest-274n), I got vitest to work but with small missing detail in NX environment.

### Please provide the exception or error you saw

```true
Error: Failed to resolve import "@org/core/utils" from "libs/core/src/lib/utils/utils.service.ts". Does the file exist?
```

### Other information

Adding `nxViteTsPaths()` fixes the issue.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Fixed in https://github.com/analogjs/analog/pull/1057
