### ISSUE TITLE
Add documentation around needed Netlify config for server features

### ISSUE THREAD

**Issue by RyanClementsHax** [analogjs/analog#1060]
Which scope/s are relevant/related to the feature request?

Docs

### Information

Deploying a static analog application works just fine. Netlify infers the publish directory and build command just fine.

Example generated from `npm create analog@latest`:
https://analog-project.netlify.app/
https://github.com/RyanClementsHax/analog-project
Build settings:
![image](https://github.com/analogjs/analog/assets/20916810/c43e8dd3-0607-435f-a8e2-e08038c45c8b)

---

Deploying a server-full analog application runs into some issues. When deployed, the front end seems to have trouble connecting to the backend.

Example generated from `npx create-nx-workspace@latest --preset=@analogjs/platform`:
https://analog-nx.netlify.app/
https://github.com/RyanClementsHax/analog-nx
Build settings:
![image](https://github.com/analogjs/analog/assets/20916810/eea8a04c-7c88-445c-8902-f406cdf40e0d)
```toml
# netlify.toml
[build]
  command = "nx build analog-app"
  publish = "dist/analog-app/client"
  functions = "dist/analog-app/analog/server"
```
Error:
![image](https://github.com/analogjs/analog/assets/20916810/a4aefef4-3fbc-4e9a-a1d4-2cfb973861f7)

Deployed assets: [deploy-662c2aa458585500082de2b6.zip](https://github.com/analogjs/analog/files/15135790/deploy-662c2aa458585500082de2b6.zip) 

---

I'm sure I'm just missing a simple setting. I'd be happy to be the one to update the docs or generators as needed

---

Other issues consulted:
https://github.com/analogjs/analog/issues/631
https://github.com/analogjs/analog/issues/492

---

### Describe any alternatives/workarounds you're currently using

Haven't found the right config to get this to work yet.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
We have deployment docs here for Netlify

https://analogjs.org/docs/features/deployment/providers#netlify

Nx is a little different because of the output directory, but the setup is mostly the same

**Comment by RyanClementsHax** [comment]
Ah I see where I went wrong now. I tried that config before, but I think I messed up something. It is working for me now. Thanks for the help.

Mind if I add an example `netlify.toml` and some links to netlify's documentation that explain what the `publish` and `functions` directories are?

**Comment by brandonroberts** [comment]
Yep, that helps
