### ISSUE TITLE
Docs: add guide on using environment variables

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#1068]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Angular projects usually have an environment.ts/environment.prod.ts for handling environment variables. Analog lets you use `.env` files directly. We should have a guide on the approaches.

1. Use one environment.ts file with the environment variables inside it
2. Use the vite environment variables directly.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Thewizard18n** [comment]
@brandonroberts  I would like to take this ... it is possible ?

**Comment by luishcastroc** [comment]
> @brandonroberts  I would like to take this ... it is possible ?
> 
> 

Go ahead and:) PRs are welcome

**Comment by brandonroberts** [comment]
Closed by https://github.com/analogjs/analog/pull/1306

https://analogjs.org/docs/guides/migrating#setting-up-environments
