### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by muuvmuuv** [analogjs/analog#107]
### Please provide the environment you discovered this bug in.

Our companies own app, but I bet an Ionic full feature starter (e.g. "my-first-app") will produce the same error.

### Which area/package is the issue in?

vite-plugin-angular

### Description

Just tested quick and added Analog-Vite to our companies Angular-Ionic-Capacitor App and ran the following:

```
NODE_OPTIONS="--max-old-space-size=16000" pnpm vite
```

it never shows the application, it just crashs after taking all RAM I allowed Node to take. Also tried with Bun but Bun does not work well with Vite yet.

### Please provide the exception or error you saw

```true
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
This should be resolved
