### ISSUE TITLE
How can I do api request?

### ISSUE THREAD

**Issue by antonkri97** [analogjs/analog#1073]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/github-blmgr2?file=src%2Fapp%2Fpages%2Findex.page.ts

### Which area/package is the issue in?

create-analog

### Description

Hi everyone! 

I tried to call the very basic API using filesystem-based approach. But no matter which URL I try, nothing works. Tell me what I'm doing wrong

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
The API server isn't available in StackBlitz, but when you run it locally it will work correctly. Just use the full URL, such as `http://localhost:5173/api/v1/hello`

**Comment by antonkri97** [comment]
Yes, now it finally works, thanks!

I'm not sure, but it wasn't the most obvious detail to me. Maybe we can add this detail to the documentation, what do you think?

**Comment by brandonroberts** [comment]
Sure. A guide on general data fetching patterns would be nice
