### ISSUE TITLE
Docs: explain on how to name nested API routes

### ISSUE THREAD

**Issue by geromegrignon** [analogjs/analog#1083]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Not specific to Analog docs as not explained in Nitro ones, there is no clear indication about how to name nested files.

Given I have two routes:
- GET /communities
- GET /communities/upcoming

There proper solution is (as far as i know):

```
/communities
  index.get.ts
  /upcoming
    index.get.ts
```

The documentation does not explain you can name files with `index` (even if it might sound obvious when you get familiar with file based routing).

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
TIL 😅

Would probably be good to upstream this to the Nitro docs also.

**Comment by geromegrignon** [comment]
opened there: https://github.com/unjs/nitro/issues/2415

**Comment by brandonroberts** [comment]
Cool, I think we can add an example to ours also
