### ISSUE TITLE
cloudflare wrangler not working with the analog-app example

### ISSUE THREAD

**Issue by stewones** [analogjs/analog#1099]
### Please provide the environment you discovered this bug in.

to reproduce run `BUILD_PRESET=cloudflare-pages nx build analog-app && npx wrangler pages dev dist/apps/analog-app/analog/public`

### Which area/package is the issue in?

Don't know / other

### Description

I'm interested in debugging an issue with cloudflare wrangler (Idk if actual deployment works) where a server load function doesn't return JSON, instead it's returning the index/home HTML.

then I went to try some analog example that has a load function to check and noticed that it doesn't even load the page

### Please provide the exception or error you saw

```true
500 Request Error
performance is not defined
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by dalenguyen** [comment]
Have you tried this one? 

https://developers.cloudflare.com/pages/framework-guides/deploy-an-analog-site/

**Comment by stewones** [comment]
holy moly, I managed to make my project work. I had messed up with the `.env`, `vite.config` and `main.server.ts` files

thanks @dalenguyen the cloudflare guide shed some light 👍
