### ISSUE TITLE
[FEAT]: Add support for HMR in development mode

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#11]
Vite uses HMR to enable refreshing the app without reloading the whole page. Vite uses HMR closest to the code that accepts HMR.

Angular has some support for this but not as granular as the root app needs to be destroyed and recreated for this to work.

External styles outside of component templates and HTML work as intended.

Prior art: https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/webpack/plugins/hmr/hmr-accept.ts

**Comment by brandonroberts** [comment]
Plugin as-is when used in Vite environment does a flash on each HMR reload. Need to investigate this so it appears native.

**Comment by omerman** [comment]
👍

**Comment by brandonroberts** [comment]
Will revisit this when better HMR support lands in Angular
