### ISSUE TITLE
Can't test with `it/describe.each` and `fakeAsync`

### ISSUE THREAD

**Issue by jahusa02** [analogjs/analog#1115]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/~/github.com/jahusa02/analog-vitest

### Which area/package is the issue in?

vitest-angular

### Description

When a testfile contains `it/describe.each` and `fakeAsync` the tests errors out.

I described the error in this Issue https://github.com/analogjs/analog/issues/841#issuecomment-2110296265|

When I use the patched function (e.g. not importing it via `import { it } from 'vitest'`), the `it.each` tests will fail.

```typescript
TypeError: Cannot read properties of undefined (reading 'withContext')
 ❯ ../../../packages/vite-plugin-angular/setup-vitest.ts:247:31
 ❯ src/lib/+state/effects/add-pending-contract/add-pending-contract.effects.spec.ts:98:6
     96|       { formStateValid: false, contractId: 'foo', satznummer: null },
     97|       { formStateValid: false, contractId: null, satznummer: 'bar' },
     98|     ])(
       |      ^
     99|       'should not post form values if ContractIds are %j',
    100|       ({ formStateValid, contractId, satznummer }) => {
 ❯ _ZoneDelegate.invoke ../../../node_modules/zone.js/fesm2015/zone.js:365:28
 ❯ ZoneImpl.run ../../../node_modules/zone.js/fesm2015/zone.js:111:43
 ❯ ../../../packages/vite-plugin-angular/setup-vitest.ts:41:21
``` 

When I importing `it`, the `fakeAsync` tests will fail with the mentioned `Error: Expected to be running in 'ProxyZone', but it was not found.`, but the `it.each` will pass.

### Please provide the exception or error you saw

```true
Either

TypeError: Cannot read properties of undefined (reading 'withContext')

or

Error: Expected to be running in 'ProxyZone', but it was not found.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by gultyayev** [comment]
I found a fix for it. Working on PR

**Comment by gultyayev** [comment]
In the meantime you could try a dirty patching of the `node_modules` in postinstall. The change is simple. I don't know how long it will take for the fix to appear in the release. Also, you could find potential missed cases.

**Comment by brandonroberts** [comment]
1.6.0 contains the fixes

**Comment by gultyayev** [comment]
I assume it's the second case where you have the imports of utils?
RN, it's not patched and only globals should be used to work properly.

**Comment by gultyayev** [comment]
Well. It works on my repo. However, describe.each is broken. By the same reason 🙃

Will need to make on more PR

**Comment by gultyayev** [comment]
Also, I cannot run Vitest freely. Only on a single thread. Otherwise I get segmentation fault on my macbook. @brandonroberts any ideas what it could be or how to fix? 🤔

**Comment by gultyayev** [comment]
Could you elaborate on why those were chosen as default? The docs say that they are very prone to memory leaks. And even in my 500 tests project a 32 Gb RAM MacBook couldn't handle. Also, it left eventually a number of unclosed node processes.

**Comment by brandonroberts** [comment]
> Could you elaborate on why those were chosen as default? The docs say that they are very prone to memory leaks. And even in my 500 tests project a 32 Gb RAM MacBook couldn't handle. Also, it left eventually a number of unclosed node processes.

`vmThreads` was chosen as the default to mimic the behavior with `jsdom`

Here's some additional context from an issue I filed in the Vitest repo https://github.com/vitest-dev/vitest/issues/4685

**Comment by brandonroberts** [comment]
Great!
