### ISSUE TITLE
[FEAT]: Add support for Angular Material custom package.json exports

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#112]
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

Angular Material uses custom `sass` and `style` properties in the `package.json` exports. When using the imports from Angular Material themes with Vite, it throws an error as it cannot resolve them. This can be fixed by adding `sass` and `style` to the `resolve.conditions` in the Vite config.

We can support this out of the box by adding it to the plugin, where the config will get merged into the provided config.

```js
import { defineConfig } from 'vite';
import angular from '@analogjs/vite-plugin-angular';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    plugins: [
      angular({
        inlineStylesExtension: 'scss',
      }),
    ],
    resolve: {
      conditions: ['sass', 'style'], // <-- add to vite plugin
      mainFields: ['module'],
    },
  };
});
```

Reference https://github.com/yharaskrik/analog-nx-15/commit/c76f4d7b91f0260f8f7630d41655ad033f1faf4f#diff-28948f0a986cd471c15c0d8c8d3a3ae39a1b7f8b054af7deb4032b01823dd42e

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by miluoshi** [comment]
Maybe this fix is related? https://github.com/angular/angular-cli/commit/0662a2e9eb116915718d512876bdacab929a6ed9
