### ISSUE TITLE
Cant stop ng serve

### ISSUE THREAD

**Issue by web-dave** [analogjs/analog#1120]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/github/web-dave/analog-project

### Which area/package is the issue in?

create-analog

### Description

I created the project.
Played with analog js (wich is nice btw) but cant stop ng serve

### Please provide the exception or error you saw

```true
cli doen not stop running
```

### Other information

All my Angular v18 projects work fine

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by dalenguyen** [comment]
+1

**Comment by brandonroberts** [comment]
I've noticed this also. Its something to do with the wrapper around the vite builder. Pressing CTRL+C twice stops it.

**Comment by web-dave** [comment]
ctrl+C twice
Doesn't work for me.

even q does not work.

**Comment by gultyayev** [comment]
I wonder if we could just add a `process.on('SIGINT')` and exit the process manually.

**Comment by brandonroberts** [comment]
This could be due to us wrapping the Nx executors for supporting `ng` commands. Usually ctrl+c twice works across environments.
