### ISSUE TITLE
nx migrate not working

### ISSUE THREAD

**Issue by WolfSoko** [analogjs/analog#1123]
### Please provide the environment you discovered this bug in.

windows nx 19.1.0

### Which area/package is the issue in?

create-analog

### Description

Migration fails. 

nx migrate @analogjs/platform@latest fails because @analogjs/trpc is not found in a aligned version. 

The latest version of @analogjs/trpc is 0.2.45 or 1.0.0.beta-5

### Please provide the exception or error you saw

```true
Unable to fetch migrations for @analogjs/trpc@1.4.0: Command failed: npm install @analogjs/trpc@1.4.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @analogjs/trpc@1.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @WolfSoko. We need to remove it from the `packageGroup` in the `package.json` for each one of the packages.

**Comment by WolfSoko** [comment]
PR Created #1134
