### ISSUE TITLE
`@analogjs/vite-plugin-angular/setup-vitest` pull zone.js 

### ISSUE THREAD

**Issue by JeanMeche** [analogjs/analog#1140]
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

I wanted to test zoneless + vitest with this small demo written by @yjaaidi but `@analogjs/vite-plugin-angular/setup-vitest` pull `zone.js` without any opt-out possibility. 

https://stackblitz.com/edit/angular-vitest-starter-v18-ryiakv?file=vite.config.ts,src%2Ftest-setup.ts

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
If you don't need `zone.js`, just don't include the import in the `src/test-setup.ts` as everything there is related to it.

**Comment by brandonroberts** [comment]
In the `@analogjs/vitest-angular` package, its renamed it to `@analogjs/vitest-angular/setup-zone`, so its more clear that you don't need it if you aren't using `zone.js`

**Comment by JeanMeche** [comment]
Makes perfect sense, thank you for the input.

**Comment by yjaaidi** [comment]
I just updated the Stackblitz to 18.0.1 and commented out the import to avoid the warning and to let people opt-in to zonejs.

**Comment by yjaaidi** [comment]
That would be amazing!
I just made it zoneful: https://stackblitz.com/edit/angular-vitest-starter-v18
and moved the zoneless version here: https://stackblitz.com/edit/angular-vitest-starter-v18-zoneless
I'll be maintaining the templates so please let me know if I miss an update 😉

**Comment by viceice** [comment]
> In the `@analogjs/vitest-angular` package, its renamed to `@analogjs/vitest-angular/setup-zone`, so its more clear that you don't need it if you aren't using `zone.js`

what about the custom snapshot serializer? Can that be exported separately?

https://github.com/analogjs/analog/blob/beta/packages/vite-plugin-angular/setup-vitest.ts shjould probably also be renamed?

**Comment by brandonroberts** [comment]
@viceice yes, we can export that separately. 

I don't think we should rename it. The `@analogjs/vitest-angular` package is where new changes should live. We'll deprecate that import at some point.

**Comment by viceice** [comment]
> @viceice yes, we can export that separately. 
> 
> I don't think we should rename it. The `@analogjs/vitest-angular` package is where new changes should live. We'll deprecate that import at some point.

is `@analogjs/vitest-angular` a drop-in replacement for the old vite Plugin? I use it in my `vitest.config.js`

**Comment by viceice** [comment]
> Yes. Its a drop-in replacement with no extra dependencies.
> 
> ```sh
> npm i @analogjs/vitest-angular --save-dev
> ```
> 
> `@analogjs/vite-plugin-angular/setup-vitest` -> `@analogjs/vitest-angular/setup-zone`
> `@analogjs/platform:vitest` -> `@analogjs/vitest-angular:test`
> 
> You still need `@analogjs/vite-plugin-angular` in the `plugins` for Angular compilation support

ok, I'll execute vitest directly (not via nx) for our full monorepo because it's easier to handle code coverage and local/ CI testing.
