### ISSUE TITLE
[FEAT]: Add Angular v15 application to template applications

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#116]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Add angular-v15 template application when using `yarn create analog`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by dalenguyen** [comment]
I can help with this one :D

**Comment by brandonroberts** [comment]
Sure

**Comment by dalenguyen** [comment]
@brandonroberts added in #158
