### ISSUE TITLE
Module import only working with relative path, path alias or project root path not working 

### ISSUE THREAD

**Issue by hungtcs** [analogjs/analog#1162]
### Please provide the environment you discovered this bug in.

1. example import module from project root: `src/some-file`
    https://stackblitz.com/edit/github-i2s3yy?file=src%2Fserver%2Froutes%2Fv1%2Fhello.ts

2. example import module with path alias: `~/some-file`
    https://stackblitz.com/edit/github-i2s3yy-bkhce6?file=src%2Fserver%2Froutes%2Fv1%2Fhello.ts&preset=node

### Which area/package is the issue in?

Don't know / other

### Description

Create a file `some-file.ts` in the `src` directory, and import this file in `src/server/routes/v1/hello.ts`.

If import this file using `import { message } from 'src/some-file'` then get the error  `Cannot find module src/some-file imported from ...`

If import this file using `import { message } from '~/some-file'` and update `tsconfig.json` add path alias `"~/*": ["./src/*"]`, then get the error `no such file or directory, open '/home/projects/github-i2s3yy-bkhce6/src/server/some-file'`,  Note that the path is wrong, it has an extra `server` segment.

### Please provide the exception or error you saw

```
Error: Cannot find module src/some-file imported from 
```

```
ver/routes/v1/hello.ts): ENOENT: no such file or directory, open '/home/projects/github-i2s3yy-bkhce6/src/server/some-file'
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by hungtcs** [comment]
I finally succeeded in importing the module using path alias (import from project root is stil not working), here is my configuration information.

The key is that you need to configure it separately for dev and build modes, both are indispensable.


```ts
/// <reference types="vitest" />

import analog from "@analogjs/platform";
import { typescriptPaths } from "rollup-plugin-typescript-paths";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig(({ mode }) => {
  const debug = mode === "development";

  return {
    build: {
      target: ["es2020"],
    },
    resolve: {
      mainFields: ["module"],
    },
    plugins: [
      analog({
        vite: {
          inlineStylesExtension: "scss",
        },
        nitro: {
          debug: debug,
          esbuild: {
            // build 的时候生效
            options: {
              target: "es2020",
              tsconfigRaw: {
                compilerOptions: {
                  experimentalDecorators: true,
                },
              },
            },
          },
          rollupConfig: {
            plugins: [
              // only working with build mode, preserveExtensions must be true.
              typescriptPaths({ preserveExtensions: true }),
            ],
          },
          errorHandler: "~/error-handler",
        },
        apiPrefix: "api",
      }),
      // only working with dev mode
      tsconfigPaths(),
    ],
    test: {
      globals: true,
      environment: "jsdom",
      setupFiles: ["src/test-setup.ts"],
      include: ["**/*.spec.ts"],
      reporters: ["default"],
    },
    define: {
      "import.meta.vitest": debug,
    },
  };
});
```

But I think can not import modules through projects root is still a bug, but if you don't think so, please turn this issues off. 

Thank you for all you do.

**Comment by brandonroberts** [comment]
For client side code you can set up an alias to import from the root

In the vite config

```ts
resolve: {
  alias: {
    'src': `${__dirname}/src`
  }
}
```

You can also set up aliases. in the `nitro` object the same way

```ts
nitro: {
  alias: {
    'src': `${__dirname}/src`
  }
}
```

We could look at having an alias, such as `~/` included by default.

**Comment by hungtcs** [comment]
Thanks @brandonroberts , this is the right solution.
