### ISSUE TITLE
Analog not working with Create Cloudflare CLI

### ISSUE THREAD

**Issue by petebacondarwin** [analogjs/analog#1163]
### Please provide the environment you discovered this bug in.

Node.js

### Which area/package is the issue in?

create-analog

### Description

Our C3 e2e tests for the Analog framework are failing in CI, so we have marked it as quarantined for now.

### Please provide the exception or error you saw

```true
See the logs here - https://github.com/cloudflare/workers-sdk/pull/5987
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @petebacondarwin. 

This should be resolved by using version Analog `1.5.0` and the `latest` template. I'll take a look

**Comment by petebacondarwin** [comment]
We have a PR to bump to 1.5.0 here: https://github.com/cloudflare/workers-sdk/pull/6044
It was failing on bun and pnpm - rerunning.

**Comment by brandonroberts** [comment]
This should be resolved by using the latest release and using `latest` option for the `--template`

```sh
pnpm create analog@latest analog-cf-app --template latest
```
