### ISSUE TITLE
Event replay js-actions aren't working

### ISSUE THREAD

**Issue by osnoser1** [analogjs/analog#1165]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/github-zc67zw

### Which area/package is the issue in?

Don't know / other

### Description

In build time, Angular CLI is using this class https://github.com/angular/angular-cli/blob/main/packages/angular/build/src/utils/index-file/index-html-generator.ts#L82 inject a script (maybe other not related interesting things) to enable the event-replay actions, specifically here https://github.com/angular/angular-cli/blob/main/packages/angular/build/src/utils/index-file/add-event-dispatch-contract.ts#L14; without that script in runtime I get that exception.

As a workaround, I put in my HTML the js script:
<img width="1004" alt="image" src="https://github.com/analogjs/analog/assets/1179744/5fab45af-bd05-48f7-958f-0bff60af67fd">

### Please provide the exception or error you saw

```true
chunk-T5GBXR7Y.js?v=db991a5a:22766 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading '_ejsa')
    at getJsactionData (chunk-T5GBXR7Y.js?v=db991a5a:22766:20)
    at chunk-T5GBXR7Y.js?v=db991a5a:22807:41
﻿
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @osnoser1. What's your proposed solution? We could inject the same thing into the `index.html` file using a Vite plugin if SSR is enabled.

**Comment by osnoser1** [comment]
> https://github.com/angular/angular-cli/blob/main/packages/angular/build/src/utils/index-file/index-html-generator.ts#L82

Well, I didn't have a solution in mind when I posted the problem 😅, but yes, in theory, we have to read the `@angular/core/event-dispatch-contract.min.js` and inject it in a script tag; this has to be done with SSR or SSG too
