### ISSUE TITLE
Unit tests launch with ng test always succeed

### ISSUE THREAD

**Issue by ArnoldM** [analogjs/analog#1172]
### Please provide the environment you discovered this bug in.

Create a new analogJs project and run "ng test"

### Which area/package is the issue in?

vitest-angular

### Description

The test `should create the app` in `app.component.spec.ts` succeeds with `expect(app).toBeTruthy()` and `expect(app).not.toBeTruthy()`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

**Comment by brandonroberts** [comment]
The `@analogjs/vitest-angular` package is the default and recommended package now. The issue should be fixed in the old package, but the new one should be used going forward.
