### ISSUE TITLE
HMR doesn't work properly when a `base` property is set in the Vite config

### ISSUE THREAD

**Issue by Poiuytrezay1** [analogjs/analog#1181]
### Please provide the environment you discovered this bug in.

I couldn't create a stackblitz, but here is an easy way to reproduce:

- Run `npx create-nx-workspace` (Choose Angular / Integrated monorepo / esbuild / sass / no ssr / no e2e / skip)
- Run `npm install` && `npm install -D @analogjs/platform`
- Run `npx nx generate @analogjs/platform:init --project [your-project-name]`
- In "apps/[your-project-name]/vite.config.ts", set `base: '/example'`
- In "apps/[your-project-name]/src/index.html" set `<base href="/example" />`
- Serve your project "nx serve [your-project-name]
- Open the app in a browser, then try modifying "apps/[your-project-name]/src/app/app.component.html", the page won't refresh
- BONUS: saving the component.ts will actually refresh the page

### Which area/package is the issue in?

vite-plugin-angular

### Description

When setting a `base` URL in the vite config and index.html file, HMR stops working properly for HTML templates in separate files. This is annoying, as it forces us to restart the app every time.

### Other information

When handling hot updates, the HTML file's `importers` field is missing the corresponding component.ts (thus, component.ts is not invalidated when modifying the HTML).

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Try with the latest release, and reopen if this is still an issue
