### ISSUE TITLE
Gutter icons in VS Code are displayed in the wrong line

### ISSUE THREAD

**Issue by kevinkasper** [analogjs/analog#1211]
### Please provide the environment you discovered this bug in.

Clone minimal reproducible example:

https://github.com/kevinkasper/vitest-vscode-gutter-icons-mre

1. `yarn install`
2. Open `src/app/app.component.spec.ts file`
3. Run all tests within the Test Explorer

### Which area/package is the issue in?

vite-plugin-angular

### Description

The gutter icons in VS Code are displayed in the wrong line if the `@analogjs/vite-plugin-angular` plugin is used.

Below is an example with activated plugin in the `vite.config.ts` and empty lines in the spec file:

![image](https://github.com/user-attachments/assets/6e92f5c1-470b-4ecb-acf0-9757148fe070)

Below is an example without activated plugin in the `vite.config.ts` and empty lines in the spec file:

![image](https://github.com/user-attachments/assets/1b8b0f54-f57c-4fbe-8158-f456b95561b3)

In the second screenshot, the tests fail, but the gutter icons are in the right place.

---

This problem has already been reported in the [vitest-dev/vscode](https://github.com/vitest-dev/vscode) repository. In the following issue it was confirmed that it is a problem with `@analogjs/vite-plugin-angular`:

https://github.com/vitest-dev/vscode/issues/400

Many thanks in advance!

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by Kendox-STA** [comment]
Same issue here, which prevents us from evaluating Vitest. Would be great to get that resolved.

**Comment by rafagsiqueira** [comment]
Here too. The gutter icons move all over the place when adding comments to tests.

**Comment by rafagsiqueira** [comment]
@brandonroberts has this fix made it to one of the releases?

**Comment by rafagsiqueira** [comment]
Any news on this? It really sends both our breakpoints and our gutter icons all over the place. Makes it nearly impossible to use the vitest extension in vscode nor debugging tests on the IDE.

**Comment by brandonroberts** [comment]
Still looking into this one. The sourcemaps are fine when served in the browser, so trying to see what the difference is when using Vitest

**Comment by rafagsiqueira** [comment]
@brandonroberts thank you very much! Forgive my ignorance, but what exactly does the vite-plugin-angular do?

**Comment by brandonroberts** [comment]
@rafagsiqueira no problem. The plugin does the Angular compilation step so your external styles,  templates, and constructor DI works during testing.

If you use all inline styles and templates, and the inject function for DI, then you don't need the plugin. I have found this to be rare though.

**Comment by brandonroberts** [comment]
Sourcemaps fix for VSCode/IDEs has landed in the `1.9.0-beta.12` release.  I've done some testing but please validate the fix on your end also
