### ISSUE TITLE
attributes and content undefined for .agx files when using `injectContent('slug')`

### ISSUE THREAD

**Issue by hofmannjan1** [analogjs/analog#1213]
### Please provide the environment you discovered this bug in.

Reproducible steps:

- `npm create analog@1.6.1` (Blog)
- Create a file `example-post-2.agx` in the `src/content` folder:

```
---
title: My Second Post
slug: 2024-07-18-my-second-post
description: My Second Post Description
coverImage: https://images.unsplash.com/photo-1493612276216-ee3925520721?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80
---

<template lang="md">

# Dynamic Example Post

Hello, world!

</template>
```

- Run `npm i && npm run dev`

### Which area/package is the issue in?

content

### Description

When using `injectContent` with the slug, the attributes and content of .agx files are undefined. In the reproducible example above, the second post is included in the posts list on http://localhost:PORT/blog but if I try to access http://localhost:PORT/blog/2024-07-18-my-second-post, nothing is rendered.

In the `pages/blog/[slug].page.ts` I added the following:
```ts
readonly post$ = injectContent<PostAttributes>('slug').pipe(
    tap((x) => console.log(x))
  );
```

The console output is:

![image](https://github.com/user-attachments/assets/0c0e65d0-7fee-489b-accb-b2b20b5641af)

There is almost no resources on how to use .agx content files but from what I understand it should work exactly like .md content files without the need to adjust the `injectContent` or anything else in the code.

The behavior is the same regardless of the .agx file's content.

### Please provide the exception or error you saw

```true
core.mjs:6467 ERROR 
TypeError: Cannot read properties of undefined (reading 'coverImage')
    at HomeComponent_Conditional_0_Template ([slug].page.ts:15:32)
    at executeTemplate (core.mjs:11264:5)
    at refreshView (core.mjs:12817:7)
    at detectChangesInView (core.mjs:13025:5)
    at detectChangesInViewIfAttached (core.mjs:12987:3)
    at detectChangesInEmbeddedViews (core.mjs:12947:7)
    at refreshView (core.mjs:12844:5)
    at detectChangesInView (core.mjs:13025:5)
    at detectChangesInViewIfAttached (core.mjs:12987:3)
    at detectChangesInComponent (core.mjs:12976:3)
```

### Other information

The only resources about .agx files I found:
- [What happened to Analog's experimental ".ng" format?](https://www.youtube.com/watch?v=15vHXCMhl6U) (Joshua's video)
- https://github.com/analogjs/analog/pull/1012 (the original PR)
- https://github.com/analogjs/analog/tree/61b1ea63fffc6eb6510cb1006922a92af9f0f3bb/apps/ng-app (an example app which has a single .agx file but uses .analog format for all pages and components which does not apply to Analog's default blog app)

That's about it, there's very little information about this feature and the official docs do not mention it at all.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Did you enable support for `.analog/.agx` files in the analog plugin in the vite.config.ts?

```ts
analog({
  vite: {
    experimental: {
      supportAnalogFormat: true
    }
  }
});
```

**Comment by Johanneslueke** [comment]
> Did you enable support for `.analog/.agx` files in the analog plugin in the vite.config.ts?
> 
> analog({
>   vite: {
>     experimental: {
>       supportAnalogFormat: true
>     }
>   }
> });
> 
> https://analogjs.org/docs/experimental/sfc#usage

the link is not working anymore and i cannot find anything in the docu anymore. is this feature deprecated by any chance or am i just blind=

**Comment by brandonroberts** [comment]
https://github.com/analogjs/analog/issues/1837
