### ISSUE TITLE
Outdated documentation page for create analog

### ISSUE THREAD

**Issue by geromegrignon** [analogjs/analog#1235]
### Please provide the environment you discovered this bug in.

Released documentation: https://analogjs.org/docs/packages/create-analog/overview#using-with-tailwind

### Which area/package is the issue in?

Docs

### Description

This page is outdated: https://analogjs.org/docs/packages/create-analog/overview#using-with-tailwind
It can only be found by using the search feature, i can't find it indexed in the navigation sidebar.

Is it meant to be updated or removed? The tailwind part is not required anymore as included as a prompt with create analog.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by geromegrignon** [comment]
@brandonroberts do you want it either:

- to be removed
- to be updated (with a proper nav entry)?

**Comment by brandonroberts** [comment]
It can be removed if not needed

**Comment by geromegrignon** [comment]
> It can be removed if not needed

It could become a **CLI reference** but as all options are prompt and template options can evolve, do you want to maintain such a page?

**Comment by brandonroberts** [comment]
I think updating the `create-analog` options is good for now along with removing the Tailwind section.
