### ISSUE TITLE
Support vitest version 2

### ISSUE THREAD

**Issue by s0h311** [analogjs/analog#1249]
### Which scope/s are relevant/related to the feature request?

vitest-angular

### Information

I'm currently using `@analogjs/vitest-angular@1.6.4` with `vitest@2.0.4` override in a mid size project with 106 tests and it seems to work fine.

Is there anything holding us back from setting the peer dependency to `^1.3.1 || ^2.0.0` ?

It would be nice to not need the override and supporting the latest `vitest` major version.

### Describe any alternatives/workarounds you're currently using

` "overrides": {
        "@analogjs/vitest-angular": {
            "vitest": "^2.0.0"
        }
    }` in `package.json`

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
I don't see a reason why we can't support that version also

**Comment by s0h311** [comment]
@brandonroberts the realease step has failed. Did I forgot to bump up the version in `package.json`?

**Comment by brandonroberts** [comment]
No, you didn't. Its supposed to be versioned through CI but something's going on there. Will get it sorted and a fix release out soon.

**Comment by brandonroberts** [comment]
`1.7.1-beta.1` is on `npm` with the fix

**Comment by s0h311** [comment]
Thank you very much
