### ISSUE TITLE
Potential bug - preprocessCSS()

### ISSUE THREAD

**Issue by slashby** [analogjs/analog#1262]
### Please provide the environment you discovered this bug in.

-

### Which area/package is the issue in?

vite-plugin-angular

### Description

vite-plugin-angular uses preprocessCSS() Vite function since v. 1.6.4. The function uses config.createResolver under the hood, but Vite adds createResolver when config is resolved and provides configResolved hook https://vitejs.dev/guide/api-plugin#configresolved for plugins.

Not resolved config is stored by vite-plugin-angular plugin to userConfig variable and then it's passed to preprocessCSS(). As result createResolver is not available and it is not possible to run style pre-processor (in my case it is for SASS).

Does it make sense to add the following configResolve hook implementation to the plugin?

`configResolved(resolvedConfig) {
  userConfig = resolvedConfig
}`

### Please provide the exception or error you saw

```true
Vite 5.3.5:

file:///node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:36585
      return sassResolve || (sassResolve = config.createResolver({
                                                  ^

TypeError: config.createResolver is not a function
    at get sass (file:///node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:36585:51)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
@slashby Yep, that makes sense
