### ISSUE TITLE
Router doesn't work in Analog v17

### ISSUE THREAD

**Issue by d-borys** [analogjs/analog#1263]
### Please provide the environment you discovered this bug in.

Hey, I started a new app today step by step with documentation and I'm getting a blank welcome page. 

Tried to add extra routes, but that didn't work as well. 

![obraz](https://github.com/user-attachments/assets/cede0c71-0324-410e-b42f-34f8e3ba20ac)

### Which area/package is the issue in?

create-analog

### Description

Steps

1. npm create analog@latest
2. npm install
3. npm start

Getting blank page under http://localhost:5173/

![obraz](https://github.com/user-attachments/assets/ae5e241e-035f-4efc-909e-eecb089139ff)

Adding extra routes e.g pages/(home)/home.page.ts and then trying to access that under /home throws error as well. 

### Other information

Package.json

```json
{
  "name": "app",
  "version": "0.0.0",
  "type": "module",
  "engines": {
    "node": ">=18.19.1"
  },
  "scripts": {
    "ng": "ng",
    "dev": "ng serve",
    "start": "npm run dev",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@analogjs/content": "^1.7.0",
    "@analogjs/router": "^1.7.0",
    "@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/platform-server": "^18.0.0",
    "@angular/router": "^18.0.0",
    "front-matter": "^4.0.2",
    "marked": "^5.0.2",
    "marked-gfm-heading-id": "^3.1.0",
    "marked-highlight": "^2.0.1",
    "marked-mangle": "^1.1.7",
    "prismjs": "^1.29.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@analogjs/platform": "^1.7.0",
    "@analogjs/vite-plugin-angular": "^1.7.0",
    "@analogjs/vitest-angular": "^1.7.0",
    "@angular-devkit/build-angular": "^18.0.0",
    "@angular/cli": "^18.0.0",
    "@angular/compiler-cli": "^18.0.0",
    "jsdom": "^22.0.0",
    "typescript": "~5.4.2",
    "vite": "^5.0.0",
    "vite-tsconfig-paths": "^4.2.0",
    "vitest": "^1.3.1",
    "tailwindcss": "^3.3.1",
    "postcss": "^8.4.21",
    "autoprefixer": "^10.4.14"
  }
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @d-borys. If you're on Windows, I believe this is fixed in the latest beta release.

```sh
npm create analog@beta app
```

Try it out and let us know if it works. The fix release will go out today.

**Comment by d-borys** [comment]
Yup, I'm on windows. 

Installing latest beta helpef. Thanks!
