### ISSUE TITLE
Simple inclusion of markdown content files from markdown page files

### ISSUE THREAD

**Issue by filloax** [analogjs/analog#1285]
### Which scope/s are relevant/related to the feature request?

content

### Information

Is it possible to simply include a markdown files from another markdown file? Similar to the {% include %} directive in Jekyll. If not, would that feature be feasible to add?

### Describe any alternatives/workarounds you're currently using

Currently none

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
No, that's not currently supported in `marked` which is what we use for compiling markdown. I don't see us adding this in the near future.
