### ISSUE TITLE
Impossible to use inject inside RouteMeta or CanActivateFn

### ISSUE THREAD

**Issue by mparpaillon** [analogjs/analog#1287]
### Please provide the environment you discovered this bug in.

Analog 1.7.2, angular 18.1.3

### Which area/package is the issue in?

Don't know / other

### Description

Hi, 
I'm trying to create a route guard but can't seem to use inject() inside it.

```ts
export const AuthGuard: CanActivateFn = async () => {
  const session = await inject(SupabaseService).getSession();

  if (!session.data.session) {
    inject(Router).navigate(["/auth"]);
    return false;
  }

  return true;
};

export const routeMeta: RouteMeta = {
  canActivate: [AuthGuard],
};

@Component({
  standalone: true,
  imports: [
    RouterOutlet,
    HeaderComponent,
  ],
  selector: "mkp-layout",
  template: `
    <div class="bg-white h-full flex flex-col">
      <mkp-header />
      <router-outlet />
    </div>
  `,
})
export default class LayoutComponent {
}
```

### Please provide the exception or error you saw

```true
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
```

### Other information

It seemed possible in Angular docs => https://angular.dev/guide/di/dependency-injection-context#stack-frame-in-context

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by mparpaillon** [comment]
Ok Apparently it's only the inject(Router) that causes the error.

**Comment by brandonroberts** [comment]
Took a quick look and it has something to do with the `async/await`. Changing the order of injection works for some reason.

```ts
export const AuthGuard: CanActivateFn = async () => {
  const router = inject(Router);
  const session = await inject(SupabaseService).getSession();

  if (!session.data.session) {
    router.navigate(["/auth"]);
    return false;
  }

  return true;
};

export const routeMeta: RouteMeta = {
  canActivate: [AuthGuard],
};

@Component({
  standalone: true,
  imports: [
    RouterOutlet,
    HeaderComponent,
  ],
  selector: "mkp-layout",
  template: `
    <div class="bg-white h-full flex flex-col">
      <mkp-header />
      <router-outlet />
    </div>
  `,
})
export default class LayoutComponent {
}
```

Need to look more into why.

**Comment by brandonroberts** [comment]
For reference, this also fails within a regular Angular application, so it's not Analog-specific. If you open the devtools and click on "Test" it throws the error.

https://stackblitz.com/edit/stackblitz-starters-uonwng?file=src%2Fmain.ts

**Comment by brandonroberts** [comment]
This behavior is working as intended, as explained by @SanderElias. 

Anything after the `await` gets moved into the next browser macrotask, which would be after instantiation. The injection context is only available during instantiation, which is why putting all the inject(s) above the await works.
