### ISSUE TITLE
`utils.inherits is not a function` when importing some packages inside Astro integration

### ISSUE THREAD

**Issue by filloax** [analogjs/analog#1291]
### Please provide the environment you discovered this bug in.

I am using AnalogJS with Astro, to use an Angular component in my website.

### Which area/package is the issue in?

astro-angular

### Description

I am making a part of my website to list RPG sessions, and am using a shared utility file for related functionalities. This utility file imports the *reading-time* module (already used in the Astro template I started for):

```ts
import readingTime from "reading-time";
```

It works fine when importing functions from the shared utility file in Astro components, but when I do it inside my angular component included with astro-angular it gives the related error in the console (not the terminal log) and stops hydration. I suspect it isn't related to the specific package due to the general nature of the error.

Any idea why this might be happening?

### Please provide the exception or error you saw

```true
[astro-island] Error hydrating /src/components/rpg/sessionsIndex/sessionsIndex.component.ts TypeError: util.inherits is not a function
    js stream.js:42
    __require chunk-JVWSFFO4.js:5
    js index.js:2
    __require chunk-JVWSFFO4.js:5
    <anonymous> reading-time.js:152
sessioni:884:5357
    start http://localhost:4321/rpg/star/sessioni:884
    childrenConnectedCallback http://localhost:4321/rpg/star/sessioni:884
    e http://localhost:4321/rpg/star/sessioni:884
    (Async: EventListener.handleEvent)
    connectedCallback http://localhost:4321/rpg/star/sessioni:884
    (Async: LifecycleConnectedCallback)
    <anonymous> http://localhost:4321/rpg/star/sessioni:884
    <anonymous> http://localhost:4321/rpg/star/sessioni:884
```
```


### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
I think I've run into this before with `reading-time` also. You need to do a couple of things:

Install the `util` package

https://github.com/brandonroberts/blog/blob/main/package.json#L40

Add config to the `vite.config.ts` for `reading-time`

https://github.com/brandonroberts/blog/blob/main/vite.config.ts#L15
https://github.com/brandonroberts/blog/blob/main/vite.config.ts#L42
