### ISSUE TITLE
Update to Nx 19.5.3 and beyond

### ISSUE THREAD

**Issue by benpsnyder** [analogjs/analog#1349]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

First upgrade to Nx 19.5.3 ... but the PR will fail deployment to Vercel due to 
[fix(core): prevent post install failures when socket path too long](https://github.com/nrwl/nx/pull/27366)

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Nx is on v20
