### ISSUE TITLE
Improve Error Stack Trace Clarity in Development Mode with AnalogJS

### ISSUE THREAD

**Issue by ismaelguerrib** [analogjs/analog#1368]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/github-csjgq2?file=project.json

### Which area/package is the issue in?

create-analog

### Description

I am encountering an issue in an AnalogJS app parts of an Nx monorepo where error stack traces in development mode are not clear or helpful for identifying the source of the problem in my application. Specifically, when I encounter an error, such as a NullInjectorError in Angular, the error stack does not provide enough detailed information to easily track down the problematic component or service in my code. It feels more like a production-level error message than a development one.

### Please provide the exception or error you saw

```true
Angular is running in development mode.
NullInjectorError: NullInjectorError: No provider for [object Object]!
    at NullInjector.get (chunk-35VRJOYW.js?v=f5ef3704:2454:21)
    at R3Injector.get (chunk-35VRJOYW.js?v=f5ef3704:3349:27)
    at injectInjectorOnly (chunk-35VRJOYW.js?v=f5ef3704:2187:36)
    at ɵɵinject (chunk-35VRJOYW.js?v=f5ef3704:2193:59)
    at inject (chunk-35VRJOYW.js?v=f5ef3704:2202:10)
    at RedirectGuard ((redirect).page.ts:9:26)
    at @angular_router.js?v=f5ef3704:2483:134
    at runInInjectionContext (chunk-35VRJOYW.js?v=f5ef3704:3592:12)
    at @angular_router.js?v=f5ef3704:2483:89
```

### Other information

Expected Behavior:

In development mode, I expect the error stack trace to provide more context, pointing to the actual files and lines in my TypeScript codebase rather than minified JavaScript files (chunk-35VRJOYW.js). This would greatly improve the debugging experience.

Actual Behavior:

The error stack trace references compiled or bundled code, which makes it difficult to locate the root cause of the error, especially when working with Angular’s dependency injection errors like NullInjectorError. It looks like the kind of error you’d expect in production rather than development. 

What I’ve Tried:

	•	Enabled Source Maps: I have ensured that sourcemap: true is set in the Vite configuration in development mode.
	•	Checked Angular DevTools: I tried using Angular DevTools to inspect the app, but the error traces still point to compiled JavaScript files.
	•	Disabled SSR: I disabled SSR, but this didn’t affect the error message clarity.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Please provide a reproduction with the latest version.
