### ISSUE TITLE
Repo: Update Analog SFC app to use .ag extension instead of .analog extension by default

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#1371]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

We've added support for the `.ag` extension when using the Analog SFC. This would update the `ng-app` in the repo to use the new extension instead.

We're updating the Analog Language Tools and IDEA Plugin to support the extension also.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by nickytonline** [comment]
Easing my way into this repo. I'd like to tackle this one @brandonroberts.

**Comment by brandonroberts** [comment]
Nice @nickytonline
