### ISSUE TITLE
outputFromObservable does not emit from SFC component

### ISSUE THREAD

**Issue by nivekcode** [analogjs/analog#1381]
### Please provide the environment you discovered this bug in.

Analog: 1.8.2
Angular: 18.2.7

### Which area/package is the issue in?

vite-plugin-angular

### Description

When we use SFC and try to emit an output using the `outputFromObservable` the output is not emitting any event. Normal outputs emit correctly in SFC. If we use `outputFromObservable` outside a SFC everything works as expected.

### Other information

I made a reproduction example here: https://github.com/kreuzerk/output-test

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by nartc** [comment]
@nivekcode can you give latest beta a try?
