### ISSUE TITLE
npm create analog@latest

### ISSUE THREAD

**Issue by leblancmeneses** [analogjs/analog#1382]
### Please provide the environment you discovered this bug in.

node 20.11.1, Apple M1 Max

### Which area/package is the issue in?

create-analog

### Description

option selection: "What would you like to start?"
"Full-stack Application" correctly generates: ^1.8.2
 "Minimal" generates new projects with ^1.7.3-beta.1

### Please provide the exception or error you saw

```true
expected "Minimal" to use latest analogjs.
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Good catch. It can be fixed by adding the package.json in these two arrays

https://github.com/analogjs/analog/blob/beta/release.config.cjs#L7
https://github.com/analogjs/analog/blob/beta/release.config.cjs#L131

**Comment by brandonroberts** [comment]
Fixed in https://github.com/analogjs/analog/commit/0e030cca96f60b42d0c6feaf5c997cc54ce0a5da
