### ISSUE TITLE
chore: add perf changes from esbuild browser plugin

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#14]
Adds checks to see if babel transform is needed

https://github.com/angular/angular-cli/pull/23682

**Comment by pjlamb12** [comment]
I'm unsure where the change that starts [on line 371](https://github.com/angular/angular-cli/pull/23682/files#diff-309812edd0ff24c480525d73b2e4b7a0d82b91d2a689720f2e77395f7958bea7R371) of that PR should be added in Analog. My guess is in the object whose name is `name: '@analogjs/vite-plugin-angular-optimizer'` in the `angular-vite-plugin.ts` file, inside the transform method?

**Comment by pjlamb12** [comment]
[These are the changes I've begun making](https://github.com/pjlamb12/analog/commit/80ca785f56164e1dfd15ec99ebbb53e808e342f4). I haven't worked with esbuild (or anything similar) before so I know this may need to change.

**Comment by brandonroberts** [comment]
@pjlamb12 Thanks! Looking on track so far. You don't need to add the `advancedOptimizations` flag. Just use the `isProd` boolean that already exists inside the plugin. These changes would be added to both the `@analogjs/vite-plugin-angular-optimizer` and `@analogjs/vite-plugin-angular` transform functions.

Would be cleaner to separate the plugins into different files, but that can come as a separate effort.
