### ISSUE TITLE
Netlify function with _redirect file

### ISSUE THREAD

**Issue by mparpaillon** [analogjs/analog#1403]
### Please provide the environment you discovered this bug in.

Analog 1.7.2
Nx 19.8.3

### Which area/package is the issue in?

Don't know / other

### Description

Hi, since I've added a _redirects file for my analog app to behave like a SPA, the API routes don't work anymore. They're returning a 404 page.

Here's the file
```
/*    /index.html   200
```

I read that the edge functions were resolved before the redirects but this is just a "function" not a "edge function" so I don't know. 

What am I missing?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
So you don't want to use SSR on any parts of the app, but just a traditional SPA + API routes?

**Comment by mparpaillon** [comment]
Currently SSR has been disabled because it was causing issues at the time (no zoneless support and some e2e issues too I think). So yeah currently it's only SPA + API routes.

**Comment by brandonroberts** [comment]
You have a couple of options:

Disable SSR with `analog({ ssr: true })` in the `vite.config.ts`, and remove the `_redirects` file, it still works as an SPA + API routes. It will hit the netlify function though when requesting full URLs.

If you want to use the `_redirects` file and just the deployed `index.html`, use the configuration below.

```
/api/* /.netlify/functions/server 200
/* /index.html 200
```

**Comment by mparpaillon** [comment]
Thanks Brandon,

SSR was already set to false and removing the _redirects file didn't change a thing. I was still getting a 404 when trying to call the API

So I tried the other solution with the redirect but now I'm getting `error decoding lambda response: error decoding lambda response: unexpected end of JSON input` 

Any idea what could be the issue?

**Comment by ajitzero** [comment]
> URL: [analog-spa.netlify.app](https://analog-spa.netlify.app/)

Doesn't seem to work:    
![image](https://github.com/user-attachments/assets/15729164-f36d-46fe-9d6c-417cf1935591)

**Comment by mparpaillon** [comment]
Thanks @brandonroberts I'll have a look and see what's different in my env

**Comment by brandonroberts** [comment]
> > URL: [analog-spa.netlify.app](https://analog-spa.netlify.app/)
> 
> Doesn't seem to work: ![image](https://private-user-images.githubusercontent.com/19947758/376785199-15729164-f36d-46fe-9d6c-417cf1935591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzE5ODksIm5iZiI6MTcyOTA3MTY4OSwicGF0aCI6Ii8xOTk0Nzc1OC8zNzY3ODUxOTktMTU3MjkxNjQtZjM2ZC00NmZlLTlkNmMtNDE3Y2YxOTM1NTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA5NDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NWE3MjA2NDI5MjkzZWJjZDJhZDMxZWEwNjZmMmFlZWNhOTViYTRkMzBmZWM2YjI0ZjZlZGM5YjE5YjE3ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3J_l493NdRyY_R8BXFj-pDaUcwuutJIF9ZoQDQSMdb8)

It should be https://analog-netlify-spa.netlify.app

**Comment by louiiuol** [comment]
Hello, I'm also creating an analog application with SPA and api routes, but inside a NX Monorepo.
@brandonroberts I've checked your repository, and tried to find the diffenerences but the configuration is perrty much the same.. Only thing i've noticed is in your dist/analog/server/ you have a node_modules folder and i don't ... not really sure why and if this is important.. Also my package.json contains a lot of deps whereas yours only get one, is that normal ? Can that be a lead ? 

In order to debug this mess, I've launched locally deployment with `netlify dev` command, SPA works just fine but when i get to http://../api/v1/hello (i've kept default exemple from analog generator) my server returns the following error: 
```md
◈ Loaded function server
◈ Rewrote URL to /.netlify/functions/server
Request from ::1: GET /.netlify/functions/server
[nitro] [uncaughtException] {
  errorMessage: 'e.default is not a function',
  errorType: 'TypeError',
  stackTrace: [
    'file:///Users/louiiuol/apps/optee/apps/marketplace/.netlify/functions-serve/server/___netlify-bootstrap.mjs:2:26751',
    'AsyncLocalStorage.run (node:async_hooks:338:14)',
    'file:///Users/louiiuol/apps/optee/apps/marketplace/.netlify/functions-serve/server/___netlify-bootstrap.mjs:2:26690',
    'Object.<anonymous> (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:88:46)',
    'step (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:67:23)',
    'Object.next (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:48:53)',
    '/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:42:71',
    'new Promise (<anonymous>)',
    '__awaiter (/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:38:12)',
    '/Users/louiiuol/.nvm/versions/node/v18.20.4/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/streaming.js:78:64'
  ]
}
Listening on http://[::]:3000
```

Many thanks for your help 🙏
