### ISSUE TITLE
Custom tsconfig for vite-plugin-angular breaks test detection

### ISSUE THREAD

**Issue by icecream-shark5** [analogjs/analog#1441]
### Please provide the environment you discovered this bug in.

OS: Ubuntu 24.04.1 LTS
Node: 22.9.0

Set up the app
```bash
npx create-nx-workspace analog-bug-report --preset=angular-monorepo --appName=analog-app --bundler=webpack --style=scss --ssr=false --e2eTestRunner=none --nxCloud=skip 
cd ./analog-bug-report/
npm i -D @analogjs/platform
npx nx generate @analogjs/platform:setup-vitest --project analog-app
```

Add plugin option in `apps/analog-app/vite.config.mts`
```diff
-    plugins: [angular(), nxViteTsPaths()],
+    plugins: [angular({ tsconfig: './tsconfig.spec.ts' }), nxViteTsPaths()],
```

Run
```bash
npx nx test analog-app
```

### Which area/package is the issue in?

vite-plugin-angular

### Description

I believe the issue is [here](https://github.com/analogjs/analog/blob/8d69254f4b3f65b6060c4610f9a3f16e792b2f1e/packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts#L168), where the option path is not resolved but the defaults are. Moving it inside the `resolve` fixes it for me.

```diff
-          options?.tsconfig ??
          resolve(
            config.root || '.',
+           options?.tsconfig ??
            (process.env['NODE_ENV'] === 'test'
              ? './tsconfig.spec.json'
              : './tsconfig.app.json')
          );
```

### Please provide the exception or error you saw

```true
RUN  v1.6.0 /home/andrew/Documents/analog-bug-report/apps/analog-app

 ❯ src/app/app.component.spec.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/app/app.component.spec.ts [ src/app/app.component.spec.ts ]
Error: No test suite found in file /home/andrew/Documents/analog-bug-report/apps/analog-app/src/app/app.component.spec.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  11:00:07
   Duration  1.77s (transform 1.07s, setup 1.01s, collect 35ms, tests 0ms, environment 286ms, prepare 408ms)


———————————————————————————————————————————————————————————————————————————————

 NX   Ran target test for project analog-app (3s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
This is not a bug per-say. If you provide the `tsconfig` property, you're expected to override the whole path

**Comment by icecream-shark5** [comment]
Got it, is this documented anywhere? It wasn't specified in `PluginOptions` and it's not obvious the path needs to be absolute for this case when the path for `setupFiles` is relative.

**Comment by charlesritchea** [comment]
Just wanted to add that in every other build tool I've used tsconfig: option is relative to the package root. Not saying it can't be absolute here, but it would be wise to call that out as it's definitely against expectations

**Comment by R-Bower** [comment]
> Just wanted to add that in every other build tool I've used tsconfig: option is relative to the package root. Not saying it can't be absolute here, but it would be wise to call that out as it's definitely against expectations

I second this.  Just ran into this exact issue and the problem was because of the tsconfig setting.

**Comment by brandonroberts** [comment]
This has been resolved already and works as intended in the latest release. If you use a relative  tsconfig path, it uses the configured root path. If you use an absolute path, it uses it as is.
