### ISSUE TITLE
vite-plugin-angular throws error after installing with yarn

### ISSUE THREAD

**Issue by joewIST** [analogjs/analog#1458]
### Please provide the environment you discovered this bug in.

@analogjs/vite-plugin-angular : 1.9.4

### Which area/package is the issue in?

vite-plugin-angular

### Description

I am using the vite-plugin-angular to get my unit tests to work. I have been getting errors such as "Expected to be running in 'ProxyZone', but it was not found." and decided to investigate the plugin to overcome these. Now the ProxyZone errors are gone but now there is an issue with "@angular/build/private".

### Please provide the exception or error you saw

```true
Cannot find module '@angular/build/private'
Require stack:
- C:\Users\joe.williams\Projects\Megatron\frontend\src\node_modules\@analogjs\vite-plugin-angular\src\lib\utils\devkit.js
Error: Cannot find module '@angular/build/private'
Require stack:
- C:\Users\joe.williams\Projects\Megatron\frontend\src\node_modules\@analogjs\vite-plugin-angular\src\lib\utils\devkit.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._resolveFilename (C:\Users\joe.williams\Projects\Megatron\frontend\src\node_modules\tsconfig-paths\lib\register.js:103:40)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at file:///C:/Users/joe.williams/Projects/Megatron/frontend/src/node_modules/@analogjs/vite-plugin-angular/src/lib/utils/devkit.js:37:87
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadConfigFromBundledFile (file:///C:/Users/joe.williams/Projects/Megatron/frontend/src/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66691:15)
    at async loadConfigFromFile (file:///C:/Users/joe.williams/Projects/Megatron/frontend/src/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66532:24)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by AlexAegis** [comment]
You likely have direct imports from vitest like this: `import { describe, it } from vitest;'

angular tests require patched test hooks (it, describe etc) and when importing them from vitest you get the raw, unpatched ones. You must only use the global, patched functions provided by analog

**Comment by joewIST** [comment]
Hi @AlexAegis thanks for your response. I have only just installed vitest in our project (we were previously using Jest) so there are no imports from vitest that could be causing this. This error seems to be more to do with accessing a directory that doesn't exist...

**Comment by brandonroberts** [comment]
@joewIST what package manager are you using? The `@analogjs/vite-plugin-angular` package has peer dependencies, including `@angular/build` that should be handled by most package managers, with `yarn` being an exception.

**Comment by joewIST** [comment]
Thanks @brandonroberts. That would explain it; we use Yarn. Is there a workaround for use with Yarn or is this just not supported yet? I couldn't see anything on the documentation but I may have missed something!

**Comment by mfig** [comment]
thanks guys, just had the same issue with new Angular app created using [@nx/angular:application](https://nx.dev/nx-api/angular/generators/application)

```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/vite/plugin plugin.
    - apps/ng-frontend/vite.config.mts: Cannot find module '@angular/build/private'
  Require stack:
  - C:\Users\User\Documents\Git\active-rpi\node_modules\@analogjs\vite-plugin-angular\src\lib\utils\devkit.js
      Error: Cannot find module '@angular/build/private'
      Require stack:
      - C:\Users\User\Documents\Git\active-rpi\node_modules\@analogjs\vite-plugin-angular\src\lib\utils\devkit.js
```
No more issues after applying missing dependencies from https://github.com/analogjs/analog/issues/1458#issuecomment-2501498555

**Comment by brandonroberts** [comment]
> Great! That works and I don't get the dependency error.
> 
> However, I'm now getting the "Error: No test suite found in file" error and I can't seem to find any consistent fix other than downgrade to an earlier version of vitest. Can you help?

Check your `tsconfig.spec.json` configuration and make sure it matches the one from the docs

https://analogjs.org/docs/features/testing/vitest#setup-for-running-tests-for-node

Also try setting the `tsconfig` in the plugin inside the `vite.config.mts`

```ts
// vite.config.mts
import angular from '@analogjs/vite-plugin-angular';

//...
plugins: [
 angular({ tsconfig: `${__dirname}/tsconfig.spec.json` })
]
```

**Comment by joewIST** [comment]
Thanks @brandonroberts that sorted it! Now I can enjoy faster tests and finally replace Jest.

**Comment by brandonroberts** [comment]
Awesome

**Comment by ddamiankowalski** [comment]
I have the same error as @joewIST, however setting the plugin inside `vite.config.mts` did not solve the issue

**Comment by brandonroberts** [comment]
@ddamiankowalski what issue are you having? The missing `@angular/build` package or something different?

**Comment by ddamiankowalski** [comment]
@brandonroberts I've used the solution to add the peer dependencies for my project which allowed me to run the tests inside my nx workspace, however when running tests I get the error. 

`Error: No test suite found in file {pathFile}`

I have set my vitest config like so

```
/// <reference types='vitest' />
import angular from '@analogjs/vite-plugin-angular';
import { nxCopyAssetsPlugin } from '@nx/vite/plugins/nx-copy-assets.plugin';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { defineConfig } from 'vite';

export default defineConfig(() => ({
  root: __dirname,
  cacheDir: '../../node_modules/.vite/libs/project-name',
  plugins: [
    angular({ tsconfig: `${__dirname}/tsconfig.spec.json` }),
    nxViteTsPaths(),
    nxCopyAssetsPlugin(['*.md']),
  ],
  // Uncomment this if you are using workers.
  // worker: {
  //   plugins: () => [ nxViteTsPaths() ],
  // },
  test: {
    name: 'project-name',
    watch: false,
    globals: true,
    environment: 'jsdom',
    include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    setupFiles: ['src/test-setup.ts'],
    reporters: ['default'],
    coverage: {
      reportsDirectory: '../../coverage/libs/project-name',
      provider: 'v8' as const,
    },
  },
}));
```

**EDIT:** Okay, so I think actually the problem is that the tests fail when I import something using a typescript import mapping in my nx project, for example:

`import { hasClass } from '@testing/utils';`

Does anybody know if there is a fix for that?

**Comment by brandonroberts** [comment]
Yes, you just need to set up path aliases

https://analogjs.org/docs/features/testing/vitest#using-typescript-config-path-aliases

**Comment by ddamiankowalski** [comment]
I did, as I mentioned above in the config pasted. Anyway, thank you for help. I guess I will have to dig in deeper into why `nxViteTsPaths` plugin does not work. It was misleading because right now when I run `npx nx test chart-{{ projectName }}` I get the error

```
Error: No test suite found in file...
```

**Comment by brandonroberts** [comment]
@ddamiankowalski  got it. `No test suite` means the files are not being included in the TypeScript compilation. Check the tsconfig to see if `noEmit` is `enabled`. Also check the `files` and `include` arrays to see if the correct files are being included.
