### ISSUE TITLE
vitest-angular:test and vitest-angular:build-test should forward more vitest CLI arguments

### ISSUE THREAD

**Issue by NateRadebaugh** [analogjs/analog#1473]
### Which scope/s are relevant/related to the feature request?

vitest-angular

### Information

At the moment, the `schema.json` for analog vitest builders only include `watch` but are missing a few CLI commands.
* test - https://github.com/analogjs/analog/blob/beta/packages/vitest-angular/src/lib/builders/test/schema.json
* build - https://github.com/analogjs/analog/blob/beta/packages/vitest-angular/src/lib/builders/build/schema.json

For instance:
* `silent` - https://vitest.dev/guide/cli#silent
* `logHeapUsage` - https://vitest.dev/guide/cli#logheapusage

Somehow coverage I think is wired up already, but I'm not sure the right configuration and whether other CLI customization would work.

Is there a way to forward all supported vitest CLI arguments, or just add the above (and others that may be more generally relevant?)

### Describe any alternatives/workarounds you're currently using

From reading the analog docs, it sounded like there's some added benefit from using `ng test` directly instead of using `vitest` command from the CLI.

Right now I'm using `vitest` directly from the CLI, but I was hoping to be able to use `ng test` from the CLI successfully with my additional arguments.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Good idea. We are passing any additional arguments to Vitest that aren't defined in the schema. 

https://github.com/analogjs/analog/blob/beta/packages/vitest-angular/src/lib/builders/test/vitest.impl.ts#L28

Could be a bug in how those are processed though.

**Comment by NateRadebaugh** [comment]
@brandonroberts  can you confirm usage of these args? I've tried "ng test silent" and "ng test --silent" but both are returning "Error: Unknown arguments: silent"

Is there something in the docs I'm missing? Thanks

**Comment by brandonroberts** [comment]
Ahh, I see. Providing arbitrary args that aren't defined in the schema isn't allowed by the CLI. You can define them in the builder and use configurations for different combinations

```json
        "test": {
          "builder": "@analogjs/vitest-angular:test",
          "configurations": {
            "quiet": {
              "silent": true
            }
          }
        }
```

And use `ng test --configuration quiet`

**Comment by NateRadebaugh** [comment]
Thank you! Closing
