### ISSUE TITLE
ɵPendingTasks is no longer exported by @angular/core (angular 19)

### ISSUE THREAD

**Issue by louiiuol** [analogjs/analog#1496]
### Please provide the environment you discovered this bug in.

`"dependencies": {
    "@analogjs/content": "1.10.1",
    "@analogjs/router": "1.10.1",
    "@analogjs/trpc": "0.2.47",
    "@angular/animations": "^19.0.0",
    "@angular/cdk": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/material": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/platform-browser-dynamic": "^19.0.0",
    "@angular/platform-server": "^19.0.0",
    "@angular/router": "^19.0.0",
...
}
`

### Which area/package is the issue in?

content

### Description

After updating my application to angular `^19.0.0`, with `"@analogjs/content": "1.10.1",`
I get the following error:

### Please provide the exception or error you saw

Here is the stack trace:

```shell

Prerendering static pages...
Building Server...

The '@analogjs/platform' server has been successfully built.
x Build failed in 40.29s

 NX   node_modules/@analogjs/content/fesm2022/analogjs-content.mjs (2:58): "ɵPendingTasks" is not exported by "node_modules/@angular/core/fesm2022/core.mjs", imported by "node_modules/@analogjs/content/fesm2022/analogjs-content.mjs".

file: /Users/louiiuol/apps/optee/node_modules/@analogjs/content/fesm2022/analogjs-content.mjs:2:58

1: import * as i0 from "@angular/core";
2: import { inject, Directive, HostListener, InjectionToken, ɵPendingTasks as _PendingTasks, Injectable, TransferState, ...
                                                             ^
3: import { DOCUMENT, Location, AsyncPipe, isPlatformBrowser } from "@angular/common";
4: import { Router, ActivatedRoute } from "@angular/router";
```

### Other information

Locally I've "fixed this error" by updating the import located in `node_modules/@analogjs/content/fesm2022/analogjs-content.mjs`:
I've replaced `ɵPendingTasks as _PendingTasks` by `ɵNoopNgZone as _PendingTasks` and my build completes. 
Not sure if this a good fix though..

Thanks for your help ! 🙏

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @louiiuol. Its fixed in `1.10.2-beta.8`
