### ISSUE TITLE
[Vitest] Unable to call globals from library

### ISSUE THREAD

**Issue by Tommy228** [analogjs/analog#1502]
### Please provide the environment you discovered this bug in.

```
"@analogjs/vite-plugin-angular": "1.10.2-beta.11",
"@analogjs/vitest-angular": "1.10.2-beta.11",
```

### Which area/package is the issue in?

vitest-angular

### Description

This bug only happens since the `1.10.1` version. It seems to work fine with `1.10.0`.

If a library calls a global (such as `beforeEach`), then it unexpectedly fails due to `TestBed` not being initialized. 

Example:
```typescript
import { createComponentFactory } from '@ngneat/spectator';
import { TestComponent } from './test.component';

describe('TestComponent', () => {
  // Uses beforeEach.
  const createComponent = createComponentFactory(TestComponent);

  it('test #1', () => {
    expect(createComponent().component).toBeTruthy();
  });
});
```

It was able to reproduce this with a tiny library which only exports this function
```typescript
export function setup() {
  beforeEach(() => TestBed.configureTestingModule({}));
}
```

I was not able to reproduce this with [ng-mocks](https://github.com/help-me-mom/ng-mocks). I think it has to do with the fact that `ng-mocks` exports CJS output while spectator produces a ESM output.

### Please provide the exception or error you saw

```true
stderr | src/lib/test-component/test.component.spec.ts > TestComponent > test #1
Error: Need to call TestBed.initTestEnvironment() first
```

### Other information

Minimal reproduction here: https://github.com/Tommy228/analogjs-vitest-test

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
In this case, you need to inline the `@ngneat/spectator` package so it gets transformed with vite before the tests run.

```
/// <reference types="vitest" />
import { defineConfig } from 'vite';

import angular from '@analogjs/vite-plugin-angular';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';

export default defineConfig(({ mode }) => ({
  plugins: [angular(), nxViteTsPaths()],
  test: {
    globals: true,
    setupFiles: ['src/test-setup.ts'],
    environment: 'jsdom',
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    reporters: ['default'],
    // inline @ngneat/spectator
    server: {
      deps: {
        inline: ['@ngneat/spectator']
      }
    }
  },
  define: {
    'import.meta.vitest': mode !== 'production',
  },
}));
```
