### ISSUE TITLE
Add support for Vitest CLI `--coverage` and `--ui` flags

### ISSUE THREAD

**Issue by jorgeandrespadilla** [analogjs/analog#1520]
### Which scope/s are relevant/related to the feature request?

vitest-angular

### Information

The `@analogjs/vitest-angular` package currently lacks support for the `--coverage` and `--ui` flags when using the CLI. These options are key for enabling test coverage and UI mode directly through the command line.

### Describe any alternatives/workarounds you're currently using

To enable these features, we must manually specify custom options in the builder configuration (inside the `angular.json` file), as shown below:

```jsonc
{
  // ...
  "test": {
    "builder": "@analogjs/vitest-angular:test",
    "options": {
      "watch": true,
      "ui": true,
      "coverage": {
        "enabled": true
      }
    }
  }
  // ...
}
```

Adding multiple targets in angular.json to support testing variants like coverage and UI mode unnecessarily complicates the configuration

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks! You can test out with `1.11.0-beta.2`
