### ISSUE TITLE
[FEAT] Add default Analog SERVER_CONTEXT for SSR/SSG/any

### ISSUE THREAD

**Issue by Yberion** [analogjs/analog#194]
### Which scope/s are relevant/related to the feature request?

Don't known / other

### Information

Hello,

It would be nice if there would be a default `SERVER_CONTEXT` set by Analog (same as `Angular Universal`) when using SSR/SSG or any other server side stuff.

- `analog-ssr`
- `analog-ssg`
- `...`

### Describe any alternatives/workarounds you're currently using

Actually what you pointed me out in our Discord discussion: https://github.com/analogjs/analog/blob/main/apps/analog-app/src/main.server.ts#L23

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Closing in favor of #327
