### ISSUE TITLE
[QUESTION] Adding Analog to Existing Project

### ISSUE THREAD

**Issue by pjlamb12** [analogjs/analog#196]
Is there a path to adding Analog to an existing Nx/Angular project? What are the required steps to add Analog support to a project?

**Comment by brandonroberts** [comment]
Yes, there is a path to adding Analog to an existing project. I have a previous Analog/Nx repo here https://github.com/brandonroberts/analog-nx-15

I may create a new one with commits on each step to migrate one

**Comment by pjlamb12** [comment]
Cool. I'll see if I can see the differences between my Nx repo and that. I wanted to see how much it's going to take to migrate my project over when the time comes. The blog demo you posted helps, but I need to see how to use some of the info in the front matter of the markdown, and getting a list of all posts for a listing page, etc. I just haven't played with it yet.

**Comment by brandonroberts** [comment]
Yep. Need to add support for front matter in the markdown files. Getting a list of all posts could be done in different ways. Vite has a nice API for getting a list of files and their contents that you could map to a list of posts with their metadata.

https://vitejs.dev/guide/features.html#glob-import

**Comment by brandonroberts** [comment]
Will track this is a more recent issue but the plan is to create a schematic that can adjust an existing Angular project to use Analog
