### ISSUE TITLE
Testing: Add E2E project for create-analog

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#201]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Need an E2E test that ensures create-analog generates a working application. This would help ensure against upgrades with external dependencies like Nx and the @nrwl/vite package.

The E2E test would:
- Run the `node packages/create-analog/index.js` script to generate a new app
- Start up the application and run an E2E test against the running app
- Maybe have modes for client/ssr mode

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
I think the nx-plugin-e2e can serve as a blueprint for that. There's a method that allows us to run not just Nx commands!

**Comment by brandonroberts** [comment]
Yep. We can run direct CLI commands also


```ts
 import { ensureDirSync } from 'fs-extra';
 import { runCommand, tmpProjPath } from '@nrwl/nx-plugin';
 
 ensureDirSync(tmpProjPath());
 runCommand(`yarn create analog test-project`);
 // ...
```

**Comment by brandonroberts** [comment]
Fixed in https://github.com/analogjs/analog/pull/478
