### ISSUE TITLE
Analog not working in Webkit based browsers

### ISSUE THREAD

**Issue by goetzrobin** [analogjs/analog#202]
### Please provide the environment you discovered this bug in.

Analog Project's do not work in webkit based browsers. 
I believe it has something to do with the Vite Angular plugin. 

_Unfortunately, you cannot reproduce this in a StackBlitz example so I cloned the analog repo and added my tests to the blog-app & analog-app applications, which both show the same behavior_

### Which area/package is the issue in?

vite-plugin-angular

### Description

**Steps to reproduce:**
1. Add some basic functionality to the AppComponent, e.g.
```
@Component({
  selector: 'analogjs-root',
  standalone: true,
  imports: [TopBarComponent, RouterOutlet],
  template: `
    <app-top-bar></app-top-bar>

    Counter: {{count}}
    <button (click)="increment()">Increment</button>

    <div class="container">
      <router-outlet></router-outlet>
    </div>
  `,
})
export class AppComponent {
  public count = 0;
  public increment(): void {
    this.count++;
  }
}
```
2. Open a **webkit** based browser such as **Safari** (on MacOS/iOS), but also Chrome on iOS
3. Click on the Increment button

**Expected Result**
The counter increases on every click.

**Actual Result**
The counter does not increase.
The console shows the following error:
<img width="1246" alt="Screenshot 2023-01-10 at 10 52 35 AM" src="https://user-images.githubusercontent.com/35136007/211598575-e8821008-fd12-4c67-8414-0d127dbd0ed7.png">

If you drill into the error the following is shown:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/35136007/211598433-38a52e79-35f1-46d7-8387-0b13ffdff204.png">

### Please provide the exception or error you saw

```true
[Error] SyntaxError: Unexpected token '{'
	(anonymous function) (app.component.ts:12)
```

### Other information

I would love to submit a PR to fix this issue but I currently am lacking the knowledge where to even start investigating this issue.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Probably related to https://github.com/angular/angular-cli/commit/cf2f30afc0ad0ceae34c457955a22186bc5ce60d
