### ISSUE TITLE
[BUG] Node > 16.17.1: Method Promise.prototype.then called on incompatible receiver

### ISSUE THREAD

**Issue by mwienk** [analogjs/analog#203]
### Please provide the environment you discovered this bug in.

node: v16.18.0 and higher

### Which area/package is the issue in?

astro-angular

### Description

I'm receiving an error when I start the sample from https://analogjs.org/docs/packages/astro-angular/overview. At the moment I connect angular into the astro application, it crashes upon requesting the page through the browser.

It might be related to https://github.com/angular/angular/issues/47872, but as the fix there is implemented through @nguniversal/builders I doubt it will fix the issue for @analogjs/astro-angular.

### Please provide the exception or error you saw

```true
error   Method Promise.prototype.then called on incompatible receiver [object Object]
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
    at node:internal/per_context/primordials:440:35
    at new Promise (<anonymous>)
    at new SafePromise (node:internal/per_context/primordials:408:29)
    at node:internal/per_context/primordials:440:9
    at Array.map (<anonymous>)
    at arrayToSafePromiseIterable (node:internal/per_context/primordials:437:5)
    at node:internal/per_context/primordials:453:21
    at new Promise (<anonymous>)
    at primordials.SafePromiseAll (node:internal/per_context/primordials:452:3)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @mwienk. I've seen this issue also and still investigating a proper fix/workaround

**Comment by brandonroberts** [comment]
I've had success with node `18.13.0`

**Comment by JeanMeche** [comment]
FYI a PR has landed for this : angular/angular#49144

**Comment by brandonroberts** [comment]
@JeanMeche awesome. Thanks for the update

**Comment by brandonroberts** [comment]
This issue has been resolve with at least Node v18.13.0 and the fixes landed in Angular v15/16
