### ISSUE TITLE
[FEAT]: Add SSR application

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#21]
Vite has built-in support for SSR https://vitejs.dev/guide/ssr.html

This application could serve as the starting point for using Analog applications with SSR, and a baseline for future support of api/server routes.

**Comment by mainawycliffe** [comment]
Will this use an express server or do we have a few alternatives to choose from?

**Comment by brandonroberts** [comment]
Good question. Most likely we'll start with express and see what other options are available. 

Some type of NestJS integration would be interesting but not sure it's possible.

**Comment by Yberion** [comment]
I'm sure a Fastify version could be done as well.

If I understand correctly, we can already make an example app with Vite SSR using Angular Universal Engine (Common/Clover) as renderer?

If so, are you fine with the example app not being Standalone since Angular Universal doesn't support it yet?

**Comment by mainawycliffe** [comment]
@brandonroberts What do you mean by NextJS integration?

This one issue I would love to explore and see if I can pull it off, but I would need some guidance on the way to approach it.

**Comment by mainawycliffe** [comment]
Makes sense

**Comment by Yberion** [comment]
> @Yberion I have a sample repo here that uses SSR without Angular Universal https://github.com/brandonroberts/analog-angular-ssr
> 
> Vite already handles the additional pieces.

I tried on my side with Angular Universal last week but I was missing some knowledges (`selectors` & `renderApplication`, `angular.default()`). Thanks for making that implementation!

Do you still require a PR for this issue (mostly copy/paste what you did) or you will do it yourself?

**Comment by mainawycliffe** [comment]
Taking a look at the repo you shared, and it looks quite nice. To do SSR, we would need to load the individual route and get component details from it and do SSR, am I right?

**Comment by brandonroberts** [comment]
@Yberion its not complete. It doesn't handle serving a production build. It just shows that it works.

 
@mainawycliffe Yes, if you have the routing setup with the Angular Router it should just SSR the app similar to how universal does it.

Long term this would be integrated inside the plugin itself. We could add some docs on using this as is today with an existing setup

**Comment by mainawycliffe** [comment]
I am just mentally modeling how the plugin would work; with analog and maybe express or nestjs, we would automatically check the route being accessed in the routes directly and SSR the page. The tricky part I can think of is to fallback to CSR so that it behaves like a SPA after the first load (maybe I am thinking to far ahead) and lazy loads the routes just like a normal angular application, but we could generate a server bundle and client bundle to work around this. 

Next.js has a Link component that enables this behavior for CSR, we could follow a similar path.

**Comment by yackinn** [comment]
I'm interested in creating an implementation with NestJS.
It could be similar to this https://github.com/nxarch/nest-nguniversal.

Can someone answer a few questions?

Is it possible to create a js bundle of a vite server?
Something like this.

```ts
import { createServer as createViteServer } from 'vite';

export const vite = await createViteServer({
  server : { middlewareMode: true },
  appType: 'custom'
});
```
Compile this into some js output bundle

What is the middleware used for?

```ts
app.use(vite.middlewares);
```
