### ISSUE TITLE
Feature: add configuration to allow custom TypeScript transformers to be added.

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#210]
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

Because Angular wraps the TypeScript compiler, being able to transform source code is usually done through transformers. One example is replacing the bootstrapping call in the `main.ts`. This feature would add a configuration option to allow custom transformers to be included before Angular compilation starts.

Existing transformers are here: https://github.com/analogjs/analog/blob/main/packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts#L446

Proposed:

```js
import { defineConfig } from 'vite';
import analog from '@analogjs/platform';

// https://vitejs.dev/config/
export default defineConfig(() => {
  return {
    plugins: [
      analog({
        advanced: {
          tsTransformers: [customTransformer]
        }
      })
    ]
  };
});
```

Provided transformers would be added to the `before` array.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by marcus-sa** [comment]
+1, would be great to use https://deepkit.io with Analog

**Comment by brandonroberts** [comment]
@marcus-sa how would this enable that?

**Comment by marcus-sa** [comment]
> @marcus-sa how would this enable that?

Deepkit needs a custom transformer for it to work.
https://docs.deepkit.io/deepkit-book-english.html under section 2.1.x

**Comment by marcus-sa** [comment]
> Then, I think, we need to change interface a tad as Deepkit requires `afterDeclaration` transformer

Yeah the API for custom transformers needs to be a bit more flexible. It's not really that self explanatory either.

**Comment by marcus-sa** [comment]
Should I add a new issue for defining other lifecycle transformers?
