### ISSUE TITLE
[Community]: Generate contributors section in README

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#23]
Commonly used tool is All Contributors https://allcontributors.org/

**Comment by jasonhodges** [comment]
Hi @brandonroberts, I could tackle this if OK with you.

**Comment by brandonroberts** [comment]
Of course

**Comment by jasonhodges** [comment]
@brandonroberts Do you want to use the AllContributors bot or manually maintain the Contributors?

**Comment by brandonroberts** [comment]
Use the bot
