### ISSUE TITLE
[LIB]: Migrate Angular Integration for Astro to this repo

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#24]
I've developed a plugin for Astro that let's use Angular components inside of an Astro project. The repository currently lives here https://github.com/brandonroberts/ng-astro in the `integration-angular` folder.

This effort would:

- Move that integration to this repo
- Rename the package to @analogjs/astro-integration-angular
- Update the package to support the new `createApplication` API upcoming in Angular 14.2 (TBD)

**Comment by mainawycliffe** [comment]
Can I take a crack at this?

**Comment by brandonroberts** [comment]
Sure, thanks! My additional thoughts were this should be generated as a `@nrwl/js:lib` with `--publishable` so there's a build step from TypeScript
