### ISSUE TITLE
The StackBlitz promoted on the homepage does not work

### ISSUE THREAD

**Issue by JohanHeyvaert** [analogjs/analog#242]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/github/analogjs/analog/tree/main/packages/create-analog/template-angular-v14

### Which area/package is the issue in?

create-analog

### Description

When trying to run the Stackblitz (https://stackblitz.com/github/analogjs/analog/tree/main/packages/create-analog/template-angular-v14) it throws an error.

![image](https://user-images.githubusercontent.com/13747250/216387415-160c8e2e-6fa3-4373-8bcf-c6abc20974ea.png)

As a first experience with Analog this doesn't look promising. Hopefully easy to fix? 

### Please provide the exception or error you saw

![image](https://user-images.githubusercontent.com/13747250/216387965-f4d02ce3-023c-476c-b317-0fb7ab636ca2.png)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Good catch, thanks @JohanHeyvaert. This should be changed here https://github.com/analogjs/analog/blob/main/apps/docs-app/src/components/StackblitzButton/index.tsx#L18 to `https://analogjs.org/new`

**Comment by JohanHeyvaert** [comment]
Wow, that was quick! Indeed, it's working now.
Thanks a lot!
