### ISSUE TITLE
May have found an issue when installing Storybook

### ISSUE THREAD

**Issue by jonnycraze** [analogjs/analog#249]
### Please provide the environment you discovered this bug in.

Procution

### Which area/package is the issue in?

create-analog

### Description

node_modules

### Please provide the exception or error you saw

```
```

### Other information

I recently created a new project using analogjs, and wanted to install storybook. After the installation, I could not get storybook to run, it threw a few errors but the error of note was that 'src/types' could not be found on the following line:

 { RequestHeaders as RequestHeaders$1 } from 'src/types';

When I opened node_modules/h3 it seemed like this package was not properly installed. I uninstalled it and storybook ran without any issues. I then reinstalled h3 directly:

```npm i h3```

This appears to have correctly installed h3, everything builds and resolves as expected in storybook, and on the development server running. I assume there may some type of dependency clash but I wasn't able to pinpoint it. Regardless I wanted to report what I experienced and how I fixed it in the case that someone else runs into this.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @jonnycraze. Will you provide a GitHub repo or steps to reproduce the issue?

**Comment by himyjan** [comment]
analog with storybook v7 beta 
using storybook Angular 15 webpack 5 file

https://github.com/himyjan/Storybook-v7-Beta-Vite4-webpack5-Angular15-React18-Vue3-TypeScript/tree/main/storybook-webpack5-analog

**Comment by brandonroberts** [comment]
Try this with the latest release and re-open if its still an issue
