### ISSUE TITLE
Feature: Add Nx library to analog-app to ensure support for tsconfig paths

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#259]
### Which scope/s are relevant/related to the feature request?

Don't known / other

### Information

To ensure there is compatibility with Analogb being used within an Nx workspace, the `analog-app` project in this repository should be updated to use a library.

- Install and configure the `vite-tsconfig-paths` plugin in the `apps/analog-app/vite.config.ts`
- Generate an Angular library in the libs folder for a component in the `analog-app`
- Refactor the component out of the `analog-app` application to use the import from the library
- Fix any issues with SSR

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@brandonroberts I can work on this!
