### ISSUE TITLE
[DOCS]: document using routeMeta to redirect to a default path

### ISSUE THREAD

**Issue by AdditionAddict** [analogjs/analog#269]
Intended PR after '\## Route Metadata' section and code

---
### Redirect to a default route

To redirect to the route `/dashboard` from `/`, define `redirectTo` and `pathMatch` inside `src/app/routes/index.ts`:
```ts
import { RouteMeta } from '@analogjs/router';

export const routeMeta: RouteMeta = {
  redirectTo: '/dashboard',
  pathMatch: 'full',
};
```
---

Or is there a preference to keep using parenthesis index route like `src/app/routes/(redirect).ts`?

**Comment by brandonroberts** [comment]
Interesting convention around the `(redirect).ts`.  I think the `index.ts` would be clearer, as you don't have to name it `(redirect)` for it to work
