### ISSUE TITLE
Router: Route config for named nested routes is not generated correctly

### ISSUE THREAD

**Issue by markostanimirovic** [analogjs/analog#273]
### Which area/package is the issue in?

router

### Description

If the `routes` directory has the following structure:

```
/routes
  /users
    create.ts
```

Navigation to `/users/create` will not work. As a workaround, we can use 'dot' notation:

```
/routes
  users.create.ts
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @markostanimirovic. I think this should be supported also.

This was also brought up in the [Analog Discord](https://chat.analogjs.org)

**Comment by yassernasc** [comment]
Hello, I am having trouble creating a route with the scheme: `route.[route-id].subroute.[subroute-id].ts` and I think Analog wasn't designed to handle such a complex scenario. Is my problem related to this github issue?

**Comment by yassernasc** [comment]
I see, thank you for pointing out the exact location to debug.
