### ISSUE TITLE
Feat: Support Content Subdirectories

### ISSUE THREAD

**Issue by BaronVonPerko** [analogjs/analog#282]
### Which scope/s are relevant/related to the feature request?

content

### Information

Right now, all of the content files must be placed in the content directory like `/src/content/*.md` in order for `injectContent` to work.

There may be cases where content needs to be separated.  For example, maybe you have blog posts, but also project markdown files for a portfolio page.  Something like this would be ideal (in order to make the blog list or project list components easier to write):

```
src/
└── content/
    └── posts/
    |   └── 2023-01-01-my-post.md
    |   └── 2023-01-12-my-other-post.md
    └──projects/
       └── some-awesome-app.md
```

Could we add another parameter to the `injectContent()` to accept a prefix?  Then update the `switchMap` to something like this:

```ts
switchMap((slug) => {
      const filename = `/src/content/${prefix}${slug}.md`;
```

Happy to open a PR for this 😄 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Good idea. What about changing the `slug` argument taking a `string | { slug: string, prefix: string }`?

**Comment by BaronVonPerko** [comment]
Yeah, I think that makes more sense.  I'll work on that PR 👍
