### ISSUE TITLE
Feature: configurable API route expose path

### ISSUE THREAD

**Issue by kyjus25** [analogjs/analog#287]
### Which scope/s are relevant/related to the feature request?

platform/vite-nitro-plugin

### Information

According to my preliminary search of the codebase (and that it is hardcoded [here](https://github.com/analogjs/analog/blob/main/packages/platform/src/lib/runtime/api-middleware.js) and [here](https://github.com/analogjs/analog/blob/main/packages/platform/src/lib/vite-nitro-plugin.ts#L95)), there seems to be no way to change the API routes to something other than `/api`.

In my very specific use case, I would like to change this to be `/services` so that the endpoints match my existing backend architecture.

I imagine this would be a configuration setting in the Vite plugin.

### Describe any alternatives/workarounds you're currently using

N/A

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Seems reasonable to me to support this

**Comment by brandonroberts** [comment]
@goetzrobin @kyjus25 said they would be willing to put in a PR, so I'd let them do it if they still want to.

**Comment by goetzrobin** [comment]
@brandonroberts I am sorry! I completely missed that! I will hold off! @kyjus25 let me know if I can be of any help!
