### ISSUE TITLE
client:only support for Astro Angular components

### ISSUE THREAD

**Issue by R-Bower** [analogjs/analog#291]
### Which scope/s are relevant/related to the feature request?

astro-angular

### Information

I'd like to be able to add a `client:only` directive to Angular components within Astro pages.  [Relevant Astro docs](https://docs.astro.build/en/reference/directives-reference/#clientonly).

### Describe any alternatives/workarounds you're currently using

None

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Form looking through the source code, the `client:only` directive is only supported by official Astro integrations.

**Comment by brandonroberts** [comment]
Example

Works
```js
import { defineConfig } from 'astro/config';
import angular from "@analogjs/astro-angular";

// https://astro.build/config
export default defineConfig({
  outDir: '../../dist/apps/astro-app',
  integrations: [
    angular(),
  ]
});
```

Does not work
```js
import { defineConfig } from 'astro/config';
import angular from "@analogjs/astro-angular";
import react from '@astrojs/react';

// https://astro.build/config
export default defineConfig({
  outDir: '../../dist/apps/astro-app',
  integrations: [
    angular(),
    react()
  ]
});
```
