### ISSUE TITLE
[DOCS]: Spin up docs site

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#3]
Build docs site with:

- Project overview
- Install instructions
- Contributing
- Sponsoring

Options
- Docusaurus
- Hand-rolled
- Other?

It will be hosted on analogjs.org

**Comment by LayZeeDK** [comment]
I'm happy to help with Docusaurus and GitHub Pages.

**Comment by brandonroberts** [comment]
I'm on board with using Docusaurus and GitHub pages to start. May move deployment to Netlify later for PR previews and such

**Comment by LayZeeDK** [comment]
Suggestions for the *Sponsoring* page, @brandonroberts?

**Comment by brandonroberts** [comment]
My suggestions would.

You can sponsor this project through GitHub sponsors with a link to that.

Sponsorships of at least $50/month will get their logo added to the GitHub README.

Sponsorships of at least $100/month will get their logo added to the GitHub README and the homepage of the website. Thanks will also be mentioned in blog posts about the project.

Sponsorships over and above these amounts can be discussed further about sponsorship opportunities.
