### ISSUE TITLE
Building error of the repo on Windows

### ISSUE THREAD

**Issue by Yberion** [analogjs/analog#30]
### Which analog package(s) are the source of the bug?

I cloned the current state of the repo which contains:
- `vite-plugin-angular 0.2.0-alpha.6`
- `create-analog 0.1.6`

### Is this a regression?

No.

### Description

Hello,

I cloned the repo and wanted to build it with the command `nx run-many --target build --all` (`npm run build`).
It failed on `nx run create-analog:build` with the following error:

```
>  NX   ERROR: Something went wrong in run-commands - Command failed: mkdir -p dist/packages/create-analog && cp -r packages/create-analog dist/packages/create-analog

Pass --verbose to see the stacktrace.
```

I think it's because I'm on Windows with `PowerShell 7`. I tested with the Windows command version of `mkdir` and `cp` but it did not work either.
I'm not familiar yet with nx, so I'm maybe missing a step.

I can't provide a reproduction as it seems to be an OS specific problem.

### Please provide the environment you discovered this bug in

```
OS: Windows 11
Node: 16.16.0
NPM: 8.17.0
Console/Terminal: PowerShell 7.2.6 (no WSL, no GitBash)
Angular: 14 (same as on the repo)
```

**Comment by LayZeeDK** [comment]
`mkdir -p` is a Unix command. It would be better to use a cross-platform script. I have the same problem on Windows using PowerShell.

**Comment by brandonroberts** [comment]
Yep. I'll get a fix in for that
