### ISSUE TITLE
Feature: Include Tailwind CSS support out of the box

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#303]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

This would add the necessary files and configuration to setup Tailwind to use with Analog on initial setup.

Would be enabled by default with a flag/prompt to disable.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by MDyrcz5** [comment]
@brandonroberts  could you assign me to this one, please?

**Comment by goetzrobin** [comment]
@brandonroberts @MDyrcz5 we should probably include this is the Nx generator too once it is merged!
I would suggest an option called `--skipTailwind` and a prompt `Set up tailwind for your workspace?` that defaults to true.
I guess for Nx we would also need to check if there is a tailwind setup already in place?

**Comment by brandonroberts** [comment]
I agree. May end up creating a separate template for including Tailwind out of the box, maybe with the blog template in #309
