### ISSUE TITLE
Feature: add blog template to application generator

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#309]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

When generating a new project with `create-analog`, there should be an option to scaffold out a blog template application with support for content routes (and maybe Tailwind) included.

Includes
- / for home route that redirects to /blog
- /blog parent route
- /blog index route that lists posts
- /blog/[slug].page.ts that displays the blog post based on id
- Stub markdown file in the `/src/content` folder
- Minimal styles
- Prerendered route included in the `vite.config.ts`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
We could add an option for dark mode support too if that's something worth adding?

**Comment by MDyrcz5** [comment]
> We could add an option for dark mode support too if that's something worth adding?

@goetzrobin in my opinion it's a developer preference to add such a mode 👀

**Comment by goetzrobin** [comment]
> > We could add an option for dark mode support too if that's something worth adding?
> 
> @goetzrobin in my opinion it's a developer preference to add such a mode 👀
> And just focus on minimal setup 🤔

That's a fair point. My thinking was that if you choose this template you are already opting into a lot more than a minimal setup so this might be helpful to someone who wants to get up and running quickly

**Comment by brandonroberts** [comment]
If adding dark mode is just a couple of lines to add/remove, I think it's ok to include.

**Comment by BaronVonPerko** [comment]
Is this being worked on?  I'd like to help out with this enhancement 🙂

**Comment by goetzrobin** [comment]
I was waiting to see if create analog would also use the Nx plugin under the hood, so no work done yet. 

@brandonroberts do you think you'll go forward with that? 

Feel free to pick it up either way @BaronVonPerko 👌

**Comment by luishcastroc** [comment]
Is this the same as the generator/schematic? cause i was going to work on that after i finish the docs for the page

**Comment by brandonroberts** [comment]
@luishcastroc this is different, but may be able to use the same generator/schematic. 

@BaronVonPerko @goetzrobin yes, I think we'll move forward on that. I should have something on that soon, but if you want to put a template together, it shouldn't be much to migrate it.

**Comment by choyiny** [comment]
Would be ideal to have Meta tags as part of the blog template too to demonstrate link previewing
