### ISSUE TITLE
Feature: Move Vite/Nitro integration into a standalone plugin

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#318]
### Which scope/s are relevant/related to the feature request?

platform

### Information

Currently Analog uses Nitro underneath as its server engine, configured through an internal Vite plugin. This feature would separate the internal Vite/Nitro plugin from `@analogjs/platform` plugin into its package as `@analogjs/vite-plugin-nitro`.

This plugin would be framework agnostic and able to be used in any Vite application.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
It was using Nitro to build the server app, but none of the Nitro parts were being used there. Creating a separate plugin for server integration would also require building a new process for prerendering pages also.

It's possible, but would be a more substantial effort.

**Comment by goetzrobin** [comment]
I can work on this! Also open to look at another issue! Let me know where you think my time is spent best! 🚀

**Comment by brandonroberts** [comment]
You're welcome to pick it up! 🚀
