### ISSUE TITLE
Docs: Nx Plugin

### ISSUE THREAD

**Issue by yassernasc** [analogjs/analog#320]
### Please provide the environment you discovered this bug in.

not quite a bug 😅 

### Which area/package is the issue in?

Docs

### Description

At `packages/nx-plugin/README.md`, instead:
> nx g @analogjs/**nx**:app analog-app

The correct command seems to be 
> nx g @analogjs/**platform**:app analog-app

As well, we can create a new page inside the Integration section at the official docs with the `packages/nx-plugin/README.md` content.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @yassernasc.  That fix would be good. I'd like to have a more detailed docs page for usage with Nx under the Integrations section, so I think it would be its own document of how to:

- Install the package
- Run the generator for a new application
- Run the nx build, nx test commands
- Generate an E2E application (future)

**Comment by brandonroberts** [comment]
I think its ok to test out with. I ran into an issue with a completely empty workspace also. There is no `tsconfig.base.json` generated with an empty workspace which caused an error when trying to generate a new app.

These steps worked for me:

1. npx create-nx-workspace@latest my-workspace (Choose integrated)
2. (Choose angular workspace preset)
3. npm i @analogjs/platform --save-dev
4. nx g @analogjs/platform:app analog-app
5. nx build analog-app
6. nx test analog-app

**Comment by brandonroberts** [comment]
We should support starting from an empty workspace with no preset also @goetzrobin

**Comment by brandonroberts** [comment]
Not quite yet. Nx is for "stable" projects, and we aren't quite there yet version-wise.

**Comment by goetzrobin** [comment]
I'll give this some love the next couple days/weeks and make sure you can get analog up and running in Nx with a single step

**Comment by DonaldMurillo** [comment]
> I think its ok to test out with. I ran into an issue with a completely empty workspace also. There is no tsconfig.base.json generated with an empty workspace which caused an error when trying to generate a new app.
> These steps worked for me:
> npx create-nx-workspace@latest my-workspace (Choose integrated)
(Choose angular workspace preset)
npm i @analogjs/platform --save-dev
nx g @analogjs/platform:app analog-app
nx build analog-app
nx test analog-app

I tried the steps mentioned above but got the following error
![image](https://user-images.githubusercontent.com/54650861/235367322-fe4b5156-9913-4b7c-bde2-053a8da76c9f.png)
nx workspace version 16.0.1 and 15.9.2. 
No real action required, I just wanted to bring it up

**Comment by brandonroberts** [comment]
We can close this one right?

**Comment by goetzrobin** [comment]
I’d say so
