### ISSUE TITLE
RFC: how to intergrate from angular to analogjs?

### ISSUE THREAD

**Issue by nhlinh123** [analogjs/analog#332]
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

angular v13 so i have to intergration to angular v15 and then install vite-plugin-angular right?
can someone help me with this ? 
thank you guys very much.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
You'd have a better experience updating to the latest version of Angular, and creating a new Analog project to compare the differences in the angular.json
