### ISSUE TITLE
Production Mode

### ISSUE THREAD

**Issue by SOG-web** [analogjs/analog#335]
Can I use this project in a production app.

Am building a new startup product

**Comment by SOG-web** [comment]
Great, but I can't find anything on the docs that talks on the flags available using the create analog cli, e.g add Tailwindcss on app generation

**Comment by SOG-web** [comment]
Never mind, the cli did it well.

I love this project, it really making Angular development very easy

**Comment by SOG-web** [comment]
Oh great what part of the project can I contribute to in order to update the doc

**Comment by antoineheitzmann0** [comment]
https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md

**Comment by SOG-web** [comment]
What is the difference between the routes and pages folder

**Comment by SOG-web** [comment]
And also what your suggestion on the file arrangement, like where to be putting the template file a each page and the style file

**Comment by SOG-web** [comment]
import { RouteMeta } from '@analogjs/router';

export const routeMeta: RouteMeta = {
  redirectTo: '/home',
  pathMatch: 'full',
};

This does not seems to be working

**Comment by SOG-web** [comment]
Not found route is not also working

**Comment by SOG-web** [comment]
> Thanks @SOG-web the issue with not found routes is fixed in the latest release. If you need more help, consider joining the [Discord](https://chat.analogjs.org)

The link is not loading

**Comment by brandonroberts** [comment]
https://discord.com/invite/mKC2Ec48U5
