### ISSUE TITLE
Introduction should have the explanation of what is a meta framework. Not pointing to another tool so we go to their documentation

### ISSUE THREAD

**Issue by titusfx** [analogjs/analog#336]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

The introduction should have an explanation of what is a meta-framework. Not pointing to another tool so we go to their documentation
I think this is a bad practice in several layers because if I need to go to another documentation to understand the most basic concept of the tool, that implies that the documentation will be really bad or null. This implies that I should check other tools.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Good point @titusfx. The initial page was done to show the two working together. The plan is to refresh the page with the Analog logo and a link to the Analog docs
