### ISSUE TITLE
ng serve -o

### ISSUE THREAD

**Issue by fireflysemantics** [analogjs/analog#357]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Hi.  Thanks for making AnalogJS!  It's very cool!!  

When I run `ng serve -o` on a project the result is:

```
Error: Unknown argument: o
```

Would be nice to have the ability to open a browser tab automatically.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is already supported, it just doesn't have an alias. This works:

```sh
ng serve --open
```
