### ISSUE TITLE
Sample Project with usage of service/provider

### ISSUE THREAD

**Issue by ArunYogi** [analogjs/analog#366]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

It would be more helpful, if you provide more example projects with little more complexity like using service/provider and routing with params.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
Hey @ArunYogi 👋 

The `analog-app` in the repository uses a service, which might help you.
I also wrote an article that creates a project that uses a service. 
It might be helpful for you:
[https://dev.to/this-is-angular/dark-mode-with-analog-tailwind-4049](https://dev.to/this-is-angular/dark-mode-with-analog-tailwind-4049 )

However, as this project matures improving the documentation available will definitely be part of our efforts. Please feel free to share any suggestions, wishes, ideas you have based on your experience so far!

**Comment by brandonroberts** [comment]
Thanks @goetzrobin, closing as resolved

**Comment by goetzrobin** [comment]
@brandonroberts I’ll also make sure to cover this in the series I am working on!
