### ISSUE TITLE
[DOCS] fix buttons styling on mobile

### ISSUE THREAD

**Issue by dalenguyen** [analogjs/analog#38]
CTA on mobile is not responsive

**Current Behaviour**

![image](https://user-images.githubusercontent.com/14116156/185455836-aa3b9fc2-1313-4321-80d7-85c2d1df9e9b.png)

**Expect Behaviour**

CTA buttons should be responsive on mobile

**Comment by dalenguyen** [comment]
And can I work on this ticket? 🤣

**Comment by brandonroberts** [comment]
Lol yes of course. While you're in there will you update the color for the header to match on lite/dark modes. The red should be the one used in the light mode on both.

**Comment by LayZeeDK** [comment]
>Lol yes of course. While you're in there will you update the color for the header to match on lite/dark modes. The red should be the one used in the light mode on both.

This is a separate issue. Please open another issue for this.

That being said, the read has been lightened for accessibility WCAG-AA contrast concerns [as recommended by Docusuarus](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima).

**Comment by brandonroberts** [comment]
Thanks Lars. I thought to file a new issue for this also but didn't. Good call on the accessibility front but I'd like the color to be closer to the ones in the logo. I'll file a separate issue to keep the conversation there.
