### ISSUE TITLE
Add tRPC support to create-analog

### ISSUE THREAD

**Issue by goetzrobin** [analogjs/analog#388]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Now that the nx-plugin supports adding the tRPC client we should support the same setup with the standalone create-analog command.

### Describe any alternatives/workarounds you're currently using

Manually install @analogjs/trpc after creating a new app 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
We are basically maintaining two separate templating systems at this point. Idea. What do you think about switching `create-analog` to basically be a wrapper around:

`npx create-nx-workspace --preset=@analogjs/platform`

Pros
- Simplifies maintenance
- Takes advantage of standalone Nx CLI project.json structure for Angular apps
- Works the same inside/outside of Nx monorepo

Potential Cons
- It would move us off the Angular CLI with `angular.json`
- Lose `ng update`, `ng add`

**Comment by goetzrobin** [comment]
@brandonroberts what are we thinking here? maybe we could even ask this is the discord and see what people think?

**Comment by brandonroberts** [comment]
Going to close this is as tRPC support is moving to Spartan UI but still available in the 0.2.45 version of `@analogjs/trpc`
