### ISSUE TITLE
[DOCS]: Update homepage header to different shade of red in dark mode

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#39]
Update the color for the header to match on lite/dark modes. The red should be the one used in the light mode on both.

That being said, the red has been brightened in dark mode for accessibility WCAG-AA contrast concerns when used with black [as recommended by Docusaurus](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima).

_Originally posted by @LayZeeDK in https://github.com/analogjs/analog/issues/38#issuecomment-1219769649_

**Comment by LayZeeDK** [comment]
Use [this Docusaurus tool](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima) to generate shades and tints of red for dark mode.

The color variables are defined in https://github.com/analogjs/analog/blob/main/apps/docs-app/src/css/custom.css.

**Comment by umairhm** [comment]
@brandonroberts I will like to give this a try, please assign it to me.

**Comment by umairhm** [comment]
@brandonroberts @LayZeeDK What if we leave the banner as-is in both dark and light modes, including the copy and buttons? The rest of the page changes anyways, and the banner can stay as-is.

**Comment by LayZeeDK** [comment]
The banner is probably where the color variation is currently the most apparent. How about the opposite of what you're suggesting? Banner uses the *real* red while everything else uses the brighter palette in dark mode.

**Comment by brandonroberts** [comment]
@LayZeeDK @umairhm the other color choices are fine in my opinion. I'd have to see a preview of the proposed changes

**Comment by brandonroberts** [comment]
Resolved in https://github.com/analogjs/analog/pull/251
