### ISSUE TITLE
ng build error: Cannot find package 'destr' imported from /**/dist/.nitro/prerender/index.mjs Did you mean to import destr@1.2.2/node_modules/destr/dist/index.cjs?

### ISSUE THREAD

**Issue by luca-peruzzo** [analogjs/analog#393]
### Please provide the environment you discovered this bug in.

{
  "name": "analog-project",
  "version": "0.0.0",
  "private": true,
  "engines": {
    "node": ">=16.0.0"
  },
  "scripts": {
    "dev": "ng serve",
    "ng": "ng",
    "start": "pnpm run dev",
    "build": "ng build",
    "watch": "ng build --watch",
    "test": "ng test"
  },
  "dependencies": {
    "@analogjs/content": "^0.2.0-beta.7",
    "@analogjs/router": "^0.2.0-beta.7",
    "@angular/animations": "^16.0.0",
    "@angular/common": "^16.0.0",
    "@angular/compiler": "^16.0.0",
    "@angular/core": "^16.0.0",
    "@angular/forms": "^16.0.0",
    "@angular/platform-browser": "^16.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0",
    "@angular/platform-server": "^16.0.0",
    "@angular/router": "^16.0.0",
    "@nx/angular": "^16.0.0",
    "front-matter": "^4.0.2",
    "marked": "^4.2.12",
    "prismjs": "^1.29.0",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@analogjs/platform": "^0.2.0-beta.7",
    "@angular-devkit/build-angular": "^16.0.0",
    "@angular/cli": "^16.0.0",
    "@angular/compiler-cli": "^16.0.0",
    "@nx/vite": "^16.0.0",
    "nx": "^16.0.0",
    "jsdom": "^20.0.0",
    "typescript": "~5.0.2",
    "vite": "^4.0.3",
    "vitest": "^0.31.0",
    "tailwindcss": "^3.3.1",
    "postcss": "^8.4.21",
    "autoprefixer": "^10.4.14"
  }
}

### Which area/package is the issue in?

Don't know / Other

### Description

After create the analog project with pnpm (pnpm create analog) and after the installation, I've an error during server build using ng build. 

### Please provide the exception or error you saw

```true
Building Server...
An unhandled exception occurred: Cannot find package 'destr' imported from /**/dist/.nitro/prerender/index.mjs
Did you mean to import destr@1.2.2/node_modules/destr/dist/index.cjs?
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by luca-peruzzo** [comment]
It seems a problem related to pnpm.
I've had no errors in reinstalling and building the project using yarn.

**Comment by brandonroberts** [comment]
Yea, there are some ongoing issues with pnpm at the moment. Try installing the `destr` package and adding it to your package.json in the devDependencies

**Comment by brandonroberts** [comment]
Left some setup instructions here for pnpm

https://github.com/analogjs/analog/issues/361#issuecomment-1605772975
