### ISSUE TITLE
Server crashes on API Routes

### ISSUE THREAD

**Issue by zawasp** [analogjs/analog#406]
### Please provide the environment you discovered this bug in.

In the default `create-analog` template, run `npm run build`.

### Which area/package is the issue in?

create-analog

### Description

 Start the server using `node dist/analog/server/index.mjs` and navigate to `http://localhost:3000/api/v1/hello`.

In light of discussion on Discord, this is caused by `favicon.ico`. It should be in the `src/assets/` folder.

### Please provide the exception or error you saw

```true
`
Listening http://[::]:3000
[nitro] [dev] [unhandledRejection] Error: NG04002
`
```

### Other information

The exception is more verbose if you use a different Nitro preset, e.g. Azure:
- Set the preset to Azure in `vite.config.ts`:
`... 
plugins: [
    analog({
      nitro: {
        preset: 'azure',
      },
    }),
  ],
...`
- `npm run build`
- `npx @azure/static-web-apps-cli start dist/analog/public --api-location dist/analog/server/`
- navigate to `http://localhost:4280/api/v1/hello`
Server crashes:
> [swa] GET http://localhost:4280/api/v1/hello - 200
[swa] GET http://localhost:7071/api/server (proxy)
[api] [2023-05-19T14:06:00.634Z] Executing 'Functions.functions' (Reason='This function was programmatically called via the host APIs.', Id=d72c3fe7-73ef-4867-9a0d-cd9752f62065)
[api] [2023-05-19T14:06:00.900Z] [error] Worker c6a6270f-9f57-4f36-9ff5-9354af073bdc uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: NG04002     at Recognizer.noMatchError (file:///home/mrila/work/analog-crash/dist/analog/server/functions/chunks/main.server.mjs:36125:12)     at file:///home/mrila/work/analog-crash/dist/analog/server/functions/chunks/main.server.mjs:36136:20     at /home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51     at OperatorSubscriber._this._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
[api] [2023-05-19T14:06:00.911Z] Language Worker Process exited. Pid=20860.
[api] [2023-05-19T14:06:00.911Z] node exited with code 1 (0x1). LanguageWorkerConsoleLog[error] Worker c6a6270f-9f57-4f36-9ff5-9354af073bdc uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: NG04002     at Recognizer.noMatchError (file:///home/mrila/work/analog-crash/dist/analog/server/functions/chunks/main.server.mjs:36125:12)     at file:///home/mrila/work/analog-crash/dist/analog/server/functions/chunks/main.server.mjs:36136:20     at /home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51     at OperatorSubscriber._this._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30).
[api] [2023-05-19T14:06:00.943Z] Executed 'Functions.functions' (Failed, Id=d72c3fe7-73ef-4867-9a0d-cd9752f62065, Duration=308ms)
[api] [2023-05-19T14:06:00.943Z] System.Private.CoreLib: Exception while executing function: Functions.functions. System.Private.CoreLib: node exited with code 1 (0x1). LanguageWorkerConsoleLog[error] Worker c6a6270f-9f57-4f36-9ff5-9354af073bdc uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: NG04002     at Recognizer.noMatchError (file:///home/mrila/work/analog-crash/dist/analog/server/functions/chunks/main.server.mjs:36125:12)     at file:///home/mrila/work/analog-crash/dist/analog/server/functions/chunks/main.server.mjs:36136:20     at /home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51     at OperatorSubscriber._this._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)     at Subscriber.error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)     at Subscriber._error (/home/mrila/work/analog-crash/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30).

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This has been resolved and is stable in the 0.2.x release. Reopen if you're still having issues
