### ISSUE TITLE
Failing Playwright component test in JIT mode

### ISSUE THREAD

**Issue by sand4rt** [analogjs/analog#409]
### Please provide the environment you discovered this bug in.

1. Clone the PR: [`https://github.com/sand4rt/playwright-ct-angular/pull/4`](https://github.com/sand4rt/playwright-ct-angular/pull/4)
2. Install packages: `pnpm i`
3. Run tests: `pnpm run test`

### Which area/package is the issue in?

vite-plugin-angular

### Description

I have a failing test that works in AOT mode but fails in JIT mode: https://github.com/sand4rt/playwright-ct-angular/blob/main/ct-angular/tests/angular-router.spec.ts#L5

What is special about this test is that the router is registered in: https://github.com/sand4rt/playwright-ct-angular/blob/main/ct-angular/playwright/index.ts#L18. The index.ts file is imported with a script tag in: https://github.com/sand4rt/playwright-ct-angular/blob/main/ct-angular/playwright/index.html#L10

### Please provide the exception or error you saw

```true
NG0304: 'router-outlet' is not a known element (used in the 'AppComponent' component template):
1. If 'router-outlet' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
@sand4rt is this still an issue?

**Comment by brandonroberts** [comment]
I think this has been resolved in Angular v16.x. The example in your repo is still on v16. Have you tried it with an Angular v16 project?

**Comment by brandonroberts** [comment]
Closing as resolved
