### ISSUE TITLE
[REPO]: Add issue template

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#41]
- General information
  - Environment
  - Bug/Feature/Docs
- Reproduction
- Whether they would like to contribute

References: https://github.com/ngrx/platform/tree/master/.github/ISSUE_TEMPLATE

**Comment by Villanuevand** [comment]
@brandonroberts  I would like to tackle this one.

**Comment by brandonroberts** [comment]
Assigned, thanks!
