### ISSUE TITLE
Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular)

### ISSUE THREAD

**Issue by sand4rt** [analogjs/analog#410]
### Please provide the environment you discovered this bug in.

1. Clone the repo: `git clone https://github.com/sand4rt/playwright-ct-angular.git`
2. Install packages: `pnpm i`
3. Run tests: `pnpm run test`

### Which area/package is the issue in?

vite-plugin-angular

### Description

When building Playwright component tests i see a lot of sourcemap warnings and i can't figure out why. See pipeline: https://github.com/sand4rt/playwright-ct-angular/actions/runs/5036859856/jobs/9033313003#step:8:18

Perhaps related: https://github.com/analogjs/analog/issues/86#issue-1380135721

### Please provide the exception or error you saw

```true
ct-angular test$ npx playwright test
ct-angular test: Running 42 tests using 1 worker
ct-angular test: vite v4.3.5 building for production...
ct-angular test: transforming...
ct-angular test: ✓ 258 modules transformed.
ct-angular test: rendering chunks...
ct-angular test: Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
ct-angular test: Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
ct-angular test: Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
ct-angular test: Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
ct-angular test: Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
ct-angular test: Sourcemap is likely to be incorrect: a plugin (@analogjs/vite-plugin-angular) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@sand4rt going to take a look at this. To confirm, this only occurs in JIT mode, correct?

**Comment by sand4rt** [comment]
Thanks! Both JIT and AOT

**Comment by sand4rt** [comment]
Hi @goetzrobin have you already looked into this? I looked into it as well, but i have no clue..

**Comment by goetzrobin** [comment]
> Hi @goetzrobin have you already looked into this? I looked into it as well, but i have no clue..

I poked around for a little but I don't really know much about source maps either... I can do some more digging or maybe @brandonroberts has some pointers? I know it's probably bridging the gap between Angular compilation and vite?

**Comment by sand4rt** [comment]
I've updated the plugin, but the issue still persists: 
https://github.com/sand4rt/playwright-ct-angular/actions/runs/7221500112/job/19676593078?pr=38#step:8:23

**Comment by brandonroberts** [comment]
Try bumping up to `0.2.28`. I tested locally and don't see the log anymore

**Comment by sand4rt** [comment]
@brandonroberts it's fixed, nice :D
