### ISSUE TITLE
Add --minimal flag to generate a minimalist application

### ISSUE THREAD

**Issue by nartc** [analogjs/analog#413]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

I want to see a `--minimal` flag when running the Application Generator. With `--minimal` flag, the generator will generate an application:
- With no test setup
- No server routes?
- A simpler `index.page.ts`

### Describe any alternatives/workarounds you're currently using

Generate a full application then remove things manually

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
I like minimal setups also

**Comment by goetzrobin** [comment]
@nartc I can pick this up if you don’t have the bandwidth right now

**Comment by nartc** [comment]
@goetzrobin go for it
