### ISSUE TITLE
Content routes with markdown component not rendered statically in Angular v16

### ISSUE THREAD

**Issue by zawasp** [analogjs/analog#424]
### Please provide the environment you discovered this bug in.

Here's a sample blog app, statically built.
https://github.com/zawasp/analog-static-issues

### Which area/package is the issue in?

content

### Description

I deployed the repo at https://analog-static-issues.pages.dev/

The https://analog-static-issues.pages.dev/about Markdown page was properly prerendered statically:
![image](https://github.com/analogjs/analog/assets/2464830/79b952f6-595a-4a2b-b4c5-ed0623ecf6f2)

However, the dynamic blog post entries at https://analog-static-issues.pages.dev/blog/post-1 and https://analog-static-issues.pages.dev/blog/post-2 are not:
![image](https://github.com/analogjs/analog/assets/2464830/f5e60ff4-0a14-409a-b89b-8dc9d4893faf)

The `app-blog-post` component is not rendered.

### Please provide the exception or error you saw

```true
The `app-blog-post` NG component appears in the HTML source, instead of its rendered content
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is an upstream Angular issue. Filed a bug here where there is a proposed workaround. Try it and see if it solves your issue

https://github.com/angular/angular/issues/50414

**Comment by zawasp** [comment]
Thanks, will try shortly.

**Comment by brandonroberts** [comment]
Yea, you also have to downgrade `zone.js` to `0.12.0` which seems to resolve it

**Comment by zawasp** [comment]
Yeah, that works, thanks!

**Comment by brandonroberts** [comment]
This has been fixed in https://github.com/angular/angular/pull/50552 and will go out with the next Angular release

**Comment by brandonroberts** [comment]
This has been resolved with the latest release of Angular
