### ISSUE TITLE
An error occured while server rendering /index.html:  require is not defined

### ISSUE THREAD

**Issue by mainawycliffe** [analogjs/analog#428]
### Please provide the environment you discovered this bug in.

Windows Subsystem Linux (WSL2)

### Which area/package is the issue in?

platform

### Description

I have just created a brand new NX application, and running it first time is giving me the following error:

![image](https://github.com/analogjs/analog/assets/12270550/ad66d967-da24-4af3-88ed-93f9b9ad5c61)

### Please provide the exception or error you saw

```true
[vite] Error when evaluating SSR module /@fs/home/mw/projects/allthingstypescript/node_modules/.pnpm/xhr2@0.2.1/node_modules/xhr2/lib/xhr2.js:
|- ReferenceError: require is not defined
    at eval (/@fs/home/mw/projects/allthingstypescript/node_modules/.pnpm/xhr2@0.2.1/node_modules/xhr2/lib/xhr2.js:121:3)
    at eval (/@fs/home/mw/projects/allthingstypescript/node_modules/.pnpm/xhr2@0.2.1/node_modules/xhr2/lib/xhr2.js:1246:4)
    at instantiateModule (file:///home/mw/projects/allthingstypescript/node_modules/.pnpm/vite@4.3.1_@types+node@16.11.7_less@4.1.3_sass@1.62.1_stylus@0.55.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-24daf00c.js:54351:15)
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Try disabling SSR and see if that helps, or adding `xhr2` to the vite config

![image](https://github.com/analogjs/analog/assets/42211/c46b359b-4bf9-4500-9e33-78ecef62d917)

**Comment by mainawycliffe** [comment]
How do I disable SSR, the second option not working

**Comment by schuchard** [comment]
@mainawycliffe looks like you're using pnpm. I was too, and had the same issue. The error does not occur with npm.

**Comment by brandonroberts** [comment]
You can disable SSR in the analog plugin

https://analogjs.org/docs/features/server/server-side-rendering#disabling-ssr

**Comment by mainawycliffe** [comment]
> @mainawycliffe looks like you're using pnpm. I was too, and had the same issue. The error does not occur with npm.

Yeah, I am. Seems like the look of all my problems, will try without and report back.

**Comment by brandonroberts** [comment]
Re-open if you're still having issues
