### ISSUE TITLE
[FEAT]: Update create-analog template application to latest dependencies

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#44]
The package.json needs updating here https://github.com/analogjs/analog/blob/main/packages/create-analog/template-angular-v14/package.json#L34-L35

Vite `^3.0.4`
Vitest `^0.21.0`

**Comment by Yberion** [comment]
Hello,

Can I take this one ?

Why not vite `^3.0.8` ?

May I suggest updating other packages of the template ?

tslib `^2.4.0`
zone.js `~0.11.8`
typescript `~4.7.4`

**Comment by brandonroberts** [comment]
Sure. Updating those also is fine with me. If you want to test it locally, run:

node ./packages/create-analog/index.js

Choose analog-project as the name
cd analog-project
yarn
yarn dev
yarn build
yarn test

The analog-project directory is ignored in git

**Comment by LayZeeDK** [comment]
Seeing that Vitest is a prerelease (<1.0.0), I suggest we don't match *minor* versions to prevent accepting breaking changes, that is:
```json
{
  "devDependencies": {
    "vitest": "~0.22.1"
  }
}
```

**Comment by brandonroberts** [comment]
I'm fine with leaving the range to accept minor versions at the moment. We're still in a prerelease state also, so I'd like to know if something breaks with the latest feature version that gets installed.

**Comment by LayZeeDK** [comment]
My point is that 0.x.0 version bumps mean breaking changes while 0.x.y versions are non-breaking feature and bugfix releases if following semantic versioning for prereleases.

**Comment by brandonroberts** [comment]
At this point in active development, yes. I'm not planning on intentionally breaking anything but we still need room to stay updated.

When we move to a beta version for the plugin, I think it's ok to tighten up the versions to be more strict. If someone says their using this stack to build towards production today, we'll revisit this accordingly.
