### ISSUE TITLE
[@analogjs/astro-angular] Only environment variables prefixed with PUBLIC_  are available in server-side code 

### ISSUE THREAD

**Issue by Drunkenpilot** [analogjs/analog#440]
### Please provide the environment you discovered this bug in.

"dependencies": {
    "@analogjs/astro-angular": "^0.2.0-beta.13",
    "@angular-devkit/build-angular": "^16.0.3",
    "@angular/animations": "^16.0.3",
    "@angular/common": "^16.0.3",
    "@angular/compiler": "^16.0.3",
    "@angular/compiler-cli": "^16.0.3",
    "@angular/core": "^16.0.3",
    "@angular/language-service": "^16.0.3",
    "@angular/platform-browser": "^16.0.3",
    "@angular/platform-browser-dynamic": "^16.0.3",
    "@angular/platform-server": "^16.0.3",
    "@astrojs/tailwind": "^3.1.3",
    "@astrojs/vercel": "^3.4.0",
    "astro": "^2.5.5",
    "bootstrap-icons": "^1.10.5",
    "daisyui": "^2.51.6",
    "rxjs": "^7.8.1",
    "stripe": "^12.7.0",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.5.2",
    "zone.js": "^0.13.0"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.9"
  }

### Which area/package is the issue in?

astro-angular

### Description

After add @analogjs/astro-angular into an Astro project,
all environment variables without prefix "PUBLIC_" are missing in server-side. 
Only variables with PUBLIC_  showed up.
 

### Other information

File: astro.config.mjs
```javascript
import analogjsangular from "@analogjs/astro-angular";
// https://astro.build/config
export default defineConfig({
  integrations: [
    tailwind(),
    analogjsangular()
  ],
  output: 'server',
  adapter: vercel()
});
```

File: src/env.d.ts
```typescript
/// <reference types="astro/client" />
interface ImportMetaEnv {
  readonly STRIPE_SK_TEST: string;
  readonly PUBLIC_STRIPE_SK_TEST: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
```

File: .env
```text
STRIPE_SK_TEST=12345
PUBLIC_STRIPE_SK_TEST=12345 
```

File:  src/stripe/server.ts
```typescript
import Stripe from "stripe";

const env = import.meta.env;

const apiKey: string = env.STRIPE_SK_TEST; // Undefined
const apiKeyPublic: string = env.PUBLIC_STRIPE_SK_TEST; // 12345

export const stripe = new Stripe(apiKey, {
  apiVersion: "2022-11-15",
});

```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Drunkenpilot** [comment]
Find a workaround
Astro Doc : [ Environment Variables](https://docs.astro.build/en/guides/configuring-astro/#environment-variables)

```typescript
import Stripe from "stripe";
/**Load directly from process **/
import { loadEnv } from "vite";
const { STRIPE_SK_TEST } = loadEnv(import.meta.env.MODE, process.cwd(), "");

const apiKey: string =STRIPE_SK_TEST; 

export const stripe = new Stripe(apiKey, {
  apiVersion: "2022-11-15",
});
/
```

**Comment by Drunkenpilot** [comment]
Here is a clean project to reproduce the issue. 
https://github.com/Drunkenpilot/astro-angular-environment-test

**Comment by brandonroberts** [comment]
Figured out what's happening here. The original code through the Vite transforms contains the environment variables, but when it passes through the Angular compilation, it reads the file from disk instead of the previously transformed file. May need to come up with a way to filter files from being compiled through Angular's compilation.

Qwik has a PR for Angular integration that only transforms Angular files in certain directories https://github.com/BuilderIO/qwik/pull/3535/files#diff-c7299caca67e83ab453cdc47b56d472bb7347e555796a4abf36d4d76cba3f83dR29
