### ISSUE TITLE
Docs: add guide on updating to the latest version

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#450]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Add instructions on updating to latest version using

nx migrate @analogjs/platform

ng update @analogjs/platform

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by SOG-web** [comment]
I have added the upgrade docs to the last section on the getting started paged.

I wanted to create a new page initially but since it just few lines, I felt it could still be added to the getting started page.

But let me know if you want me to put it on a new page

**Comment by brandonroberts** [comment]
Closed by https://github.com/analogjs/analog/pull/456
