### ISSUE TITLE
Angular 16, Cannot find module '@angular-devkit/build-angular/src/babel/presets/application'

### ISSUE THREAD

**Issue by wohlben** [analogjs/analog#457]
### Please provide the environment you discovered this bug in.

Its reproducible just by starting a new project with angular 16, so it also occurs with your linked Analog StackBlitz example

https://stackblitz.com/github/analogjs/analog/tree/main/packages/create-analog/template-angular-v16?file=vite.config.ts&preset=node

### Which area/package is the issue in?

create-analog

### Description

Its safe to close this issue if Angular 16 isn't currently supported. I just attempted to create a new project and was prompted which version to use, so I chose 16 and the just initiated project doesnt run.
 
It seems the @angular-devkit package changed the path for the application preset, the import seems to work only by adding 'tools'.

> import * as application from "@angular-devkit/build-angular/src/tools/babel/presets/application"

Hot patching the path in the node_modules directory doesn't fix it however, as then its failing on other changed paths.

### Please provide the exception or error you saw

```true
failed to load config from analog-project/vite.config.ts
Error: Cannot find module '@angular-devkit/build-angular/src/builders/browser-esbuild/angular/jit-resource-transformer'
Require stack:
- analog-project/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js
- analog-project/node_modules/@analogjs/vite-plugin-angular/src/index.js
- analog-project/node_modules/@analogjs/platform/src/lib/platform-plugin.js
- analog-project/node_modules/@analogjs/platform/src/index.js
- analog-project/vite.config.ts
- analog-project/node_modules/vite/dist/node/chunks/dep-e8f070e8.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._resolveFilename (analog-project/node_modules/tsconfig-paths/lib/register.js:103:40)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (analog-project/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js:9:36)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at _require.extensions.<computed> [as .js] (file://analog-project/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64527:17)
    at Module.load (node:internal/modules/cjs/loader:1103:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'analog-project/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js',
    'analog-project/node_modules/@analogjs/vite-plugin-angular/src/index.js',
    'analog-project/node_modules/@analogjs/platform/src/lib/platform-plugin.js',
    'analog-project/node_modules/@analogjs/platform/src/index.js',
    'analog-project/vite.config.ts',
    'analog-project/node_modules/vite/dist/node/chunks/dep-e8f070e8.js'
  ]
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @wohlben. This path was changed in Angular 16.1, and we will have a fix out soon
