### ISSUE TITLE
Docs: Add Troubleshooting section for Analog Router

### ISSUE THREAD

**Issue by MitchSmoot** [analogjs/analog#506]
### Which scope/s are relevant/related to the feature request?

router

### Information

Current documentation on Router may not explain the key concepts adequate for some mid to junior level developers. There are also some pitfalls that new analog developers have and will continue to run into when installing Analog manually or upgrading from earlier versions. I have kept a record of all of the pitfalls and kinks I have encountered, and would like to add a troubleshooting section that would address these and save time for other new analog developers.

### Describe any alternatives/workarounds you're currently using

Reaching out to the helpful community in the Analog discord, going over past help threads there, etc.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @MitchSmoot. I don't think we should have an extensive guide for troubleshooting but should document in a way that gets users on the happy path the quickest, and helps them understand the concepts, and decrease confusion where possible.

If you can add the pitfalls you ran into in this issue, that would help

**Comment by MitchSmoot** [comment]
Sorry about the hiatus, had some other priorities come up but I am in a position to get back to finishing this.

**Comment by brandonroberts** [comment]
Closing in favor of an automatic schematic
