### ISSUE TITLE
New project with TRPC throws CORS error

### ISSUE THREAD

**Issue by ashley-hunter** [analogjs/analog#519]
### Please provide the environment you discovered this bug in.

https://codesandbox.io/p/sandbox/strange-elbakyan-f4m9k2

### Which area/package is the issue in?

trpc

### Description

I created a new project with `npx create-nx-workspace --preset=@analogjs/platform` enabling the TRPC option. When I serve the application and try to add a new note on the sample page I get CORS errors in the console.

### Please provide the exception or error you saw

```
Access to fetch at 'http://127.0.0.1:4200/api/trpc/note.create?batch=1' from origin 'https://f4m9k2-4200.csb.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
127.0.0.1:4200/api/trpc/note.create?batch=1:1     Failed to load resource: net::ERR_FAILED
chunk-YKBZPBB4.js?v=31d7cea3:5618 ERROR TRPCClientError: Failed to fetch
    at _TRPCClientError.from (@analogjs_trpc.js?v=31d7cea3:702:12)
    at @analogjs_trpc.js?v=31d7cea3:1005:30
    at _ZoneDelegate.invoke (zone__js.js?v=31d7cea3:294:158)
    at Object.onInvoke (chunk-YKBZPBB4.js?v=31d7cea3:14392:25)
    at _ZoneDelegate.invoke (zone__js.js?v=31d7cea3:294:46)
    at _Zone.run (zone__js.js?v=31d7cea3:100:35)
    at zone__js.js?v=31d7cea3:1028:28
    at _ZoneDelegate.invokeTask (zone__js.js?v=31d7cea3:320:171)
    at chunk-YKBZPBB4.js?v=31d7cea3:14222:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (chunk-YKBZPBB4.js?v=31d7cea3:14222:30)
h
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Most likely need to update the `url` in the tRPC client to match the Codesandbox environment

https://codesandbox.io/p/sandbox/strange-elbakyan-f4m9k2?file=%2Fsample%2Fsrc%2Ftrpc-client.ts%3A1%2C1

**Comment by ashley-hunter** [comment]
Ah, you are correct, I was accessing it locally on localhost:4200, works fine on 127.0.0.1:4200. Thank you!
