### ISSUE TITLE
Fix: engines in create-analog should be updated to reflect compatible versions of Node

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#532]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

We have known working versions of Node that are compatible when creating new Analog projects. Currently in the `engines` property in the `package.json` we allow for incompatible versions to be used.

https://github.com/analogjs/analog/blob/main/packages/create-analog/package.json#L17-L19

The `engines` should be updated to:

```json
  "engines": {
    "node": "~16.17.0 || >=18.13.0"
  },
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by KekmaTime** [comment]
hey @brandonroberts i would like to work on this issue can you assign me this

**Comment by brandonroberts** [comment]
Thanks @KekmaTime it's already covered in https://github.com/analogjs/analog/pull/533
