### ISSUE TITLE
Allow redirect on parent component

### ISSUE THREAD

**Issue by goetzrobin** [analogjs/analog#536]
### Which scope/s are relevant/related to the feature request?

router

### Information

I have the following folder/route structure:

```
/(documentation)
  /documentation
     /introduction.page.ts
     /[...not-found].page.ts
  documentation.page.ts   
```

```ts
// /(documentation)/documentation.page.ts
export const routeMeta: RouteMeta = {
  data: {
    breadcrumb: 'Docs',
  },
};

@Component({
  selector: 'spartan-documentation',
  standalone: true,
  imports: [RouterOutlet, SideNavComponent, BreadcrumbsComponent, TwoSectionPageDirective, MainSectionDirective],
  hostDirectives: [ContainerDirective, RedirectDirective],
  host: {
    class: '',
  },
  template: `
    <spartan-side-nav />
    <section class="px-4 sm:px-0 py-6 lg:py-8">
      <spartan-breadcrumbs />
      <router-outlet />
    </section>
  `,
})
export default class ExamplesPageComponent {}
```
What I'd like to be able to do is redirect to /documentation/introduction whenever the /documentation route is accessed.
Ideally by simply providing the redirect to the routeMeta object

```ts
// /(documentation)/documentation.page.ts
export const routeMeta: RouteMeta = {
    redirectTo: 'introduction',
    pathMatch: 'full',
    data: {
    breadcrumb: 'Docs',
  },
};
```

### Describe any alternatives/workarounds you're currently using

Manually redirecting with the following directive:

```ts
@Directive({
  selector: '[spartanRedirect]',
  standalone: true,
})
export class RedirectDirective {
  @Input()
  endsWith = '';
  @Input()
  commands: string[] = [];
  private _router = injectRouter();
  private _route = injectActivatedRoute();
  constructor() {
    this._router.events
      .pipe(
        filter((e) => e.type === EventType.NavigationEnd || e.type === EventType.NavigationSkipped),
        takeUntilDestroyed()
      )
      .subscribe((e) => {
        if (!(e as NavigationEnd | NavigationSkipped).url.endsWith(this.endsWith) || this.commands.length === 0) return;
        this._router.navigate(this.commands, { relativeTo: this._route });
      });
  }
}
```

The problem is that this will break clicking the browser's back button and you have to use a different link to get to a different page

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
I think what you need here is an index route for `/documentation`.

```
/(documentation)
  /documentation
     /introduction.page.ts
     /index.page.ts
     /[...not-found].page.ts
  documentation.page.ts   
```

With a redirect

```ts
// /(documentation)/documentation/index.page.ts
export const routeMeta: RouteMeta = {
    redirectTo: 'introduction',
    pathMatch: 'full',
    data: {
      breadcrumb: 'Docs',
    },
};
```

**Comment by brandonroberts** [comment]
Yes I do think that should be the preferred way. It should be the same as a typical nested route. What happens when you set it up that way?

**Comment by goetzrobin** [comment]
It just stays at /documentation. There’s no redirect happening.

**Comment by brandonroberts** [comment]
Any errors in the console? What about redirecting to '../introduction'?

**Comment by goetzrobin** [comment]
No errors. Here is what I found so far:

By nesting the index.html inside the folder we create a child with the '' path, which is what we want.
However, the child itself has a loadChildren function (which only unpacks the module on runtime), which then creates our redirect. And it seems like loadChildren and the redirect don't work together.
 
<img width="1155" alt="Screenshot 2023-07-11 at 8 18 28 PM" src="https://github.com/analogjs/analog/assets/35136007/0ae35b8f-c341-4e42-b187-3140b4bbfa81">

**Comment by goetzrobin** [comment]
@brandonroberts I added e2e tests in the linked PR that displays the "issue".

I think the problem is that currently we only "look into the file" inside the loadChildren function.
With redirect we would need to do this during the creation of the routes so we know that inside the index.page.ts
is actually a redirect, which cannot be nested inside a loadChildren. I hope that makes sense.

**Comment by markostanimirovic** [comment]
Hey 👋 

For the following routes config:

```ts
export const routes: Route[] = [
  {
    path: 'locations',
    children: () => [
      { path: '', redirectTo: 'new-york', pathMatch: 'full' },
      { path: 'new-york', component: NewYorkComponent },
      { path: 'belgrade', component: BelgradeComponent },
    ],
  }
];
```

navigating to `/locations` will redirect to `/locations/new-york`. However, for the following config:

```ts
export const routes: Route[] = [
  {
    path: 'locations',
    loadChildren: () => [
      { path: '', loadChildren: () => [{ path: '', redirectTo: 'new-york', pathMatch: 'full' }] },
      { path: 'new-york', component: NewYorkComponent },
      { path: 'belgrade', component: BelgradeComponent },
    ],
  }
];
```

redirection won't happen when navigating to `/locations`. Also, there is no error.

> ⚠️ The same will happen if we replace `loadChildren` with `children`.

---

I think the best would be to check with the Angular team instead of finding workarounds on the Analog side because accessing the page files content during the routes creation phase to detect redirects will break the lazy loading of the page files.

For now, we can use absolute paths for redirections:

```
/pages
  /locations
    index.page.ts
    new-york.page.ts
    belgrade.page.ts
  locations.page.ts
```

`/pages/locations/index.page.ts` content:

```ts
export const routeMeta: RouteMeta = {
  // this works
  redirectTo: '/locations/new-york',
  pathMatch: 'full',
};
```

---

By the way, if the Angular team implements [`loadConfig` feature](https://github.com/angular/angular/issues/50432), it will most likely solve this issue.

**Comment by goetzrobin** [comment]
Thanks @markostanimirovic!! 👍  Using the absolute path works like a charm!
I can add a section to the documentation for that and while I am at it I could work on this if you want me to: https://github.com/analogjs/analog/issues/449

**Comment by markostanimirovic** [comment]
I plan to work on #449 this or next week, but if you already started working on it, let me know 🤘

**Comment by goetzrobin** [comment]
> I plan to work on #449 this or next week, but if you already started working on it, let me know 🤘

I’ll hold off then as I haven’t started yet! If you want you can use the same branch where I added a e2e test, if not I can also close the PR and delete the branch.

**Comment by atscott** [comment]
Hi, is there's any reason the routes can't be structured like this instead?


```
export const routes: Route[] = [
  {
    path: 'documentation',
    redirectTo: 'documentation/introduction',
    pathMatch: 'full',
  },
  {
    path: 'documentation',
    children: [{ path: 'introduction', component: Intro }],
  },
];
```

stackblitz example showing the working redirect: https://stackblitz.com/edit/stackblitz-starters-bxksk5
