### ISSUE TITLE
[REFACTOR]: Move plugins into separate files

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#54]
Right now there's 2 plugins

- A plugin for transforming files
  -   This plugin also handles deps optimization
- A build-only plugin for optimizing

Suggest splitting these into 3 plugins in separate files and using the plugin entry point to pass them the necessary options

- Deps optimizer
- Transform
- Build optimizer

**Comment by sumitparakh** [comment]
Can I take this up @brandonroberts ?

**Comment by brandonroberts** [comment]
@sumitparakh I already have some work in progress here, thanks.
