### ISSUE TITLE
Attempting to query GraphQL during prerender causes build to fail silently

### ISSUE THREAD

**Issue by leonsenft** [analogjs/analog#550]
### Please provide the environment you discovered this bug in.

- macoOS: Ventura 13.4.1
- Node: v20.4.0
- NPM: 9.7.2

### Which area/package is the issue in?

Don't know / other

### Description

# Reproduction

## Setup

Clone https://github.com/leonsenft/wfps-analog/tree/ssg-dynamic-content

You'll need a repo with a GitHub app. Use that to generate the necessary fields and put them in `.env` at the root of the project:

```
VITE_GITHUB_REPO_OWNER=<owner>
VITE_GITHUB_REPO_NAME=<name>

VITE_GITHUB_CLIENT_ID="Client ID"
VITE_GITHUB_APP_ID="App ID"
VITE_GITHUB_INSTALLATION_ID="Installation id for this repo"
VITE_GITHUB_CLIENT_SECRET="Client secret"
```

The full steps for that are here: https://github.com/frigus02/wfps2023-starter.

Alternatively if you want to replace the GraphQL query in the `AboutComponent` with something that doesn't require a GitHub app to authenticate you might be able to still reproduce the issue.

## Verify the app works in dev

```
npm start
```

Click the `About` link and verify the page loads and the query succeeds. 

# Issue

Attempting to build for release fails silently when it gets to prerendering `/about`. The build completes with exit code 0 and no error message. This is the output I see:

```
$ npm run build

> analog-starter@0.0.0 build
> ng build

vite v4.4.5 building for production...
✓ 426 modules transformed.
dist/client/index.html                             1.75 kB │ gzip:  1.31 kB
dist/client/assets/index-f18671ce.css              8.21 kB │ gzip:  2.51 kB
dist/client/assets/index.page-06f0bd20.js          1.40 kB │ gzip:  0.80 kB
dist/client/assets/index.page-feae4a65.js          1.41 kB │ gzip:  0.83 kB
dist/client/assets/defineProperty-cf0dde64.js      1.48 kB │ gzip:  0.65 kB
dist/client/assets/index.page-f9b6154e.js          2.11 kB │ gzip:  1.00 kB
dist/client/assets/analogjs-content-ecd3868e.js  135.09 kB │ gzip: 43.67 kB
dist/client/assets/github.service-e16d2e75.js    196.77 kB │ gzip: 48.59 kB
dist/client/assets/index-b1bed47c.js             275.67 kB │ gzip: 86.90 kB
Building SSR application...
✓ built in 5.20s
vite v4.4.5 building SSR bundle for production...
✓ 27 modules transformed.
dist/ssr/assets/index.page-0c3e41ef.mjs            2.90 kB
dist/ssr/assets/index.page-acee71fa.mjs            3.05 kB
dist/ssr/assets/index.page-d1d57b6c.mjs            3.39 kB
dist/ssr/assets/github.service-4cd70bbe.mjs        8.95 kB
dist/ssr/assets/analogjs-content-064b5f78.mjs     16.77 kB
dist/ssr/main.server.mjs                       1,345.18 kB
✓ built in 5.66s
Building Server...
✔ Generated public dist/analog/public                                                                            nitro 1:46:36 PM
ℹ Initializing prerenderer                                                                                       nitro 1:46:36 PM
ℹ Prerendering 2 routes                                                                                          nitro 1:46:39 PM
  ├─ / (4ms)                                                                                                      nitro 1:46:39 PM
github.getAbout()
onInit  null
 ->  {
  description: 'Web Framework Perspective Summit 2023 - Analog',
  url: 'https://github.com/leonsenft/wfps-analog'
}

$
```

Note that `onDestroy` is never called for the `AboutComponent` either.

### Please provide the exception or error you saw

```true
The lack of error is the problem.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
I think this is related to https://github.com/analogjs/analog/issues/468

**Comment by leonsenft** [comment]
> I think this is related to #468

I'm not sure. It looks like from the error message in that issue that the network request in question fails? I was able to verify that my GraphQL request completes successfully with the expected data while debugging.

**Comment by goetzrobin** [comment]
Interesting! I might have misunderstood. Your graphgl backend is 3rd party?

**Comment by leonsenft** [comment]
The app uses https://www.npmjs.com/package/octokit to query the GitHub GraphQL API. You can see the implementation here: https://github.com/leonsenft/wfps-analog/blob/ssg-dynamic-content/src/app/lib/github.service.ts.

**Comment by brandonroberts** [comment]
This should be resolved. Feel free to reopen if not
