### ISSUE TITLE
Feature: Add schematics to convert an angular project to AnalogJS project

### ISSUE THREAD

**Issue by torusservices** [analogjs/analog#554]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

As a beginner developer I would like to convert an existing Angular project such as a fresh install of angular to analogJS via use of a schematic such as ng add @analogjs

maybe even some questions to set it up to work with firebase hosting out of the box.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by santoshyadavdev** [comment]
Hey @brandonroberts, 

Is this still open? Let me know I can work on it.
