### ISSUE TITLE
Mermaid files are bundled even if mermaid is not used

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#560]
### Please provide the environment you discovered this bug in.

Support for mermaidjs was added in https://github.com/analogjs/analog/pull/555. This results in the mermaid js files being bundled even if you don't have it enabled.

### Which area/package is the issue in?

content

### Description

1. Clone this repo
2. Install the dependencies (pnpm i)
3. Go into the blog-app app.config.ts and disable mermaid
4. Build the blog app (nx build blog-app)
5. Notice all the mermaidjs files are still bundled

Workaround to exclude mermaid from the build
1. In the vite.config.ts, add `build.rollupOptions.exclude` set to `['mermaid']`
2. Build the blog app (nx build blog-app)
3. Notice none of the mermaidjs files are bundled

### Other information

Maybe we can put this in the docs @JeanMeche?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by JeanMeche** [comment]
Good catch @brandonroberts, I'm looking into making mermaid tree shakable (cf this commit https://github.com/analogjs/analog/compare/main...JeanMeche:analog:chore/mermaid-tree-shaking). 

But I doesn't work as expected. Are there some specificities about tree shaking with Analog ?

**Comment by brandonroberts** [comment]
Nothing specific being done here that we've built in. I think it's similar to the Angular Router, where instead of: 

```ts
provideContent(withMarkdownRenderer({ withMermaid: true }))
```

which won't be tree-shaken because its still referenced internally, It has to use something similar to that builder pattern:

```ts
provideContent(
  withMarkdownRenderer(),
  withMermaid() // <- loads mermaid
)
```
