### ISSUE TITLE
Feature: generate page components

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#565]
### Which scope/s are relevant/related to the feature request?

nx-plugin

### Information

This feature would add the ability to generate pages. It would support Nx Generators and Angular CLI schematics.

Some examples

ng g page about -> src/app/pages/about.page.ts

ng g page blog/post -> src/app/pages/blog/post.page.ts

ng g page products/[products] -> src/app/pages/products/[products].page.ts

ng g blog -> 
  src/app/content/my-first-post.md
  src/app/pages/blog.page.ts -> blog layout page
  src/app/pages/blog/[slug].page.ts -> blog post page
  src/app/pages/blog/index.page.ts -> blog list page

ng g post my-second-post -> src/content/my-second-post.md

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by luishcastroc** [comment]
I Can take a look ok this one to try to make it happen, should we setup expectations? Or with the examples in the issue is ok 😀

**Comment by brandonroberts** [comment]
The examples are good. We can break them up into just doing the page generator first.

**Comment by luishcastroc** [comment]
i'll send the first draft soon for analysis (as needed) @brandonroberts can you please assign the issue to me?
