### ISSUE TITLE
Support LightningCSS + TailwindCSS in Nx repo

### ISSUE THREAD

**Issue by benpsnyder** [analogjs/analog#583]
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

Are either of these implementations possible?
https://lightningcss.dev/docs.html#with-vite
https://vitejs.dev/config/shared-options.html#css-lightningcss

tried 
```
  plugins: [
    lightningcss({
      browserslist: '>= 0.25%',
    }),
  ],
```

and
```
  css: {
    transformer: 'lightningcss',
  },
```

Doesn't work with `tailwind.config.js` and `postcss.config.js` in the project root
![image](https://github.com/analogjs/analog/assets/707567/0831b351-bb78-42a2-b62c-062367bf5d62)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Don't see a reason this shouldn't work. I tried a similar setup with Vite 4.4.x and transformer: 'lightningcss' without the @apply and it worked correctly.

**Comment by brandonroberts** [comment]
Looks like Tailwind and Lightning CSS don't work together at the moment due to the PostCSS requirement for Tailwind. 

There's DownwindCSS which seems to be the equivalent.

**Comment by benpsnyder** [comment]
> Looks like Tailwind and Lightning CSS don't work together at the moment due to the PostCSS requirement for Tailwind.
> 
> There's DownwindCSS which seems to be the equivalent.

I am stripping out configuration right now in one of my projects and using tailwindcss@insiders and will post back if I have success with it.

**Comment by brandonroberts** [comment]
Will revisit when Tailwind lands v4 with support without using postcss
