### ISSUE TITLE
home (/) route doesn't prerender

### ISSUE THREAD

**Issue by stewones** [analogjs/analog#584]
### Please provide the environment you discovered this bug in.

I've created a new project with pnpx analog and just added the static option in vite.config.

when running nx build it doesn't prerender the home route as you see in dist/analog/public/index.html

though other static pages renders ok

repro
https://github.com/stewones/analog-home-render-issue

### Which area/package is the issue in?

Don't know / other

### Description

Idk

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is a known issue because of the index.html in the client assets, which gets used by Nitro during pre-rendering. 


Try adding this to the `nitro` object `serveStatic: false`

```ts
analog({
  nitro: {
    serveStatic: false
  }
})
```

**Comment by stewones** [comment]
yup it worked!
Thanks my man!
