### ISSUE TITLE
Feature: disable serving static assets by default

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#585]
### Which scope/s are relevant/related to the feature request?

vite-plugin-nitro

### Information

One issue we keep coming across is the / route not being pre-rendered. This is because there is an index.html in the client build, and Nitro uses this for serving when pre-rendering.

The workaround is to set `serveStatic: false` in the Nitro config.

This change would set the flag to false by default, as normal assets would be published to the deployment providers CDN, and not served through the Nitro server.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
I can take this @brandonroberts

**Comment by goetzrobin** [comment]
Then I cannot take this 😄 Thanks for pointing that out!

**Comment by geromegrignon** [comment]
It might not fit all use cases but I'm mitigating it currently by setting `min-height: 100vh` on the router-outlet as a workaround it really impacts the CLS score.

**Comment by brandonroberts** [comment]
One solution is to delete the `index.html` at the root of the `/` route is included in the pre-rendered routes array, as we inline the contents of the `index.html` before pre-rendering.

Then we would render the index.html in the public assets directory.

**Comment by brandonroberts** [comment]
This fix has been released in version `0.2.7`
