### ISSUE TITLE
Docs: Add more documentation on creating API routes

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#599]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

The docs are pretty limited on what you can do with API routes.

- API routes are file-based and support reload on changes
- API routes support static paths, dynamic params, and catch-all routes
- API routes support GET/POST/PUT/PATCH and more requests

Some examples in the Nitro docs

https://nitro.unjs.io/guide/routing#filesystem-routing

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by luishcastroc** [comment]
> I can take it

hi @deepakrudrapaul are you working on this? if not i might have the time to put something together

**Comment by deepakrudrapaul** [comment]
Hi @luishcastroc, yes i am working on this
