### ISSUE TITLE
Docs: Add documentation for using mermaid diagrams

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#609]
### Which scope/s are relevant/related to the feature request?

content

### Information

The content package supports using mermaid diagrams in markdown content. To enable it, using the `loadMermaid` config property with a callback function to load the package

```ts
// app.config.ts
import { provideHttpClient } from '@angular/common/http';
import { ApplicationConfig } from '@angular/core';
import { provideClientHydration } from '@angular/platform-browser';
import { provideFileRouter } from '@analogjs/router';
import { provideContent, withMarkdownRenderer } from '@analogjs/content';

export const appConfig: ApplicationConfig = {
  providers: [
    provideFileRouter(),
    provideHttpClient(),
    provideClientHydration(),
    provideContent(
      withMarkdownRenderer({
        loadMermaid: () => import('mermaid')
      })
    )
  ],
};
```

This could be a separate guide with a screenshot of a page with a diagram

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by choyiny** [comment]
I'd like to take this on!

**Comment by brandonroberts** [comment]
Thanks!

**Comment by JeanMeche** [comment]
Just a note, I've lost over an hour to understand why this didn't worked for me to display mermaids charts. 

`loadMermaid` registers the `MERMAID_IMPORT_TOKEN` that is only used by the `analog-markdown` component. 

If you don't use `<analog-markdown />` this won't work 😁

PS: I've added on my todolist to provide a docs page.
