### ISSUE TITLE
NPM build error

### ISSUE THREAD

**Issue by seanbh** [analogjs/analog#611]
### Please provide the environment you discovered this bug in.

PowerShell 7, node 18.13.0, npm 9.8.1.

### Which area/package is the issue in?

create-analog

### Description

`npm run build` fails when I add the first prerender route other than '/'.

```
plugins: [
    analog({
      prerender: {
        routes: async () => ['/', '/about'],
      },
    }),
],
```

I have a src/app/pages/about.page.ts file, that I copied from the docs.

Note than `pnpm` works fine.

### Please provide the exception or error you saw

```true
ERROR Error: Uncaught (in promise): Error: NG04002
Error: NG04002
    at Recognizer.noMatchError (file:///C:/code/demo/analog/npm-unchanged/dist/ssr/main.server.mjs:38000:12)
    at file:///C:/code/demo/analog/npm-unchanged/dist/ssr/main.server.mjs:38011:20
    at C:\code\demo\analog\npm-unchanged\node_modules\rxjs\dist\cjs\internal\operators\catchError.js:13:51
.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
@QuantariusRay has a Windows machine. Will you take a look?

**Comment by QuantariusRay** [comment]
Yes sir. I will do that now that I'm settled at the new place 👍

**Comment by brandonroberts** [comment]
Windows support is improved with Analog 1.0.2
