### ISSUE TITLE
Feature: add snapshot support for Vitest

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#613]
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

Vitest supports snapshot testing, but doesn't know how to handle Angular testing fixtures. Jest has snapshot serializers. Something similar should be implemented for Vitest support.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Docs on serializers https://vitest.dev/guide/snapshot.html#custom-serializer

**Comment by Tenessy** [comment]
@brandonroberts  I can take this task

**Comment by brandonroberts** [comment]
Thanks @Tenessy!

**Comment by Tenessy** [comment]
Hello @brandonroberts , I have an issue to test cause `**TestBed.createComponent**` make an error when i'am starting `pnpm test` `Error: NG0200: Circular dependency in DI detected for TestComponentRenderer. Find more at https://angular.io/errors/NG0200
        ❯ throwCyclicDependencyError ../../node_modules/packages/core/src/render3/errors_di.ts:20:9
        ❯ R3Injector.hydrate ../../node_modules/packages/core/src/di/r3_injector.ts:415:7
        ❯ R3Injector.get ../../node_modules/packages/core/src/di/r3_injector.ts:282:23
        ❯ TestBedImpl.inject ../../node_modules/packages/core/testing/src/test_bed.ts:520:48
        ❯ TestBedImpl.tearDownTestingModule ../../node_modules/packages/core/testing/src/test_bed.ts:728:31
        ❯ TestBedImpl.resetTestingModule ../../node_modules/packages/core/testing/src/test_bed.ts:454:16
        ❯ ../../node_modules/packages/core/testing/src/test_hooks.ts:34:15
        ❯ _ZoneDelegate.invoke ../../node_modules/.pnpm/zone.js@0.13.3/node_modules/zone.js/fesm2015/zone.js:368:26
        ❯ ProxyZoneSpec.onInvoke ../../node_modules/.pnpm/zone.js@0.13.3/node_modules/zone.js/fesm2015/zone-testing.js:273:39
        ❯ _ZoneDelegate.invoke ../../node_modules/.pnpm/zone.js@0.13.3/node_modules/zone.js/fesm2015/zone.js:367:52`.

I add a test in **test.setup-ts** file inside **vite-plugin-angular** folder follow this implementation `import '../setup-vitest';
import '@angular/compiler';

import { describe, it, expect, beforeEach } from 'vitest';
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

/**
 * Initialize TestBed for all tests inside of vite-plugin-angular
 */
import { ComponentFixture, TestBed, getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

describe('Angular Fixture Snapshot', () => {
  @Component({
    selector: 'app-test',
    standalone: true,
    imports: [RouterOutlet],
    template: `
      <div class="container">
        <router-outlet></router-outlet>
      </div>
    `,
  })
  class TestComponent {}

  let fixture: ComponentFixture<TestComponent>;
  let component: TestComponent;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [TestComponent],
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(TestComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create fixture snapshot', () => {
    expect(fixture).toMatchSnapshot();
  });
});`
