### ISSUE TITLE
Docs: Algolia Search

### ISSUE THREAD

**Issue by kyjus25** [analogjs/analog#622]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

As Analog expands in features, it becomes increasingly beneficial to add a search box to the documentation website.

Docusaurus provides an [easy-to-implement](https://docusaurus.io/docs/search#using-algolia-docsearch)  integration with Algolia, which is free for open source projects.

I would be willing to put in a pull request once the Algolia account is created and any relevant keys are provided.

### Describe any alternatives/workarounds you're currently using

Navigate using the left sidebar as current, or implement other options of searching that Docusaurus provides out of the box.

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Cool, applied, and waiting on a response. I will update here when I hear something.

**Comment by brandonroberts** [comment]
Algolia request was approved!

**Comment by kyjus25** [comment]
@brandonroberts let's gooooo!!! Not sure what all needs configured on the Algolia side but if you've got the app ID and API key I can wire it up tomorrow. It says it is safe to commit it

**Comment by crutchcorn** [comment]
@brandonroberts any chance you'd be okay with sharing the app ID and API key? I'm happy to make a PR adding it :)

**Comment by brandonroberts** [comment]
Sure, here's the info.

appId: 8W3CAMYOQF,
apiKey: 650d723674c8cd38658add35fb9433e3,

**Comment by crutchcorn** [comment]
@brandonroberts I also need the `indexName` from Algolia 😅 I'll open a draft PR without that for now

**Comment by crutchcorn** [comment]
Oh, hmm... It seems like there's a permission error with `apiKey`:

```
"Index not allowed with this API key"
```

<img width="859" alt="image" src="https://github.com/analogjs/analog/assets/9100169/8ddeee7a-d1b4-4629-8588-15f9abbce778">

@brandonroberts let me DM you and see if I can help get this set up

**Comment by brandonroberts** [comment]
I've created the project on Algolia. Try this again and let me know.

**Comment by crutchcorn** [comment]
@brandonroberts I added a PR and I'm not getting errors anymore, but the indexing doesn't seem to have taken as I'm not getting any results

**Comment by dalenguyen** [comment]
Maybe because of this? 

<img width="976" alt="image" src="https://github.com/analogjs/analog/assets/14116156/b2274807-2039-4e3d-9b57-d21519c2bea4">

**Comment by brandonroberts** [comment]
Search is now working. Thanks everyone!
