### ISSUE TITLE
Transitive dependencies (from `@nx-plus/docusaurus`) cause setup to fail in node < 20

### ISSUE THREAD

**Issue by rlmestre** [analogjs/analog#626]
### Please provide the environment you discovered this bug in.

M1 Mac
node 16.17.x, 16.20.x, 18.13.x, 18.17.x

### Which area/package is the issue in?

Don't know / other

### Description

The project currently has the following dependency chain causing `pnpm install` to fail in node versions below 20: 

`@nx-plus/docusaurus@15.0.0-rc0` -> `@nrwl/workspace@15.9.4` -> `nx@15.9.4` -> `@yarnpkg/parsers@3.0.0-rc.48.1`

Nx 16+ fixed this by pinning the version: https://github.com/nrwl/nx/pull/17860. I can get around it locally by using `pnpm` overrides:
```json5
// package.json
{
  "pnpm": {
    "overrides": {
      "@yarnpkg/parsers": "@yarnpkg/parsers@3.0.0-rc.46"
    }
  }
}
```
In Node 20+ it works fine.

### Please provide the exception or error you saw

```
ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://registry.npmjs.org/@yarnpkg/parsers/-/parsers-3.0.0-rc.48.1.tgz": Error: Invalid checksum for TAR header at offset 208384. Expected 0, got 5578
```

### Other information

I'm not sure if this counts as a bug for this project but I thought I'd report it anyway for visibility and/or discussion. There is a PR to update `@nx-plus/docusaurus` to support Nx 16 (https://github.com/ZachJW34/nx-plus/pull/291) but there are no guarantees it'll be implemented.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by rlmestre** [comment]
@brandonroberts Can we remove this and call `docusaurus` directly from `nx:run-commands`? We are only using this dep for the executors, which don't add much on top.

**Comment by brandonroberts** [comment]
Yes that's fine if everything else works the same
