### ISSUE TITLE
Vercel Deploy not working

### ISSUE THREAD

**Issue by SleeplessFox** [analogjs/analog#628]
### Please provide the environment you discovered this bug in.

Clean Angular Analog Project.
Angular 16 

**package.json**

{
  "name": "name",
  "version": "0.0.0",
  "private": true,
  "engines": {
    "node": "^16.14.0 || >=18.10.0"
  },
  "scripts": {
    "dev": "ng serve",
    "ng": "ng",
    "start": "npm run dev",
    "build": "ng build",
    "watch": "ng build --watch",
    "test": "ng test",
    "generate-page": "ng g @analogjs/platform:page --project=/"
  },
  "dependencies": {
    "@analogjs/content": "^0.2.0-rc.4",
    "@analogjs/router": "^0.2.0-rc.4",
    "@angular/animations": "^16.1.0",
    "@angular/common": "^16.1.0",
    "@angular/compiler": "^16.1.0",
    "@angular/core": "^16.1.0",
    "@angular/forms": "^16.1.0",
    "@angular/platform-browser": "^16.1.0",
    "@angular/platform-browser-dynamic": "^16.1.0",
    "@angular/platform-server": "^16.1.0",
    "@angular/router": "^16.1.0",
    "@nx/angular": "^16.4.0",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.6",
    "front-matter": "^4.0.2",
    "marked": "^5.0.2",
    "marked-gfm-heading-id": "^3.0.4",
    "marked-highlight": "^2.0.1",
    "mermaid": "^10.2.4",
    "prismjs": "^1.29.0",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@analogjs/platform": "^0.2.0-rc.4",
    "@angular-devkit/build-angular": "^16.1.0",
    "@angular/cli": "^16.1.0",
    "@angular/compiler-cli": "^16.1.0",
    "@nx/vite": "^16.4.0",
    "autoprefixer": "^10.4.14",
    "jsdom": "^22.1.0",
    "nx": "^16.4.0",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.1",
    "typescript": "~5.0.2",
    "vite": "^4.4.8",
    "vitest": "^0.32.0"
  }
}

**vite.config.ts**

/// <reference types="vitest" />

import { defineConfig } from 'vite';
import analog from '@analogjs/platform';
import { AppVariables } from './app.variables';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  publicDir: 'src/assets',
  build: {
    target: ['es2020'],
  },
  resolve: {
    mainFields: ['module'],
  },
  plugins: [
    analog({
      nitro: {
        preset: 'vercel',
      },
      static: true,
      ssr: true,
      prerender: {
        routes: ['/', '/about', '/privacy', '/terms'],
        sitemap: {
          host: AppVariables.WEBSITE_URL,
        },
      },
    }),
  ],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['src/test.ts'],
    include: ['**/*.spec.ts'],
  },
  define: {
    'import.meta.vitest': mode !== 'production',
  },
}));
`

### Which area/package is the issue in?

Docs

### Description

As described in the Docs https://analogjs.org/docs/features/deployment/providers a vercel deployment is working out of the box. 

Unfortunately, it is not working. When I choose my Analog repo and deploy it on vercel I just get an 

`404: NOT_FOUND
Code: NOT_FOUND`

Website. 

Do I have to choose different Project Settings in Vercel because the default Angular settings are may not working?

**Build Command** : ng build
**Output Directory**: dist
**Install Command**: npm install
**Development Command**: ng serve

### Please provide the exception or error you saw

`404: NOT_FOUND
Code: NOT_FOUND`

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by Aru-Ku** [comment]
Hi @SleeplessFox 

The default project generated from analogjs works fine for me in vercel.
Both with default vite config & also with [Setting the Preset Manually](https://analogjs.org/docs/features/deployment/providers#setting-the-preset-manually) as mentioned in the documentation.

I haven't modified or set any settings in Vercel
![image](https://github.com/analogjs/analog/assets/47110396/ea534e84-a2d0-4d75-a54f-64c46341f0c9)

**Comment by brandonroberts** [comment]
That's correct. You don't need to override any settings when deploying to Vercel. Re-open this if you still have an issue
