### ISSUE TITLE
ISR for SSG routes?

### ISSUE THREAD

**Issue by omerman** [analogjs/analog#629]
### Which scope/s are relevant/related to the feature request?

router

### Information

Is it on the roadmap to add isr support?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is already supported through the `routeRules` in the `nitro` config object inside the `analog()` plugin.

We haven't wrapped it in a proper API yet. There are some docs here https://nitro.unjs.io/config#routerules

**Comment by brandonroberts** [comment]
Closing as a duplicate of #127
