### ISSUE TITLE
Feature: Support for Netlify preset in Nitro configuration

### ISSUE THREAD

**Issue by Aru-Ku** [analogjs/analog#631]
### Which scope/s are relevant/related to the feature request?

vite-plugin-nitro

### Information

The current configuration in `vite-plugin-nitro.ts` does not have support for a Netlify preset.

Although setting the preset to netlify, the build output directory are not changed as required. I would like to work on this new enhancement. This will make the possibility of zero-config deployment for Netlify.

Also, since nitro supports other presets, I would like to move the present preset to separate folder (like `src/libs/presets/vercel.ts` and `src/libs/presets/netlify.ts`) instead of all the logic being piled up in `vite-plugin-nitro.ts` file.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is similar to https://github.com/analogjs/analog/issues/492. @santoshyadavdev was working on documenting deploying to Netlify, but I don't know if he was working on the other part also.
