### ISSUE TITLE
feature: top level layout support

### ISSUE THREAD

**Issue by besimgurbuz** [analogjs/analog#632]
### Which scope/s are relevant/related to the feature request?

router

### Information

I think having a top level layout that stays on every page would be great. If it's supported by analogjs I couldn't find it from the documents. Same idea in SvelteKit is [`+layout.svelte`](https://kit.svelte.dev/docs/routing#layout) file in `src/routes` destination. 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @besimgurbuz. How is this different than wrapping the router-outlet in the AppComponent with a layout?

**Comment by besimgurbuz** [comment]
None. I totally forgot about the AppComponent while experimenting routes. Sorry for inconvenience.
