### ISSUE TITLE
Loading data as JSON files gzipped by the server crashes while server rendering

### ISSUE THREAD

**Issue by BenLune** [analogjs/analog#643]
### Please provide the environment you discovered this bug in.

```
"nx": "15.6.3",
"@analogjs/content": "^0.2.0",
"@analogjs/router": "^0.2.0",
```
On MacOS

### Which area/package is the issue in?

Don't know / other

### Description

I have a project where the data are loaded as static json files, hosted gzipped on S3.
I noticed that I had a strange behaviour where the state was missing data.
Trying to basically load a file, and console.log its result, I noticed that the file was well loaded by the browser version but was in error server-side.
We need to find a solution for the server to be able to manage this situation, as the browser does it.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Using `provideHttpClient(withFetch())` resolves this issue
