### ISSUE TITLE
Provide a way to generate a RSS xml

### ISSUE THREAD

**Issue by JeanMeche** [analogjs/analog#654]
### Which scope/s are relevant/related to the feature request?

content

### Information

Kind of "old-tech" but I know some still uses RSS to keep up-to-date the latest articles. 

Could be great addition to Analog as a blogging platform ! 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is already supported https://analogjs.org/docs/features/api/overview#defining-xml-content. Maybe it should be moved to the SSG section
