### ISSUE TITLE
Add @angular/platform-server/init to main.server.ts file

### ISSUE THREAD

**Issue by goetzrobin** [analogjs/analog#664]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Some libraries depend on DOM globals, which are not available without the following import:

```ts
import '@angular/platform-server/init';
```
What does it do?

From the docs:
Initializes the server environment for rendering an Angular application.
For example, it provides shims (such as DOM globals) for the server environment.
The import must come before any imports (direct or transitive) that rely on DOM built-ins being available.

I think we should add this as part of the create-analog tool and the Nx plugin.

### Describe any alternatives/workarounds you're currently using

Add it manually.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
👍
