### ISSUE TITLE
Angular template files not found while creating a new project with create-analog v.0.2.49

### ISSUE THREAD

**Issue by pratheeshrussell** [analogjs/analog#672]
### Please provide the environment you discovered this bug in.

OS: Ubuntu 20.04.6 LTS
Node: v18.17.1
NPM: 9.6.7 
(this issue should occur in other environments too)

### Which area/package is the issue in?

create-analog

### Description

When I run  

`npm create analog@latest`  

I get an error that package json is missing

### Please provide the exception or error you saw

```true
Scaffolding project in /home/analog/analog-demo/angular16-test...
Error: ENOENT: no such file or directory, open '/home/pratheesh/.npm/_npx/3aa11859d66e1790/node_modules/create-analog/template-angular-v16/package.json'
```

### Other information

I checked the code tab in npm and found that the template folders only had the Readme file for older versions other files were also present. This might be the reason 

https://www.npmjs.com/package/create-analog/v/0.2.49?activeTab=code

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Interesting. Published an updated version in `0.2.51` that includes the templates
