### ISSUE TITLE
docs: adding turkish language 

### ISSUE THREAD

**Issue by besimgurbuz** [analogjs/analog#673]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

I want to contribute to Analog. And I though adding turkish language would be a good start. What do you think @brandonroberts ?

### Describe any alternatives/workarounds you're currently using

N/A

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by Villanuevand** [comment]
@besimgurbuz that's definitely a great idea.... 
If you got any question, I can help you with it.

**Comment by besimgurbuz** [comment]
Great, I have good examples to start from (#671). I would love to get your help on review @Villanuevand.

**Comment by brandonroberts** [comment]
Thanks @besimgurbuz and @Villanuevand

**Comment by Villanuevand** [comment]
@besimgurbuz  thanks. Just ping me and I will check your work!
