### ISSUE TITLE
Docs: add documentation for snapshot testing with Vitest

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#683]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Add a section to the overview page https://analogjs.org/docs/features/testing/overview for running a snapshot test with an example.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Tenessy** [comment]
@brandonroberts You can assigned me on this task ;)

**Comment by santoshyadavdev** [comment]
Hey @Tenessy , let me know if you are planning to work on this, or I can take it as I have soem fee time 😃

**Comment by Tenessy** [comment]
Hey @santoshyadavdev, you can take this task if you want, i haven't time in this moment. Thanks ! :)
