### ISSUE TITLE
Docs: add documentation for server-side data fetching

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#684]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Server-side data fetching was introduced in https://github.com/analogjs/analog/pull/446

## Setup

1. An environment variable needs to be set for the server, using a `.env` file.

```sh
VITE_ANALOG_PLUGIN_BASE_URL=http://localhost:5173
```

This environment variable should be set also at build time for deployment.

## Usage

1. Create a `.server.ts` file alongside the `.page.ts` file that exports an async `load` function.

```ts
// src/app/pages/index.server.ts
import { PageServerLoad } from '@analogjs/router';

export const load = async ({
  params, // params/queryParams from the request 
  req, // H3 Request
  res, // H3 Response handler
  fetch, // internal fetch for direct API calls,
  event // full request event 
}: PageServerLoad) => {
  return {
    loaded: true,
  };
};
```

2. Use the `injectLoad` function in the component inside an injection context, and use the `load` function for type safety.

```ts
// src/app/pages/index.page.ts
import { Component } from '@angular/core';
import { LoadResult, injectLoad } from '@analogjs/router';

import { load } from './index.server'; // not included in client build

@Component({
  standalone: true,
  template: `
    <h2>Home</h2>

    Loaded: {{ data().loaded }}
  `,
})
export default class BlogComponent {
  // with route componentInputBinding enabled -> https://angular.io/api/router/withComponentInputBinding
  @Input() load(data: LoadResult<typeof load>) {
    console.log(data); // logs { loaded: true }
  }

  // with useLoad function
  data = toSignal(injectLoad<typeof load>(), { requireSync: true });
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by besimgurbuz** [comment]
I would love to add this feature into the docs. One question, is this should be under `Core Concepts > API Routes > Server-Side Data Fetching`? @brandonroberts

**Comment by brandonroberts** [comment]
Great @besimgurbuz. I think it should be its own section `Core Concepts > Data Fetching > Server-Side Data Fetching`. That way we can add different examples also

**Comment by besimgurbuz** [comment]
Hi again @brandonroberts, I came across a typo while reading the code. In the code the expected env variable is `VITE_ANALOG_PUBLIC_BASE_URL`. But you typed as `VITE_ANALOG_PLUGIN_BASE_URL` in this issue. I used `VITE_ANALOG_PUBLIC_BASE_URL` in the doc. 
![Screenshot 2023-10-05 at 00 39 34](https://github.com/analogjs/analog/assets/33575384/477f1373-9a5c-42ad-ba93-c2190ef94359)
