### ISSUE TITLE
[REPO]: Automate publishing of packages

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#69]
The Analog packages are versioned independently and this would automate the versioning and release of each package based on most recent commits.

Not sure if this would also include generating an updated changelog for each package. Ideally this could be triggered through a protected GitHub Action also

**Comment by mainawycliffe** [comment]
Can I take a look at this? By publishing you mean automated on release or tags or what do you have in mind?

**Comment by brandonroberts** [comment]
@nartc said he was going to take a look at this.

**Comment by mainawycliffe** [comment]
No worries, I will find something else to sink my teeth in

**Comment by nartc** [comment]
@mainawycliffe feel free to pick it up. I have been a bit busy lately.

**Comment by mainawycliffe** [comment]
@brandonroberts I will take care of this in the next few days

**Comment by brandonroberts** [comment]
@mainawycliffe ok cool. Let me know if you have any questions. We may be able to use the affected commands from Nx in some way.

**Comment by mainawycliffe** [comment]
I was just wondering, do we want to use releases or just push to master and publish a minor/path version for the time being

**Comment by mainawycliffe** [comment]
@brandonroberts I think I have come up with half decent solution for this, I will PR something over the weekend - semi-automated in that the releases have to made manually, but after that, a release is created per package and pushed to NPM. Do you want something like this or go fully automated?

**Comment by brandonroberts** [comment]
Semi-automated works for me to start
