### ISSUE TITLE
Missing "./rxjs-interop" specifier in "@angular/core" package [plugin vite:dep-pre-bundle]

### ISSUE THREAD

**Issue by 222dipa** [analogjs/analog#692]
### Please provide the environment you discovered this bug in.

node v18.18.0
npm v9.8.1

{
  "name": "analog-project",
  "version": "0.0.0",
  "private": true,
  "engines": {
    "node": "^16.14.0 || >=18.10.0"
  },
  "scripts": {
    "dev": "ng serve",
    "ng": "ng",
    "start": "npm run dev",
    "build": "ng build",
    "watch": "ng build --watch",
    "test": "ng test"
  },
  "dependencies": {
    "@analogjs/content": "^0.2.0",
    "@analogjs/router": "^0.2.0",
    "@angular/animations": "^15.0.0",
    "@angular/common": "^15.0.0",
    "@angular/compiler": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/platform-server": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@nrwl/angular": "^15.0.0",
    "front-matter": "^4.0.2",
    "marked": "^5.0.2",
    "mermaid": "^10.2.4",
    "prismjs": "^1.29.0",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@analogjs/platform": "0.1.0-beta.23",
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular/cli": "~15.0.0",
    "@angular/compiler-cli": "^15.0.0",
    "@nrwl/vite": "^15.0.0",
    "nx": "^15.7.0",
    "jsdom": "^20.0.0",
    "typescript": "~4.8.4",
    "vite": "^4.0.3",
    "vitest": "^0.25.8",
    "tailwindcss": "^3.3.1",
    "postcss": "^8.4.21",
    "autoprefixer": "^10.4.14"
  }
}

### Which area/package is the issue in?

create-analog

### Description

Steps:

- npm create analog@latest
- cd analog-project
- npm i
- npm run start

### Please provide the exception or error you saw

```true
npm run start

> analog-project@0.0.0 start
> npm run dev


> analog-project@0.0.0 dev
> ng serve



The '@analogjs/platform' successfully started.
The server endpoints are accessible under the "/api" path.
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
✘ [ERROR] Missing "./rxjs-interop" specifier in "@angular/core" package [plugin vite:dep-pre-bundle]

    node_modules/@analogjs/content/fesm2022/analogjs-content.mjs:21:35:
      21 │ import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/dipa/Desktop/analog-project/node_modules/vite/dist/node/chunks/dep-3bba9c7e.js:39961:19)
    at handlePlugins (/Users/dipa/Desktop/analog-project/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
You should consider using the Angular v16 template for a new project
