### ISSUE TITLE
unable to create a project

### ISSUE THREAD

**Issue by dev-rajat-bacancy** [analogjs/analog#703]
### Please provide the environment you discovered this bug in.

✘ [ERROR] Expected string in JSON but found "<<"

    ../../../../package.json:24:0:
      24 │ <<<<<<< Updated upstream

### Which area/package is the issue in?

create-analog

### Description

I create a project names as dummy installed npm then unable to execute.
you can the versions that I installed

![image](https://github.com/analogjs/analog/assets/144689525/92b425e8-7297-4e26-b7bf-3e82534ddc65)

![image](https://github.com/analogjs/analog/assets/144689525/300bba2b-c7aa-4503-b8cc-4c85332a47ab)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
@dev-rajat-bacancy I don't think this is related to Analog. That `package.json` looks to be outside of the project directory, which we have no control over. Check the contents of that `package.json`

**Comment by dev-rajat-bacancy** [comment]
@brandonroberts I uninstall the angular and installed it again. Now it's working fine. Might be there will be some issue from my end when I upgrade angular version.

Thanks again @brandonroberts
