### ISSUE TITLE
`Content-Type` header is missing in responses of starter project

### ISSUE THREAD

**Issue by alaendle** [analogjs/analog#712]
### Please provide the environment you discovered this bug in.

GitHub codespace on https://github.com/alaendle/meta-framework-playground/tree/eb34a638d2fe0430ad9ccb169b89182a65dd1d9c

### Which area/package is the issue in?

Don't know / other

### Description

Following https://analogjs.org/docs/getting-started#creating-a-new-application and directly starting via `npm install && npm run start` - `curl http://localhost:5173/ -v` shows that the response doesn't include a `Content-Type` header and browsers will display the response as plain text.

### Please provide the exception or error you saw

```true
curl http://localhost:5173/ -v
*   Trying 127.0.0.1:5173...
* connect to 127.0.0.1 port 5173 failed: Connection refused
*   Trying [::1]:5173...
* Connected to localhost (::1) port 5173 (#0)
> GET / HTTP/1.1
> Host: localhost:5173
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Date: Sun, 22 Oct 2023 08:19:18 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Content-Length: 2064
< 
<!DOCTYPE html><html lang="en"><head>
```

### Other information

Please let me know if I was unclear or if you need further information to track down the issue.

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by alaendle** [comment]
Maybe this is the line (L47) that misses the content-type?
https://github.com/analogjs/analog/blob/c59184ef5ebe42e6f1bd4a6b926861fb24025c40/packages/vite-plugin-nitro/src/lib/plugins/dev-server-plugin.ts#L40-L50

**Comment by brandonroberts** [comment]
Haven't had any issues so far, but seems like a reasonable fix
