### ISSUE TITLE
Supports for external assets

### ISSUE THREAD

**Issue by innoflash** [analogjs/analog#714]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

So in Angular we add styles and scripts in the angular JSON file.

How do we do it with AnalogJS?

<img width="520" alt="Screenshot 2023-10-22 at 19 26 32" src="https://github.com/analogjs/analog/assets/12772919/6c31d80b-5127-4b8f-835e-3c8d15897cdc">
<img width="616" alt="Screenshot 2023-10-22 at 19 26 44" src="https://github.com/analogjs/analog/assets/12772919/559ac555-728a-466f-aa97-e22a230f1a61">

### Describe any alternatives/workarounds you're currently using

Its a blocker for me for now :) 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is supported already, you just don't have to add them to the `angular.json` file.

They can be added directly in the `index.html`

Example: https://github.com/analogjs/analog/blob/main/apps/analog-app/index.html#L13

**Comment by innoflash** [comment]
Alright, thanks a lot
