### ISSUE TITLE
Nx 17: An unhandled exception occurred: Package "@nx/vite" has no builders defined.

### ISSUE THREAD

**Issue by BJWielink** [analogjs/analog#718]
### Please provide the environment you discovered this bug in.

I simply ran these commands:

```
pnpm create analog
pnpm i
pnpm run dev
```

After that I get the error: An unhandled exception occurred: Package "@nx/vite" has no builders defined.

In this morning these commands still worked.

### Which area/package is the issue in?

platform

### Description

I am unable to run a freshly created analog platform project.

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Package "@nx/vite" has no builders defined.
```

### Other information

I think it is because nx@angular17 is installed by the latest pnpm create, yet the actual angular version is 16.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Yea, this was a change in Nx with the support for Angular CLI builders. For now, you can downgrade the `@nx/vite` package version to `16.10.0`.

We'll replace the builder for Angular CLI workspaces soon.

**Comment by brandonroberts** [comment]
This is resolved in the latest release. You may still need to pin the `@nx/vite` package to `16.8.1`
