### ISSUE TITLE
[create analog]: analog is not working when use create analog command and angular 16

### ISSUE THREAD

**Issue by redfox-mx** [analogjs/analog#727]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/github/analogjs/analog/tree/main/packages/create-analog/template-angular-v16?file=vite.config.ts&preset=node

### Which area/package is the issue in?

create-analog

### Description

Create analog is not working currently for angular 16 and analog 0.2.x. Use given default example.

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Cannot read properties of undefined (reading 'executor')
See "C:\Users\new_m\AppData\Local\Temp\ng-BJZvlX\angular-errors.log" for further details.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This looks to be an outdated version. Try https://analogjs.org/new

**Comment by mariusbolik** [comment]
I had the same issue. I ran `yarn create analog` and chose Angular 16. First, `@analogjs/platform` was missing, and after installing id I got the error `An unhandled exception occurred: Cannot read properties of undefined (reading 'executor')`. I could not create a new analog.js project out of the box.

**Comment by brandonroberts** [comment]
@mariusbolik yes, that's a known issue with Nx. If you pin `@nx/vite` to `16.8.1` and install it should work correctly.
