### ISSUE TITLE
Docs: add example to API routes on accessing cookies

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#728]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

We added support for accessing the request event here. The PR has an example of how to access cookies in the server request.

https://github.com/analogjs/analog/pull/614

This example should be added to the docs in the API routes overview page.

https://github.com/analogjs/analog/blob/main/apps/docs-app/docs/features/api/overview.md

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by santoshyadavdev** [comment]
I will work on it
