### ISSUE TITLE
NgModules support

### ISSUE THREAD

**Issue by Antonytm** [analogjs/analog#763]
### Which scope/s are relevant/related to the feature request?

astro-angular

### Information

Documentation says:
> The Astro Angular integration only supports rendering standalone components:

Are there any plans to support `NgModule` sometime in the future?

And if I decide to add NgModules support, is there any technical limitation, why it can be impossible?

P.S. I understand that probably NgModules will be deprecated at some time, but my codebase heavily relies on it.

### Describe any alternatives/workarounds you're currently using

Migration component to standalone one by one.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by marcus-sa** [comment]
You can still import modules in standalone components..?

**Comment by Antonytm** [comment]
@marcus-sa 
Can you elaborate, on what do you mean under "you can import modules in standalone components", please?

I have dependency on 3rd party library: https://github.com/Sitecore/jss/tree/dev/packages/sitecore-jss-angular
If I try to use something from that library without modification, I get
`The directive, imported is not standalone. Did you forget to add the standalone: true flag?`
Or console exception if it is not a standalone component.

**Comment by marcus-sa** [comment]
> @marcus-sa Can you elaborate, on what do you mean under "you can import modules in standalone components", please?
> 
> I have dependency on 3rd party library: [Sitecore/jss@`dev`/packages/sitecore-jss-angular](https://github.com/Sitecore/jss/tree/dev/packages/sitecore-jss-angular?rgh-link-date=2023-11-21T11%3A51%3A38Z) If I try to use something from that library without modification, I get `The directive, imported is not standalone. Did you forget to add the standalone: true flag?` Or console exception if it is not a standalone component.

```ts
@Directive({
	selector: '[test-dir]',
})
class TestDirective {}

@NgModule({
  declarations: [TestDirective],
  exports: [TestDirective],
})
class TestModule {}


@Component({
	selector: 'test-cmp',
	standalone: true,
    imports: [TestModule],
    template: `<div [test-dir]></>div>`,
})
class TestComponent {}
```

**Comment by brandonroberts** [comment]
There are no plans to support NgModules as the primary import to use an Angular component in Astro. I tried this before standalone components were introduced and it was not worth the effort to use.

Consuming the `JssModule` in your standalone component is probably the best option that lib is migrated.
