### ISSUE TITLE
Exploring possibility of using analog for docs

### ISSUE THREAD

**Issue by santoshyadavdev** [analogjs/analog#776]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Currently we are using docusaurus for documentation, but analog has the capability for rendering markdown, how about exploring the possibility of using analog for documentation, and maybe in future we can provide an doc template similar to what astro did with starlight.

### Describe any alternatives/workarounds you're currently using

As of today there are 3 solutions docusaurus or starlight by astro

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by stewones** [comment]
I was just wondering the same.

**Comment by brandonroberts** [comment]
I thought I responded to this previously, but I think its a good idea. I'd like to explore rebuilding the docs with Analog now that the 1.0 is out
