### ISSUE TITLE
Vitest-only fails in existing project

### ISSUE THREAD

**Issue by rainerhahnekamp** [analogjs/analog#790]
### Please provide the environment you discovered this bug in.

Existing application: https://github.com/rainerhahnekamp/eternal/tree/vitest-main-testing-playwright

### Which area/package is the issue in?

vite-plugin-angular

### Description

I've installed Vitest into my Angular-CLI-based project as described here: https://dev.to/brandontroberts/faster-testing-with-angular-and-vitest-274n

```bash
npm install @analogjs/platform --save-dev
ng g @analogjs/platform:setup-vitest
```

Unfortunately, the test execution fails:

1. If I run `npx ng test` on my local machine, it stalls 
2. In GitHub Actions, `npx ng test` stops with error code 1: https://github.com/rainerhahnekamp/eternal/actions/runs/7161492548/job/19497170593#step:5:14
3. I have more success if I just run `npx vitest`. Unfortunately, I'm getting a NG0203 (missing injection context) for my test **holidays.component.spec.ts**. This test works in the jest version though. (branch main-testing-playwright).

Your help is very much appreciated.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @rainerhahnekamp. Figured out the first issue on why it stalls. Its because its missing `reporters` in the vite config.

```ts.diff
/// <reference types="vitest" />

import angular from '@analogjs/vite-plugin-angular';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    plugins: [angular()],
    test: {
      globals: true,
      environment: 'jsdom',
      setupFiles: ['src/test-setup.ts'],
      include: ['**/*.spec.ts'],
+     reporters: ['default'],
    },
    define: {
      'import.meta.vitest': mode !== 'production',
    },
  };
});
```

PR with the fix here: https://github.com/analogjs/analog/pull/791

Thanks for the repo. Will check on the other test failure

**Comment by brandonroberts** [comment]
@rainerhahnekamp figured out why the `holidays.component.spec.ts` was failing also

```ts.diff
import { fakeAsync, TestBed, waitForAsync } from '@angular/core/testing';
import {
  HttpTestingController,
  provideHttpClientTesting,
} from '@angular/common/http/testing';
import { HolidaysComponent } from './holidays.component';
import { provideState, provideStore } from '@ngrx/store';
import { provideEffects } from '@ngrx/effects';
import { holidaysFeature } from '../+state/holidays.reducer';
import { HolidaysEffects } from '../+state/holidays.effects';
import { Configuration } from '@app/shared/config';
import { createHolidays } from '@app/holidays/model';
import { provideHttpClient } from '@angular/common/http';
import { By } from '@angular/platform-browser';
+ import { provideRouter } from '@angular/router';
+ import { provideLocationMocks } from '@angular/common/testing';

describe('Holidays Component', () => {
  const setup = () =>
    TestBed.configureTestingModule({
      imports: [HolidaysComponent],
      providers: [
        provideStore(),
        provideState(holidaysFeature),
        provideEffects([HolidaysEffects]),
        provideHttpClient(),
        provideHttpClientTesting(),
+        provideRouter([]),
+        provideLocationMocks(),
        {
          provide: Configuration,
          useValue: {
            baseUrl: 'http://localhost:8080/',
          },
        },
      ],
    }).createComponent(HolidaysComponent);

  it('should instantiate', waitForAsync(() => {
    const fixture = setup();
    expect(fixture.componentInstance).toBeInstanceOf(HolidaysComponent);
  }));

  it('should show holiday cards', fakeAsync(() => {
    const fixture = setup();
+    fixture.detectChanges();
    const controller = TestBed.inject(HttpTestingController);
    const holidays = createHolidays({ title: 'Vienna' }, { title: 'London' });
    controller.expectOne((req) => !!req.url.match(/holiday/)).flush(holidays);
+    fixture.detectChanges();
    const cards = fixture.debugElement.queryAll(By.css('app-holiday-card'));
    expect(cards.length).toBe(2);
  }));
});
```

This test was slightly different before the Vitest changes from what I could tell also

**Comment by MarioGeier00** [comment]
Hello @brandonroberts,

using the following commands i am also unable to get vitest to work:

```shell
ng new --minimal
npm install @analogjs/platform --save-dev
ng g @analogjs/platform:setup-vitest
```

The first issue is that vitest@1.31.1 is being installed which does not exist. Either 0.31.1 or 1.3.1 exists.
After manually fixing the version, i get an error running `ng test`:

"@analogjs/vite-plugin-angular" resolved to an ESM file. ESM file cannot be loaded by `require`

Your help is very much appreciated.

**Comment by brandonroberts** [comment]
@MarioGeier00 yes, we'll need to adjust the schematic. If you rename the `vite.config.ts` to `vite.config.mts` it will load the Vite configuration as ESM and should help with that error

**Comment by brandonroberts** [comment]
The Vitest schematic has been adjusted for existing projects in 1.0.2. Closing as resolved for now
