### ISSUE TITLE
Install issues with Bun and Vite 5 / Vitest 1 in templates 

### ISSUE THREAD

**Issue by birkskyum** [analogjs/analog#795]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

When initiating a project using the templates (at least angular 17), I can't install the package.json because of incompatible package versions with vite/vitest/ and nx/vite.

There is a related upstream issue open here:
- https://github.com/nrwl/nx/issues/20722

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @birkskyum. I've reached out to the Nx team already, and they will work on support for Vitest 1.0 soon. In the meantime, newly generated apps with `npm create analog@latest` should have a `.npmrc`  at the root which allows peer dependencies to be installed outside of those defined ranges in the `@nx/vite` package.

.npmrc
```sh
legacy-peer-deps=true
```

Angular v17.1 should bump Vite up to 5.x also

The other option is to use `npm install --legacy-peer-deps`, which is similar to what's defined in the `.npmrc`

**Comment by birkskyum** [comment]
@brandonroberts , gotcha, thanks. I hit this because I tried to `create analog@latest` with bun, which problematically doesn't appear to respect the .npmrc yet.

**Comment by brandonroberts** [comment]
Oh, interesting. 

I think if you pin `Vitest` to `^0.34.4`, `@nx` packages to `~17.1.0`, and `Vite` to `4.5.1` that might allow you to install with bun without peer dependency issues.

Vitest 1.0 is mainly needed if you're using component harnesses

**Comment by birkskyum** [comment]
That sure does fix that specific issues.

**Comment by brandonroberts** [comment]
Ok cool. I think we'll update the current template to use those versions to decrease the `npm install` friction for new apps being generated with the v17/blog templates.

**Comment by brandonroberts** [comment]
The packages are aligned in the latest release of `create-analog`. The following now works without peer dependency installation issues.

```sh
npm create analog@latest analog-bun-install
cd analog-bun-install
bun install
bun run dev
```

**Comment by birkskyum** [comment]
- https://github.com/nrwl/nx/pull/20760

seems like this change is in the nx [17.2.5](https://github.com/nrwl/nx/releases/tag/17.2.5), so it's technically possible to bump the deps now.

**Comment by brandonroberts** [comment]
True, but the Angular CLI is still on 4.5.1 until 17.2 gets released which will cause peer dependency issues.

**Comment by Jordan-Hall** [comment]
> The packages are aligned in the latest release of `create-analog`. The following now works without peer dependency installation issues.
> 
> ```shell
> npm create analog@latest analog-bun-install
> cd analog-bun-install
> bun install
> bun run dev
> ```

Running bun run dev with dev is vite dev isn't running in Bun runtime. @brandonroberts  you need to use bun run --bun dev to use bun for the runtime otherwise it uses node.

**Comment by brandonroberts** [comment]
Yes, I know. There were still some compatibility issues running with the bun runtime, but its been a while since I checked it

**Comment by Jordan-Hall** [comment]
Fair enough sorry I was.following the thread and I thought you was saying bun working. Been considering pulling jn angular vite plugins for a pure bun solution

**Comment by brandonroberts** [comment]
Created a working solution with Bun runtime and the Vite CLI

https://github.com/brandonroberts/analog-bun-ssr-example
