### ISSUE TITLE
Crash if `//templateUrl: ""` comment line exists in `@Component()` on page copmponent

### ISSUE THREAD

**Issue by mirumirumi** [analogjs/analog#797]
### Please provide the environment you discovered this bug in.

I found a very strange bug. I was able to figure out how to reproduce it completely on my end, but could not reproduce it on StackBlitz.
I'm reporting this issue because the syntax that is causing the problem is Angular's, although I think the problem is probably related to the Vite area.
I have confirmed that it does not happen with Angular alone (even with `build-angular:browser-esbuild` build).

https://stackblitz.com/edit/github-ds5ida?file=src%2Fapp%2Fpages%2Findex.page.ts

### Which area/package is the issue in?

vite-plugin-angular

### Description

The problem is that inserting the comment `// templateUrl: ""` or `// templateUrl: ''` in the `@Component()` decorator that defines the page component causes the following error and crashes the application.
The crash will not occur if the comment is slightly different, as shown below.

### **Crash:**
![image](https://github.com/analogjs/analog/assets/88871226/58a2b7b5-9579-4bd5-ae47-df2b8e55b276)

### **No crash:**
![image](https://github.com/analogjs/analog/assets/88871226/8d66191f-4025-4c7f-b072-d2b986590f84)

This also occurred in a clean project immediately after `create-analog`.

- WSL 2
- Node 18.16.1
- I selected Angular 17

### Please provide the exception or error you saw

```true
2:59:37 PM [vite] Internal server error: Failed to resolve import "/home/mirumi/dev/my-project/src/app/pages" from "src/app/pages/index.page.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/mirumi/dev/my-project/src/app/pages/index.page.ts:1:1
  1  |  import { Component } from "@angular/core";
     |  ^
  2  |  import * as i0 from "@angular/core";
  3  |  export const routeMeta = {
      at formatError (file:///home/mirumi/dev/my-project/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44062:46)
      at TransformContext.error (file:///home/mirumi/dev/my-project/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
      at normalizeUrl (file:///home/mirumi/dev/my-project/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rlmestre** [comment]
I was looking into this and developed a fix. Will open a PR now
