### ISSUE TITLE
Support Windows path TemplateUrl and StyleUrl on Vitest

### ISSUE THREAD

**Issue by nemu69** [analogjs/analog#798]
### Please provide the environment you discovered this bug in.

Operating System: Windows

### Which area/package is the issue in?

vite-plugin-angular

### Description

There's a bug encountered when using Vitest with vite-plugin-analog-angular. The specific details of the bug are not fully described, but it seems related to file path handling.

Referencing a comment by Brandon in issue https://github.com/analogjs/analog/issues/688#issuecomment-1748963739, it's noted that he does not have access to a Windows machine, which might be relevant for replicating this bug.
![gde](https://github.com/analogjs/analog/assets/43633395/cd5d43f0-ae38-4549-aac6-9bdb0721a63a)

### Please provide the exception or error you saw

```sh
StyleUrl: Error: Failed to resolve import "C:********.Frontsrcappcoresharedcomponents  ogglemerging-letter-toggle.component.scss?inline" from "src\app\core\shared\components\toggle\merging-letter-toggle.component.ts". Does the file exist?

TemplateUrl: Error: Failed to resolve import "C:********.Frontsrcappapp.component.html?raw" from "src\app\app.component.ts". Does the file exist?
```

### Proposed Solution:
The issue might be resolved by modifying the way file paths are handled. Specifically, replacing double backslashes (\\) with single forward slashes (/) in the file path string.

e.g. : 
```ts
const templateUrlPath = (0, path_1.resolve)((0, path_1.dirname)(id), resolvedTemplatePath)
```
to
```ts
const templateUrlPath = ((0, path_1.resolve)((0, path_1.dirname)(id), resolvedTemplatePath)).replace(/\\/g, '/');
```

This change appears to resolve the issue.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @nemu69. Vite has a `normalizePath` function that can be imported and used here which has cross-platform support. Here's the original line

https://github.com/analogjs/analog/blob/main/packages/vite-plugin-angular/src/lib/component-resolvers.ts#L59

**Comment by nemu69** [comment]
Okay, great, I will use this for clarity.
