### ISSUE TITLE
Nx monorepo - vitest fails to recognize tests in src/**/*.spec.ts files

### ISSUE THREAD

**Issue by jeremyhofer** [analogjs/analog#801]
### Please provide the environment you discovered this bug in.

Can be recreated after installing analog within a Nx workspace.

Repo created from a fresh Nx workspace, new analog app installed, and a test file added at `analog-app/src/server/routes/v1/hello.spec.ts`: https://github.com/jeremyhofer/analog-nx-vitest-server-tests-not-found

### Which area/package is the issue in?

platform

### Description

When `spec.ts` files are created under the `src/server` directory of an analog application within a Nx monorepo the tests within the files are not recognized. The tests fail with the error `Error: No test suite found in file <file>`. Screenshot of this happening:
![1702586237](https://github.com/analogjs/analog/assets/17076628/4cbdfbee-2526-45e0-9a7f-9c149d549e4b)

Testing based on [the discussion in discord](https://discordapp.com/channels/994618831987290112/1184958601916317756) the following was discovered:
1. Fully commenting out the `analog()` plugin in `vite.config.ts` allows the tests to execute as expected
2. Adding `**/*.server.ts` to `tsconfig.spec.json` `include` array has no impact
3. Adding `**/*.server.ts` to the `include` array of the `test` configuration in `vite.config.ts` has no impact
4. Configuring the `analog` plugin with a tsconfig path for vite (`analog({ vite: { tsconfig: 'relative/path/from/root/to/tsconfig.spec.json' } })`) has no impact, neither when providing the path relative from root or simply as `tsconfig.spec.json`.
5. Still occurs when running `vitest` from within the application directory instead of using the Nx executor
6. Tests added under `src/server` in an analog app created with `npm create analog@latest` outside of a Nx monorepo run and work as expected
7. Not very scientific - quick diff of config files, tsconfigs, package versions, etc. don't show any major differences between an analog app in a Nx repo vs. the standalone app created
8. Choosing to use `tRPC` or not as part of the analog app in the Nx monorepo has no impact

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Found the issue. Its excluding them in the `tsconfig.json`

https://github.com/jeremyhofer/analog-nx-vitest-server-tests-not-found/blob/master/analog-app/tsconfig.json#L5

If you set the `exclude` to an empty array in the `tsconfig.spec.json`, they run correctly.

**Comment by jeremyhofer** [comment]
Yep, that is it!

I'll raise a PR and update the templates in nx-plugin this evening. Can close the issue after that.

Thanks as always for the support!

**Comment by jeremyhofer** [comment]
Actually, testing a bit further, realized the `exclude` in `tsconfig.json` was causing my issue with tsConfigPaths not being loaded/respected for tests as well. Changing `exclude` to an empty array in `tsconfig.json` resolves both the test issue and the paths issue.

Given `tsconfig.app.json` is set up with the proper `include` and `exclude` for the production app I don't think the `exclude` in the `tsconfig.json` is really needed. I'll double check other targets work as expected, but is there a reason you can think of to not change the `exclude` in `tsconfig.json` instead?

**Comment by brandonroberts** [comment]
My initial thought for putting it there was to further prevent server code from making it into client builds, but that's covered through a plugin. I think its reasonable to remove it from the `exclude` array.

**Comment by jeremyhofer** [comment]
:+1: great, that makes sense why it would have been there in the past. I'll raise a PR to update the templates. Looking, it'll make it a bit more consistent with standalone analog apps as there is not an `exclude` array defined - unless there's some bundling differences between the two setups?
