### ISSUE TITLE
Prerender content routes based on files in directory

### ISSUE THREAD

**Issue by d-koppenhagen** [analogjs/analog#820]
### Which scope/s are relevant/related to the feature request?

platform

### Information

As described in the [Docs](https://analogjs.org/docs/features/server/static-site-generation), static site generation is currently done by adding routes to the `prerender` config in `vite.config.ts` like this:

```ts
import { defineConfig } from 'vite';
import analog from '@analogjs/platform';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  plugins: [
    analog({
      static: true,
      prerender: {
        routes: async () => [
          '/',
          '/about',
          '/blog',
          '/blog/posts/2023-02-01-my-first-post',
        ],
      },
    }),
  ],
}));
```

To alway prerender new sites for e. g. new blog post articles, you have to remember to update this config to be sure the articles are pre-rendered.
A common use-case is to alway pre-render such kind of articles or to pre-render them when front-matter meta-data is defined.

I would suggest to allow adding directory configs to the array of pre-rendered routes which auto-magically prerenders new articles like this:

```ts
import { defineConfig } from 'vite';
import analog from '@analogjs/platform';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  plugins: [
    analog({
      static: true,
      prerender: {
        routes: async () => [
          '/',
          '/about',
          '/blog',
          // previeously
          '/blog/posts/2023-02-01-my-first-post',
          // new:
          {
            dir: '/blog/posts', // matches all routes created by file-based routing within // `src/content/blog/posts`
            filter: (metaData) => { // optional: allow to filter pre-rendered routes based on front-matter meta data
              return metaData.published !== 'false'
            }
          } 
        ],
      },
    }),
  ],
}));
```

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by ajitzero** [comment]
I was looking for this! I tried writing a function for this last night but haven't got it to work yet and didn't have time to look into it.

I am adding it here if it helps somehow:

<details><summary>Initial function for filtering drafts</summary>
<p>

```ts
import * as fs from 'fs';
import * as path from 'path';
import * as fm from 'front-matter';

function getPath(basePath: string, filePath: string): string {
  // https://github.com/JeanMeche/riegler.fr/blob/main/vite-prerender.utils.ts
  return `${basePath}${path.parse(filePath).name}`;
}

export function getContentUrls(options?: Partial<{
  basePath: string;
  skipDrafts: boolean;
}>): string[] {
  const {
    basePath = '/blog/',
    skipDrafts = true, /* isDevMode, from ENV */
  } = options;

  const filePaths = fs.readdirSync('./src/content');

  if (!skipDrafts) {
    return filePaths.map((filePath: string) => getPath(basePath, filePath));
  }

  return filePaths
    .map((filePath: string) => ({
      name: getPath(basePath, filePath),
      contents: fs.readFileSync(filePath, 'utf8'),
    }))
    .filter(file => {
      const frontmatter = fm(file.contents);
      return !frontmatter?.draft;
    })
    .map(file => file.name);
}
```

</p>
</details>

**Comment by brandonroberts** [comment]
@d-koppenhagen interesting! I like the idea in general, but the URL could be different than the `slug` defined in the frontmatter.

So instead of a `filter`, maybe it would a function that returns a `{ path: string } | false` or just `string | false`, with the string being the full URL path.

And also `contentDir` seems like a more appropriate name.


Another idea I've had altogether is to define these pre-rendered routes within the `.page.` or `.server` routes themselves. Not completely sure on what that looks like yet though, but `/blog/[slug].page.ts` defines an array of values for `[slug]`, and during pre-rendering, we collect all of them and use those as the routes.

**Comment by d-koppenhagen** [comment]
@ajitzero so far as a little helper snippet, I created a small pre-commit hook which is executed from my `package.json`:
https://github.com/d-koppenhagen/k9n.dev/blob/main/package.json#L24

**Comment by d-koppenhagen** [comment]
> @d-koppenhagen interesting! I like the idea in general, but the URL could be different than the slug defined in the frontmatter.

Ah, I wasn't aware of the fact the `slug` can be set in the frontmatter. Probably because I always included the slug as a convention in my content filenames.

> So instead of a filter, maybe it would a function that returns a { path: string } | false or just string | false, with the string being the full URL path.

I agree, this would be way more generic and flexible.

> And also contentDir seems like a more appropriate name.

totally!

> Another idea I've had altogether is to define these pre-rendered routes within the .page. or .server routes themselves. Not completely sure on what that looks like yet though, but /blog/[slug].page.ts defines an array of values for [slug], and during pre-rendering, we collect all of them and use those as the routes.

Yes that could also be an alternative approach. One thing I don't like about this one is, that it makes pre-rendered routes harder to find as some coming from here now and some are defined in the `vite.config.ts`. This will make it a bit confusing probably doesn't it?

**Comment by d-koppenhagen** [comment]
I created a Draft PR (Its not perfect yet but probably its a good base to discuss things @brandonroberts wdyt?
