### ISSUE TITLE
Incorrect coverage reports

### ISSUE THREAD

**Issue by jeremyhofer** [analogjs/analog#822]
### Please provide the environment you discovered this bug in.

Having issues getting StackBlitz to cooperate. Here's a repo that reproduces:

https://github.com/jeremyhofer/demo-analog-incorrect-test-coverage

For some reason `npm run test`, despite adding the `coverage: true` option to the `test` target in `angular.json` is not generating coverage. I think this may be a `@nx/vite` plugin executor thing with the version I'm testing in this repo. Due to this I am running tests via `npx vitest --coverage` in this reproduction. However, in my actual project I am running/generating coverage with `nx test <app>` with no impact.

### Which area/package is the issue in?

Don't know / other

### Description

Coverage reports generated as part of unit tests for any file in the analog `/src` directory have incorrect coverage reports.

An example visual of the coverage reported for the `app.component.ts` that is scaffolded with a new analog app, with an untested function added to the component:
![1703901542](https://github.com/analogjs/analog/assets/17076628/f480619d-9de2-4b3f-a088-04c8337c67d5)
![1703901770](https://github.com/analogjs/analog/assets/17076628/241823cc-2017-4852-bec1-72a8fdd6b6e9)

Incorrect coverage reports such as this are being generated for any and all files I try. Angular components, pages, server routes, etc. Each one will report inaccurate coverage results.

I'm not sure exactly where in the stack the source mapping may be getting lost when testing. I'd be happy to dig into this a fair bit if I can be pointed in a starting direction.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
I think this is a sourcemap issue also. There's an open issue here #86
