### ISSUE TITLE
Remove script from static build

### ISSUE THREAD

**Issue by anuj9196** [analogjs/analog#825]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

My application is just a static website to render content without any js based functionality. The static build generated loads multiple js files in the browser, which does not seems to be useful.

<img width="427" alt="Screenshot 2024-01-02 at 09 16 23" src="https://github.com/analogjs/analog/assets/6560085/37d9237f-0f8f-4d18-9267-ef67d5707dae">

I want my application to be free from js dependencies thus want these files to be removed from the static build.

The `vite.config.ts` file is
```typescript
export default defineConfig(({ mode }) => ({
  publicDir: 'src/assets',
  build: {
    target: ['es2020'],
  },
  resolve: {
    mainFields: ['module'],
  },
  plugins: [
    analog({
      static: true,
      prerender: {
        routes: async () => [
          '/',
          '/about',
          '/pricing/',
          '/contact',
        ],
      }
    }),
    angular({
      inlineStylesExtension: 'scss',
    }),
  ],
}
```

### Describe any alternatives/workarounds you're currently using

Not using any alternative

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [X] No

**Comment by brandonroberts** [comment]
You can use post-rendering hooks to remove the script tags from the generated HTML, and delete the JS files with a post-build step.

https://analogjs.org/docs/features/server/static-site-generation#post-rendering-hooks
