### ISSUE TITLE
Provide AsciiDoc Renderer

### ISSUE THREAD

**Issue by d-koppenhagen** [analogjs/analog#827]
### Which scope/s are relevant/related to the feature request?

content

### Information

It would be nice to support also AsciiDoc (*.adoc) as Markdown alternative.

similar to `withMarkdownRenderer()` it could be named `withAsciiDocRenderer()`.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Haven't seen this one as much. Does this need to be built-in?

**Comment by d-koppenhagen** [comment]
Probably you are right and it could also be an extension living somewhere else.
