### ISSUE TITLE
[Nx][beta 2] 403 errors on main.ts and styles.css

### ISSUE THREAD

**Issue by BenLune** [analogjs/analog#828]
### Please provide the environment you discovered this bug in.

```
"@analogjs/content": "1.0.0-beta.2"
"nx": "17.2.8"
```

### Which area/package is the issue in?

vite-plugin-angular

### Description

Using serve command, I have 403 errors in browser's console.
In Webstorm Terminal, I have those warning message : 

- The request url "/Users/xxxxxx/WebstormProjects/nx-solomco/apps/solomco-web/src/styles.css" is outside of Vite serving allow list.
- The request url "/Users/xxxxxx/WebstormProjects/nx-solomco/apps/solomco-web/src/main.ts" is outside of Vite serving allow list.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is resolved in the 1.0 migration guide
