### ISSUE TITLE
Feat: Single package 

### ISSUE THREAD

**Issue by luisbytes** [analogjs/analog#832]
### Which scope/s are relevant/related to the feature request?

platform

### Information

It would be interesting if instead of having all those packages in "dependencies" and "devDependencies", they are all packaged in a single package like nuxt and next, for example typescript, vite, nx and many more.

This would make the json package much cleaner and easier to update, it might also be interesting to create analog.config.ts.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @luisbytes but I think this creates more friction than improving the experience. It also makes manually upgrading more difficult with peer dependency issues.
