### ISSUE TITLE
withMarkdownRenderer: allow to configure / pass extensions 

### ISSUE THREAD

**Issue by d-koppenhagen** [analogjs/analog#835]
### Which scope/s are relevant/related to the feature request?

content

### Information

Under the hood, the lib marked is used to render the markdown.
It's configured with common plugins e. g. for syntax highlighting or adding `id`'s to the headlines by default.
However, marked allows to pass more extensions or custom extensions like this:

```ts
marked.use(
  // ... 
  // common extensions like  gfmHeadingId or markedHighlight
  // ...
  {
    hooks: {
      postprocess(html) {
        const headings = getHeadingList();
        return `<ul id="table-of-contents">
  ${headings.map(({id, text, level}) => `<li><a href="#${id}" class="h${level}">${text}</a></li>`)}
        </ul>${html}`;
      }
    },
  }
);
```

My suggestion would be to expose an extension point within `withMarkdownRenderer`. So the interface could look like this afterwards:

```ts
export interface MarkdownRendererOptions {
  loadMermaid?: () => Promise<typeof import('mermaid')>;
  extensions: marked.MarkedExtension[]
}
```

In the end, a new extension can be passed like this:

```ts
const tocExtension = {
  hooks: {
    postprocess(html) {
      const headings = getHeadingList();
      return `<ul id="table-of-contents">
  ${headings.map(({id, text, level}) => `<li><a href="#${id}" class="h${level}">${text}</a></li>`)}
      </ul>${html}`;
     }
  },
}
export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(),
    provideClientHydration(),
    provideContent(
      withMarkdownRenderer({
        extensions: [tocExtension]
      })
    ),
    provideFileRouter(
      withInMemoryScrolling({ anchorScrolling: 'enabled' }),
      withEnabledBlockingInitialNavigation()
    ),
  ],
};
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Are these hooks the only extension points?

**Comment by d-koppenhagen** [comment]
According to the docs, objects passed to `use()` seems to be called extension but could include common options (such as the mentioned ones by @luishcastroc) as well.

So in my opinion it's the most flexible way to configure marked.

https://marked.js.org/using_advanced#options

**Comment by brandonroberts** [comment]
Closing this as we're moving content rendering to build time 

https://github.com/analogjs/analog/pull/1174
