### ISSUE TITLE
This project SCREAMS: leave us alone, go use React or Qwik or whatever else

### ISSUE THREAD

**Issue by cgarbacea** [analogjs/analog#840]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

The docs and samples are bad practice overall. Even the docs site is made with react components.

### Describe any alternatives/workarounds you're currently using

- maybe separeate html templates and style from .ts files in your sample code.
- use analogjs for the docs site

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by luishcastroc** [comment]
When the docs were created, Analog was still in its early stages, so we used current tools dedicated to that matter. Also, could you please elaborate on why single file components are considered a bad practice? One of the key features of Analog is its flexibility in allowing you to use any Angular pattern you prefer.

**Comment by cgarbacea** [comment]
you could have used grow.io like before and maybe learn something in the process... like enable content from yaml :) not only md.
I want to see you using template in a medium/large project and also have styles in the same files or have your new/entry devs try to learn Angular or Analog and believe that this is the proper way... cause this what they see and learn from your docs

**Comment by luishcastroc** [comment]
Appreciate the suggestion but we will move on from this discussion if you have any further concern please be sure to use our discord
