### ISSUE TITLE
Vitest: TypeError: `it.skip` is not a function

### ISSUE THREAD

**Issue by Yberion** [analogjs/analog#841]
### Please provide the environment you discovered this bug in.

- https://github.com/Yberion/analog-nx/tree/vitest-skip
- `npm i`
- `npm run test:app`

Test located in `apps\analog-nx\src\app\app.component.spec.ts`

### Which area/package is the issue in?

vite-plugin-angular

### Description

It seems that https://vitest.dev/guide/filtering.html#skipping-suites-and-tests & co are not working.

### Please provide the exception or error you saw

```true
FAIL  src/app/app.component.spec.ts [ src/app/app.component.spec.ts ]
TypeError: it.skip is not a function
 ❯ src/app/app.component.spec.ts:19:8
     17|
     18|   it('should create 1', () => {
     19|     fixture.detectChanges();
       |        ^
     20|     expect(component).toBeTruthy();
     21|   });
 ❯ _ZoneDelegate.invoke ../../node_modules/zone.js/bundles/zone.umd.js:411:30
 ❯ Zone.run ../../node_modules/zone.js/bundles/zone.umd.js:165:47
 ❯ ../../packages/vite-plugin-angular/setup-vitest.ts:41:21
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

### Other information

Somehow Vitest (`describe`, `it`, ...) typing isn't working on VSCode on this repro. It's working fine on my other project with pnpm.

```
Angular CLI: 17.0.9
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by vneogi199** [comment]
Looks like it works after adding this import to the test file:
`import {describe, beforeEach, it, expect} from 'vitest';`.

I'm assuming these are currently defaulting to `@nx/jest` used by `@nx/angular` plugin instead of the `vitest` ones.

**Comment by brandonroberts** [comment]
Its probably an issue with using the `globals`. Importing them directly should work fine in most cases

**Comment by lukasz-wroblewski** [comment]
as @jahusa02 said 
direct importing causes 
`
Error: Expected to be running in 'ProxyZone', but it was not found.
`

**Comment by brandonroberts** [comment]
> as @jahusa02 said direct importing causes `Error: Expected to be running in 'ProxyZone', but it was not found.`

Yes, that's correct. You have to use the global functions that are patched correctly to operate inside the Zone.js/ProxyZone context

**Comment by brandonroberts** [comment]
@jahusa02 that should work. You can find the patched methods there 

https://github.com/analogjs/analog/blob/beta/packages/vite-plugin-angular/setup-vitest.ts#L251

**Comment by brandonroberts** [comment]
> Hey @brandonroberts,
> 
> I know this issue is closed but I can't get the tests working. Still the same problem. Should I open a new Issue?

Sure, if you could add an example that would be great
