### ISSUE TITLE
Vitest: Error: Failed to resolve import "..." from "...". Does the file exist?

### ISSUE THREAD

**Issue by Yberion** [analogjs/analog#842]
### Please provide the environment you discovered this bug in.

- https://github.com/Yberion/analog-nx/tree/vitest
- `npm i`
- `npm run test:app`

Test located in `apps\analog-nx\src\app\app.component.spec.ts`

The Jest version on the `main` branch works.

### Which area/package is the issue in?

Don't know / other

### Description

It seems that nested component imports aren't working.

In the reproduciton, I'm trying to test `app.component` which import 2 component, `a` and `b`. Component `b` import component `c`.

Imports are properly working on a 1 level depth:

- `app.component`
  - `testa`
  - `testb`

But it does not work for more than 1 depth, so the follow triggers the error:

- `app.component`
  - `testa`
  - `testb`
    - `testc` <--

My goal would be this to compile properly, I want to use [ng-mocks](https://github.com/help-me-mom/ng-mocks) to mock `components`/`service`/`pipe`/...

### Please provide the exception or error you saw

```true
Error: Failed to resolve import "@analog-nx/testc" from "libs\testb\src\lib\testb\testb.component.ts". Does the file exist?
 ❯ formatError ../../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63765:46
 ❯ TransformContext.error ../../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63759:19
 ❯ normalizeUrl ../../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62034:33
 ❯ ../../async file:/E:/Git/analog-nx/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62188:47
 ❯ TransformContext.transform ../../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62109:13
 ❯ Object.transform ../../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:30
 ❯ loadAndTransform ../../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29
 Test Files  1 failed (1)
      Tests  no tests
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

### Other information

Somehow Vitest (`describe`, `it`, ...) typing isn't working on VSCode. It's working fine on my other project with pnpm.

```
Angular CLI: 17.0.9
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by Yberion** [comment]
Hello,

I was able to fix the issue by changing the following in `vite.config.ts` from:

```ts
...
  plugins: [
    angular(),
    viteTsConfigPaths({
      root: './',
    }),
  ],
...
```

To this:

```ts
...
  plugins: [
    angular(),
    viteTsConfigPaths(),
  ],
...
```

@brandonroberts should I make a PR to update the [doc](https://analogjs.org/docs/features/testing/vitest#using-typescript-config-path-aliases) if the "fix" is fine for you?

**Comment by brandonroberts** [comment]
@Yberion sure
