### ISSUE TITLE
[Bug] Failed to parse Markdown file, `mdast-util-definitions` expected node

### ISSUE THREAD

**Issue by runyasak** [analogjs/analog#849]
### Please provide the environment you discovered this bug in.

* Node: v18.19.0
* @analogjs/astro-angular: 0.2.29
* @angular/compiler: 17.0.9
* @astrojs/starlight: 0.15.3
* astro: 4.0.1

Repo: https://github.com/runyasak/my-analog-starlight

### Which area/package is the issue in?

astro-angular

### Description

Hello analog contributors!

First, I want to say that this project is very amazing and I've followed for long time.
Thank you for your great work. 😁

# Overview

I initiated Astro Starlight theme project, installed with `astro-angular`, and ran dev.
Then, the error appeared on the screen:

![Screen Shot 2567-01-11 at 21 50 51](https://github.com/analogjs/analog/assets/6861191/5ca6a11f-b7db-4a63-97a5-346102392e5e)

After that, my web crashed and could not work.
I've tried to install with Astro CLI and manual installation, the results are the same.

# Expected Result

My web should be worked fine with `astro-angular`.

---

If you have any feedback or suggestions, please let me know.

### Please provide the exception or error you saw

```true
[ERROR] Cannot read properties of undefined (reading 'hidden')
  Stack trace:
    at /my-starlight/node_modules/.pnpm/@astrojs+starlight@0.15.3_astro@4.1.1/node_modules/@astrojs/starlight/utils/navigation.ts:176:44
    [...] See full stack trace in the browser, or rerun with --verbose.
[WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/favicon.ico`.

Possible dynamic routes being matched: node_modules/.pnpm/@astrojs+starlight@0.15.3_astro@4.1.1/node_modules/@astrojs/starlight/index.astro.
[ERROR] Failed to parse Markdown file "/my-starlight/node_modules/.pnpm/@astrojs+starlight@0.15.3_astro@4.1.1/node_modules/@astrojs/starlight/components/EmptyMarkdown.md":
mdast-util-definitions expected node
  Stack trace:
    at definitions (file:///my-starlight/node_modules/.pnpm/mdast-util-definitions@6.0.0/node_modules/mdast-util-definitions/lib/index.js:33:11)
    [...] See full stack trace in the browser, or rerun with --verbose.
```
```


### Other information

I need to change `typescript` version to `5.2.2` because Angular does not support `5.3.3` or the latest version for now.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by rlmestre** [comment]
This is due to a known incompatibility between Astro's Remark Shiki plugin and Zone.js. Unless another solution or workaround comes along, we'd have to wait for zoneless.

https://github.com/withastro/astro/issues/8611

**Comment by brandonroberts** [comment]
Thanks @rlmestre. I thought the Astro plugin automatically warned about this?

**Comment by rlmestre** [comment]
Yes, but the current check only considers the configuration of the markdown plugin. This example is using Starlight, and it seems that handles its own markdown config internally. I can look into improving detection to show the warning.

**Comment by runyasak** [comment]
Hi @rlmestre @brandonroberts,
Thank you for taking care of my issue.
I am looking forward to using Angular with Astro by analog. 😁

**Comment by rlmestre** [comment]
I opened an issue in the repo for the dependency that's causing the issue. Unfortunately, I think it's a long shot, but we'll see.

The good news is we finally have a root cause and it doesn't seem to be as big of a deal as native async/await conflicts with Zone. The bad news is we'll continue to run into packages that use async plugins or transformers causing these issues. In this case it's Starlight's expressive code.

You can disable expressive code by passing `false` to the property in starlight's `astro.config`:
```mjs
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import angular from '@analogjs/astro-angular';

export default defineConfig({
  integrations: [starlight({
     expressiveCode: false,
     ...
  })],
});
```

@brandonroberts do we want to add a warning and/or override for this particular one as well?

**Comment by rlmestre** [comment]
My issue/PR were accepted, so the issue has been fixed upstream! To fix it "the right way", we need to wait for the dependency to be updated in `unified` and then Astro. If you want to try it now, you can override the package:

```json
  "pnpm": {
    "overrides": {
      "trough": "2.2.0"
    }
  }
```
