### ISSUE TITLE
Firebase Functions doesn't work out-of-the-box

### ISSUE THREAD

**Issue by duluca** [analogjs/analog#853]
### Please provide the environment you discovered this bug in.

macOS 14.2.1
Node 18 or 20
Firebase CLI 13.0.3
create-analog 0.2.67

### Which area/package is the issue in?

Docs

### Description

At first, I headed directly to the Firebase providers page: https://analogjs.org/docs/features/deployment/providers#firebase. 

This sent me down a path of hours of head-banging because I missed the overview page and wasn't aware of nitro or what it did. This page is very easy to miss: https://analogjs.org/docs/features/deployment/overview

Once I configured `nitro` in `vite.config.ts` I still ran into an issue with `firebase deploy`. 
```
Error: An unexpected error has occurred.
TypeError: Cannot read properties of null (reading 'match')

```

The stack trace was pretty generic. After some searching around, I found the answer on this GitHub thread: https://github.com/nuxt/nuxt/issues/23496#issuecomment-1758748355

It seems like with the different generations and node versions available on Firebase, these must be explicitly stated in the nitro config for things to work properly. 

This is the configuration that worked for me:
```
nitro: {
  preset: 'firebase',
  firebase: {
    nodeVersion: '20',
    gen: 2,
    httpsOptions: {
      region: 'us-east1',
      maxInstances: 100,
    },
  },
},
```

I think it'd be a significant improvement if every provider listed a Nitro config section. This seems to be required to get Firebase working, but even in other providers it would help avoid many unnecessary headaches if someone misses the overview page.

In addition, the DevEx could be further improved if the `npm create` tool asked what cloud provider someone would like to select. That'd also provide additional clues hinting at the need for additional configuration.

### Please provide the exception or error you saw

```true
Error: An unexpected error has occurred.
TypeError: Cannot read properties of null (reading 'match')
```

### Other information

Also I saw a warning saying:
```
 ⚠  functions: Couldn't find firebase-functions package in your source code. Have you run 'npm install'?
```
This seems to be benign. If this is expected behavior, it should also be documented.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Thanks @duluca. That would be great to add. When I initially went through the deployment process for Firebase for the guide, this extra configuration wasn't needed.

**Comment by pebblecreek** [comment]
@duluca  Thank you !!! It works.  I was banging my head all day trying to figure out the right nitro config and I found your post. Thank you for figuring out the nitro config.
