### ISSUE TITLE
Generating page converts "/" into ","

### ISSUE THREAD

**Issue by mackelito** [analogjs/analog#860]
### Please provide the environment you discovered this bug in.

N/A

### Which area/package is the issue in?

Don't know / other

### Description

Running
````
npx nx generate @analogjs/platform:page --pathname='(customers)'/demo/home --project=demoApp --no-interactive --dry-run                    

>  NX  Generating @analogjs/platform:page

CREATE demoApp/src/app/pages/(customers),demo/home.page.ts
````
### Please provide the exception or error you saw

```true
Wrong path
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by mackelito** [comment]
Just a quick update:
It seems to always work if we only have 1 "/"
`--pathname='(customers)'/demo` creates the file `/src/app/pages/(customers)/demo.page.ts`.. but adding a second "/" does not work.. 

but the next one works... `--pathname='(customers)'/demo/test/home` creates `/src/app/pages/(customers),demo,test/home.page.ts`

**Comment by brandonroberts** [comment]
Does this work if you put the whole path in quotes? `--pathname='(customers)/demo/test/home'`

**Comment by luishcastroc** [comment]
I can take a look at this as well @brandonroberts

**Comment by mackelito** [comment]
> Does this work if you put the whole path in quotes? `--pathname='(customers)/demo/test/home'`

Nope... same result :/

**Comment by luishcastroc** [comment]
@brandonroberts  just sent a PR that should solve this.
