### ISSUE TITLE
Docs: Add guide for implementing custom markdown renderer

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#874]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

The `@analogjs/content` package has a [ContentRenderer](https://github.com/analogjs/analog/blob/main/packages/content/src/lib/content-renderer.ts) abstract class that can be implemented and provided to use a different renderer for markdown content, such as remark with rehype

This needs to be documented to show how to create a custom renderer for those who want to use something other than the built-in one with marked and Prism.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by joshuamorony** [comment]
I'll be implementing remark/rehype shortly so I can create a PR for the docs once I'm done with that

**Comment by brandonroberts** [comment]
Closing this as we've moved markdown rendering to build time with prism/shiki and will revisit custom renderers
