### ISSUE TITLE
[bug] Can't make styleurl to dynamic route due to regex replacement in compiler

### ISSUE THREAD

**Issue by chris-kruining** [analogjs/analog#876]
I have a component on a dynamic route. and I follow the convention to have the same name for my css file, as I do for my component.

meaning that a `[param].page.ts` component will have a stylesheet of `[param].page.css`

however, due to the replace this line does the resulting url in runtime would be `param.page.css`

https://github.com/analogjs/analog/blob/081a17893fa68b231334a4949039bd65e8c13be1/packages/vite-plugin-angular/src/lib/component-resolvers.ts#L53

**Comment by chris-kruining** [comment]
I have a working "fix" the code is ugly and error prone, the regex barely readable. but at least this works:

```js
const styleUrlPaths = matchedStyleUrls
  .match(/^\s*styleUrls?\s*\:\s*\[?((?:(?:"|')[^'"]+(?:"|'),?\s*)+)\]?$/)[1]
  .replace(/"|'|\s/g, '')
  .split(',');
```

**Comment by brandonroberts** [comment]
I think that's an ok fix for now, but yes something that uses an AST to parse out the templateUrls and styleUrls would be better.

**Comment by rlmestre** [comment]
I can work on this if needed. Very similar/related to #887
