### ISSUE TITLE
SSG from content directory is not working when contentDir doesn't start with '/'

### ISSUE THREAD

**Issue by remes2000** [analogjs/analog#894]
### Please provide the environment you discovered this bug in.

https://github.com/remes2000/mnieruchalski.me/tree/analog-bug

### Which area/package is the issue in?

vite-plugin-nitro

### Description

I'm creating a blog and I want to prerender all of the blog posts. I store each blog post in .md file in src/content directory. I was following the steps described in this section https://analogjs.org/docs/features/server/static-site-generation#from-content-directory but sadly my posts weren't available in dist catalog (also there weren't any errors nor warnings present)

After a while I've noticed, that this feature will only work if contentDir starts with '/' character (but in the example from documentation there's no '/' at the beginning of contentDir).

So to sum-up:
This is not working:
```
prerender: {
      routes: async () => [
        '/',
        '/blog',
        {
          contentDir: 'src/content',
          transform: (file: PrerenderContentFile) => {
            // use the slug from frontmatter if defined, otherwise use the files basename
            const slug = file.attributes['slug'] || file.name;
            return `/blog/${slug}`;
          },

        },
      ],
 },
```
This is working:
```
prerender: {
      routes: async () => [
        '/',
        '/blog',
        {
          contentDir: '/src/content',
          transform: (file: PrerenderContentFile) => {
            // use the slug from frontmatter if defined, otherwise use the files basename
            const slug = file.attributes['slug'] || file.name;
            return `/blog/${slug}`;
          },

        },
      ],
 },
```

If it's intended we should only update the documentation. If it's not intended (and I believe it's not) we need a proper fix. 

### Please provide the exception or error you saw

```true
No error nor warning present
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by remes2000** [comment]
I think the issue is here
https://github.com/analogjs/analog/blob/main/packages/vite-plugin-nitro/src/lib/utils/get-content-files.ts#L18

I could replace the lines with
```
const resolvedDir = normalizePath(path.join(root, glob));
const contentFiles: string[] = fg.sync([`${resolvedDir}/*`], {
  dot: true,
});
```

**Comment by brandonroberts** [comment]
Fixed via https://github.com/analogjs/analog/pull/895
