### ISSUE TITLE
Data files - multiple content on one page

### ISSUE THREAD

**Issue by MarcinMichalik** [analogjs/analog#928]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

It would be nice to have data files like in [jekyll](https://jekyllrb.com/docs/datafiles/). 

What I am trying to achieve: I would like to have all my projects on one page. I don't want to split all projects in separate pages. My first thought was that I create 'projects' in content folder and there I added all md files, but I don't known how to get content all files on one page. It would be nice to have data files with md (formatted content).

Maybe I misunderstood something in the documentation, so please explain.

### Describe any alternatives/workarounds you're currently using

I am trying to workaround by adding data files to `assets` folder and use `HTTPClient`.  My page is generating, but the console shows an error `ERROR TypeError: Failed to parse URL from /data/projects.json`

If I have a full workaround ready, then I will share it.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by nckirik** [comment]
@joshuamorony's video might help, since it sounds like his case is very similar to yours

https://youtu.be/o6novBbaHis?si=LRhj5CBWnfayKtc_

**Comment by brandonroberts** [comment]
@MarcinMichalik you need to use the full URL to the `/data/projects.json` file, such as `http://localhost:5173/data/projects.json`
