### ISSUE TITLE
[QUESTION] Error during build

### ISSUE THREAD

**Issue by Fronikuniu** [analogjs/analog#931]
### Please provide the environment you discovered this bug in.

package.json

{
  "name": "@analogjs3/source",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {},
  "dependencies": {
    "@analogjs/content": "^0.2.0",
    "@analogjs/router": "^0.2.0",
    "@angular/animations": "^17.2.0",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/forms": "^17.2.0",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/platform-server": "^17.2.0",
    "@angular/router": "^17.2.0",
    "dotenv": "^16.4.5",
    "front-matter": "^4.0.2",
    "marked": "^5.0.2",
    "marked-gfm-heading-id": "^3.1.0",
    "marked-highlight": "^2.0.1",
    "mermaid": "^10.2.4",
    "prismjs": "^1.29.0",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.14.0"
  },
  "devDependencies": {
    "@analogjs/platform": "^0.2.0",
    "@analogjs/vite-plugin-angular": "^0.2.0",
    "@analogjs/vite-plugin-nitro": "^0.2.45",
    "@angular-devkit/build-angular": "^17.2.0",
    "@angular/compiler-cli": "^17.2.0",
    "@nx/angular": "^18.0.0",
    "@nx/devkit": "^18.0.0",
    "@nx/eslint": "^18.0.0",
    "@nx/js": "18.0.8",
    "@nx/vite": "^18.0.0",
    "@nx/workspace": "18.0.8",
    "autoprefixer": "^10.4.0",
    "jsdom": "^22.1.0",
    "nx": "18.0.8",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.2",
    "typescript": "~5.3.0",
    "vite": "~5.0.0",
    "vite-tsconfig-paths": "^4.2.0",
    "vitest": "^1.0.4"
  }
}

### Which area/package is the issue in?

Don't know / other

### Description

Hi, I have a question about the build. When I use the command `npx nx run frontend:build` I get this error: 
![image](https://github.com/analogjs/analog/assets/26391807/6502a958-8a41-4b95-93f3-d15ecc744b94)
Does anyone know what could be the cause?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
What's in your `vite.config.ts`?

**Comment by Fronikuniu** [comment]
> What's in your `vite.config.ts`?

/// <reference types="vitest" />

import analog from "@analogjs/platform";
import { defineConfig, Plugin, splitVendorChunkPlugin } from "vite";
import { nxViteTsPaths } from "@nx/vite/plugins/nx-tsconfig-paths.plugin";
import nitro from "@analogjs/vite-plugin-nitro";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    root: __dirname,
    publicDir: "src/public",
    resolve: {
      mainFields: ["module"],
    },
    build: {
      outDir: "../../dist/apps/frontend/client",
      reportCompressedSize: true,
      commonjsOptions: { transformMixedEsModules: true },
      target: ["es2020"],
    },
    plugins: [analog(), nxViteTsPaths(), splitVendorChunkPlugin(), nitro()],
    test: {
      globals: true,
      environment: "jsdom",
      setupFiles: ["src/test-setup.ts"],
      include: ["**/*.spec.ts"],
      reporters: ["default"],
      cache: {
        dir: `../../node_modules/.vitest`,
      },
    },
    define: {
      "import.meta.vitest": mode !== "production",
    },
  };
});

**Comment by brandonroberts** [comment]
The `nitro` plugin doesn't need to be there, its already included with the `analog` plugin

**Comment by Fronikuniu** [comment]
Here is repo: [](https://github.com/Fronikuniu/analogjs-boilerplate), Even without nitro() im getting error: 
![image](https://github.com/analogjs/analog/assets/26391807/a4766da4-5297-451f-bf7c-4a42c8098bb2)

**Comment by brandonroberts** [comment]
I cloned your repo, removed `nitro`, and everything built fine for me, but I'm not on Windows. Can you try it with WSL also?
