### ISSUE TITLE
Errors when creating new app (missing packages and module)

### ISSUE THREAD

**Issue by cerivitos** [analogjs/analog#945]
### Please provide the environment you discovered this bug in.

v20.11.1 and v18.13.0 (tested with both)

### Which area/package is the issue in?

create-analog

### Description

When creating a fresh app using 
`npm create analog/@latest` with Tailwind
`npm install`
`npm run start` the following errors are seen.

1. Missing `@ngtools/webpack` package
2. Missing `@angular-devkit/build-angular` package
3. `.js` files need to be manually renamed to `.cjs`, same issue as #941 
4. Missing `vite-plugin-nitro` 

### Please provide the exception or error you saw

```true
1st error:
failed to load config from C:\Users\ceriv\Angular projects\link-me\vite.config.ts
An unhandled exception occurred: Cannot find package '@ngtools/webpack' imported from C:\Users\ceriv\Angular projects\link-me\node_modules@analogjs\vite-plugin-angular\src\lib\host.js
See "C:\Users\ceriv\AppData\Local\Temp\ng-3cAtD8\angular-errors.log" for further details.

2nd error:
failed to load config from C:\Users\ceriv\Angular projects\link-me\vite.config.ts
An unhandled exception occurred: Cannot find package '@angular-devkit/build-angular' imported from C:\Users\ceriv\Angular projects\link-me\node_modules@analogjs\vite-plugin-angular\src\lib\utils\devkit.js
See "C:\Users\ceriv\AppData\Local\Temp\ng-6rMUFM\angular-errors.log" for further details.

3rd error:
[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: C:/Users/ceriv/Angular projects/link-me): [ReferenceError] module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Users\ceriv\Angular projects\link-me\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Users\ceriv\Angular projects\link-me\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

4th error:
[worker reload] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\C:\Users\ceriv\Angular projects\link-me\node_modules@analogjs\vite-plugin-nitro\src\lib\runtime\api-middleware' imported from C:\Users\ceriv\Angular projects\link-me\dist.nitro\dev\index.mjs
```

### Other information

After manually fixing for 1, 2 and 3, it seems that the base app can run normally despite the error message in point 4. However I haven't gone ahead on any development so unknown if there is any impact.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by monacodelisa** [comment]
@cerivitos upon creating the app - did you have the initial `dist` folder ?

**Comment by monacodelisa** [comment]
prior the `dist` folder was getting generated on starting the dev server 
`npm start`, `ng serve`, `npm run start` - they were all generating a `dist` folder containing `.nitro` 
so this is related to that error (4th error) and on windows

**Comment by monacodelisa** [comment]
as far as I can see - it is not getting generated anywhere

**Comment by Micha-Richter** [comment]
maybe related to https://github.com/nrwl/nx/issues/8614 ?
does --skip-nx-cache help, @monacodelisa ?

**Comment by monacodelisa** [comment]
@Micha-Richter I just tried it, sadly it makes no difference, 
I will be exploring but... the Analog environment new to me, 
I wish I knew where I'm supposed to look... but I'll keep trying :)
thank you for suggesting something to try out

**Comment by monacodelisa** [comment]
the thing is that I have not made any changes to my dev env, in the first app there was noting that I needed to setup or add or adjust - it just ran fine locally

**Comment by monacodelisa** [comment]
Since the issues are OS related I decided to try switching to `codespaces` 
- and everything works like a charm over there - serving the app, building the app 
if someone is looking for a temporary solution - give `codespaces` a try at least 
this way you can keep on coding and exploring Analog 😊

**Comment by monacodelisa** [comment]
@brandonroberts 

| Environment | Codespaces               | Windows                  |
|-------------|--------------------------|--------------------------|
| create command | `npm create analog@latest` | `npm create analog@latest` |
| next step | `npm i` | `npm i` |
| on `npm start` generation of `dist` | ✅ | ✅ |
| subfolders `.nitro/dev` and `.nitro/types` | ✅ | ✅ | 
| generation of `nitro.json` | ✅ | ❌ |

hope this helps a bit at least

**Comment by ferat** [comment]
I also experience these problems. I wonder if it applies to all Windows (11) users.

**Comment by brandonroberts** [comment]
Working on a fix here and setting up a workflow to build on Windows https://github.com/analogjs/analog/pull/949.

**Comment by brandonroberts** [comment]
Thanks everyone. Analog 1.0.2 has been released with the fixes for Windows.
