### ISSUE TITLE
Add Vite docs to Integrations sidebar

### ISSUE THREAD

**Issue by crutchcorn** [analogjs/analog#947]
It would be nice to have a link to Vite as an integrations on the docs page sidebar:

https://analogjs.org/docs/packages/vite-plugin-angular/overview

<img width="297" alt="image" src="https://github.com/analogjs/analog/assets/9100169/566737ca-1623-475c-a584-02a46a379267">

I'm happy to add a PR to do this or add a docs page for the Vite integration

**Comment by brandonroberts** [comment]
Good idea.  I had an existing issue here that's similar

https://github.com/analogjs/analog/issues/812
