### ISSUE TITLE
[BUG]: astro-angular integration broke Astro <script> tag

### ISSUE THREAD

**Issue by alfredogonzalezmartinez** [analogjs/analog#95]
### Please provide the environment you discovered this bug in.

[Error reproduction](https://stackblitz.com/edit/analogjs-astro-angular?file=src/pages/index.astro)

### Which area/package is the issue in?

astro-angular

### Description

Script tag doesn't work in astro components when I add @analogjs/astro-angular to my Astro project.

Script tag works when I add `is:inline` directive or an atribute. But, it is a problem when I´m using TypeScript inside or I need to import a external script, because is necessary that Astro bundle it and that is not working with astro-angular integration.

[Astro docs - Client-Side Scripts](https://docs.astro.build/en/core-concepts/astro-components/#client-side-scripts)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Fixed with https://github.com/analogjs/analog/pull/98

**Comment by brandonroberts** [comment]
This fix has been released with `@analogjs/astro-angular` version `0.1.0-beta.2`
