### ISSUE TITLE
can't run project with angular 16 version

### ISSUE THREAD

**Issue by unrealphong** [analogjs/analog#951]
### Please provide the environment you discovered this bug in.

create project and launch it with angular version 16

### Which area/package is the issue in?

Don't know / other

### Description

i initialize the project with angular 16 and launch the project and get this error: 

> "failed to load config from /Users/username/personal/playground/analog-project/vite.config.ts
> TypeError: (0 , import_platform.default) is not a function
>      at /Users/username/personal/playground/analog-project/vite.config.ts:46:41
>      at loadConfigFromFile (file:///Users/username/personal/playground/analog-project/node_modules/vite/dist/node/chunks/dep-52909643.js:66184:15)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async resolveConfig (file:///Users/username/personal/playground/analog-project/node_modules/vite/dist/node/chunks/dep-52909643.js:65777:28)
>      at async _createServer (file:///Users/username/personal/playground/analog-project/node_modules/vite/dist/node/chunks/dep-52909643.js:65051:20)
>      at async viteDevServerExecutor (/Users/username/personal/playground/analog-project/node_modules/@nx/vite/src/executors/dev-server/dev-server.impl.js:34:24)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Thanks @unrealphong. Is there any reason you aren't using Angular v17 for a new app?

**Comment by unrealphong** [comment]
I haven't had time to learn the new functions of angular 17, so I'm still using version 16

**Comment by woxpillar** [comment]
similar problem in angular 17 as well

**Comment by charlesritchea** [comment]
Can we get better documentation on Angular version support in general. I'm stuck on 15 because I'm stuck on Material 14 because I'm stuck on custom styles. Anyway, would be nice to know right away whether I can use this or not

**Comment by brandonroberts** [comment]
Angular v15 is not supported with the latest versions because of changes to the file structure in the Angular Devkit. We have a compatibility table here that needs a bit of updating, but anything Angular v16.1.x and above is supported by the latest release.

https://github.com/analogjs/analog/blob/beta/packages/nx-plugin/src/generators/app/versions/README.md

**Comment by charlesritchea** [comment]
Thank you!

**Comment by charlesritchea** [comment]
Yeah, I don't want to go on a bunch of angry tangents because it's not your fault I'm in this situation, but 0.1.0.beta.22... is not going to work. Guess it's back to jest

**Comment by brandonroberts** [comment]
👋  We've landed a fix in the plugin to support different versions of Angular, and now v15 is supported with the `1.3.1-beta.3` release of `@analogjs/vite-plugin-angular`. Feel free to test it out before it goes out in `1.3.1`

PR: https://github.com/analogjs/analog/pull/1077
