### ISSUE TITLE
Integration with astro: There are logs with 'Angular is running in development mode.'

### ISSUE THREAD

**Issue by alator21** [analogjs/analog#966]
### Please provide the environment you discovered this bug in.

-

### Which area/package is the issue in?

astro-angular

### Description

I created a brand new astro app, and followed the instructions to integrate with analog. Afterwards, i ran `astro build` and then `node dist/server/entry.mjs`. When navigating to my site on `https://localhost:4321` , I see logs in the console 
```
Angular is running in development mode.
```

Side info:

I have 2 `.env` files. One for prod `.env.production` and one for dev '.env.development'.  The production variables are loaded using the above instructions, so I would expect that the production build of the angular components would be triggered as well.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
We're using the `astro:build:setup` hook to call `enableProdMode()` here 

https://github.com/analogjs/analog/blob/beta/packages/astro-angular/src/index.ts#L95

Looks like we need to switch to `astro:build:start` 

https://docs.astro.build/en/reference/integrations-reference/#astrobuildstart

**Comment by alator21** [comment]
@brandonroberts Should I go for it? Is this the only change that is needed?

**Comment by brandonroberts** [comment]
@alator21 sure. It should be. You can test it locally first

**Comment by alator21** [comment]
Putting the `enableProdMode();` on the `astro:build:start` didn't make any difference - still got the logs. When i put it as the last line on the `astro:config:done` , i no longer get the `Angular is running in development mode.` message.
