### ISSUE TITLE
Cannot find package '@ngtools/webpack' On MacOs when starting the project

### ISSUE THREAD

**Issue by tleveque23** [analogjs/analog#967]
### Please provide the environment you discovered this bug in.

MacOs 14.4.1
NodeJs v20.11.0

### Which area/package is the issue in?

create-analog

### Description

I follow the Getting started guide.
> yarn create analog
Go in the directory
> yarn
> yarn start

### Please provide the exception or error you saw

```true
failed to load config from /Users/thierryleveque/Documents/dev/testProject/analog-project/vite.config.ts
An unhandled exception occurred: Cannot find package '@ngtools/webpack' imported from /Users/thierryleveque/Documents/dev/testProject/analog-project/node_modules/@analogjs/vite-plugin-angular/src/lib/host.js
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Only when using yarn, you have to explicitly add the `@ngtools/webpack` package to the `package.json`.

```sh
yarn add @ngtools/webpack --dev
```

We could maybe detect this when generating a new app, but I don't want to add it for everyone

**Comment by tleveque23** [comment]
And then now it is @angular-devkit/build-angular that is missing...
Adding it also fix the problem.
But this should be added in the documentation. On the getting started page.
