### ISSUE TITLE
Feature: Server Only Components

### ISSUE THREAD

**Issue by jdgamble555** [analogjs/analog#989]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Hear me out. This would be amazing. Imagine creating the DOM on the server and rendering the HTML for non-interactive components. I doubt Angular will every go in this direction unless Solid and Svelte get on board one day (no idea).  It would simplify hydration (you wouldn't need it), and make things beautiful. 

I would think you start with just routes (think something like `component.server.analog`.  Basically having a `.server` in the name makes it a server component. Later you could add client components inside the server component maybe.

This could be easier than it sounds if the complexity is not crazy.

### Describe any alternatives/workarounds you're currently using

- [React Server Components](https://react.dev/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023#react-server-components)
- [Nuxt Server Components - Island Architecture](https://nuxt.com/docs/guide/directory-structure/components#server-components)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by tobiasegli** [comment]
@jdgamble555, with Angular v19 this feature just got released (in preview) as part of incremental hydration.
https://angular.dev/guide/incremental-hydration#hydrate-never

**Comment by jdgamble555** [comment]
Not the same thing. What Angular is missing and has always been missing (and seemingly will always be missing) is server only code.

I want to generate the html safely on the server, fetch from a database with private credentials, all in one component, and seemingly have child client components that can be reactive.

This is what RSC can do.

Unless I'm missing something.

J

**Comment by brandonroberts** [comment]
Yea, that's the target with this feature. Ideally, it would work alongside incremental hydration, but all the rendered content is done server-side, even with support for props. I have a prototype working already

**Comment by jdgamble555** [comment]
Could you run server safe code? (ex fetch from db with credentials hidden from client)
