### ISSUE TITLE
Build & Deploy on CloudFlare Pages issue

### ISSUE THREAD

**Issue by dalenguyen** [analogjs/analog#999]
### Please provide the environment you discovered this bug in.

Workspace: Nx

Repo: https://github.com/dalenguyen/cloudflare-challange

### Which area/package is the issue in?

Don't know / other

### Description

I'm generating a new Analog app using Nx workspace. When I try to build and deploy the app to CloudFlare pages, there are issues locally and on cloud flare:

## Locally

Here is my configuration for nitro:

```
   plugins: [
      analog({
        nitro: {
          output: {
            dir: "./dist/ai/analog/public",
            serverDir: "./dist/ai/analog/public/_worker.js",
          },
        },
      }),
 ```

After running the build, there're two places where it save the file. This one is in the wrong place:

<img width="230" alt="image" src="https://github.com/analogjs/analog/assets/14116156/b16609ff-19ee-4ea4-94c6-4de3f552b52d">

It suppose to be in the same place under `dist`:

<img width="154" alt="image" src="https://github.com/analogjs/analog/assets/14116156/bde6fcc5-af26-4ae9-a327-2642509f8d2f">

## On CloudFlare

Looks like it only generate the `client` and `ssr` folder.

<img width="659" alt="image" src="https://github.com/analogjs/analog/assets/14116156/b2635da1-e9e4-410c-9773-603df0725ca5">

There's no `dist/ai/analog/public` being generated.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
When you deploy to Cloudflare, it builds correctly for the environment. If you want to do it locally, you need to specify the BUILD_PRESET

```sh
BUILD_PRESET=cloudflare-pages ng build
```

**Comment by dalenguyen** [comment]
It does work if I set the path to `ai/dist/ai/analog/public` in CloudFlare. Is it the build issue (feature) in Nx workspace? 🤔
